<?php

/**
 * BaseBodega
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idbodega
 * @property string $ca_nombre
 * @property string $ca_tipo
 * @property string $ca_transporte
 * @property timestamp $ca_fchcreado
 * @property string $ca_usucreado
 * @property timestamp $ca_fchactualizado
 * @property string $ca_usuactualizado
 * @property integer $ca_cod_dian
 * @property integer $ca_direccion
 * @property integer $ca_identificacion
 * @property Doctrine_Collection $Reporte
 * 
 * @method integer             getCaIdbodega()        Returns the current record's "ca_idbodega" value
 * @method string              getCaNombre()          Returns the current record's "ca_nombre" value
 * @method string              getCaTipo()            Returns the current record's "ca_tipo" value
 * @method string              getCaTransporte()      Returns the current record's "ca_transporte" value
 * @method timestamp           getCaFchcreado()       Returns the current record's "ca_fchcreado" value
 * @method string              getCaUsucreado()       Returns the current record's "ca_usucreado" value
 * @method timestamp           getCaFchactualizado()  Returns the current record's "ca_fchactualizado" value
 * @method string              getCaUsuactualizado()  Returns the current record's "ca_usuactualizado" value
 * @method integer             getCaCodDian()         Returns the current record's "ca_cod_dian" value
 * @method integer             getCaDireccion()       Returns the current record's "ca_direccion" value
 * @method integer             getCaIdentificacion()  Returns the current record's "ca_identificacion" value
 * @method Doctrine_Collection getReporte()           Returns the current record's "Reporte" collection
 * @method Bodega              setCaIdbodega()        Sets the current record's "ca_idbodega" value
 * @method Bodega              setCaNombre()          Sets the current record's "ca_nombre" value
 * @method Bodega              setCaTipo()            Sets the current record's "ca_tipo" value
 * @method Bodega              setCaTransporte()      Sets the current record's "ca_transporte" value
 * @method Bodega              setCaFchcreado()       Sets the current record's "ca_fchcreado" value
 * @method Bodega              setCaUsucreado()       Sets the current record's "ca_usucreado" value
 * @method Bodega              setCaFchactualizado()  Sets the current record's "ca_fchactualizado" value
 * @method Bodega              setCaUsuactualizado()  Sets the current record's "ca_usuactualizado" value
 * @method Bodega              setCaCodDian()         Sets the current record's "ca_cod_dian" value
 * @method Bodega              setCaDireccion()       Sets the current record's "ca_direccion" value
 * @method Bodega              setCaIdentificacion()  Sets the current record's "ca_identificacion" value
 * @method Bodega              setReporte()           Sets the current record's "Reporte" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBodega extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_bodegas');
        $this->hasColumn('ca_idbodega', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ca_nombre', 'string', 80, array(
             'type' => 'string',
             'length' => '80',
             ));
        $this->hasColumn('ca_tipo', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_transporte', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchcreado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usucreado', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchactualizado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usuactualizado', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_cod_dian', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_direccion', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_identificacion', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Reporte', array(
             'local' => 'ca_idbodega',
             'foreign' => 'ca_idbodega'));
    }
}