<?php

/**
 * BaseIdgRiesgos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idriesgo
 * @property integer $ca_idproceso
 * @property string $ca_codigo
 * @property string $ca_riesgo
 * @property string $ca_etapa
 * @property string $ca_potenciador
 * @property string $ca_controles
 * @property string $ca_ap
 * @property string $ca_contingencia
 * @property string $ca_usucreado
 * @property timestamp $ca_fchcreado
 * @property string $ca_usuactualizado
 * @property timestamp $ca_fchactualizado
 * @property integer $ca_impresion
 * @property boolean $ca_laft
 * @property boolean $ca_activo
 * @property IdgProcesos $IdgProcesos
 * @property Doctrine_Collection $IdgFactor
 * @property Usuario $UsuCreado
 * @property Usuario $UsuActualizado
 * @property Doctrine_Collection $IdgValoracion
 * @property Doctrine_Collection $IdgEventos
 * @property Doctrine_Collection $IdgCausas
 * 
 * @method integer             getCaIdriesgo()        Returns the current record's "ca_idriesgo" value
 * @method integer             getCaIdproceso()       Returns the current record's "ca_idproceso" value
 * @method string              getCaCodigo()          Returns the current record's "ca_codigo" value
 * @method string              getCaRiesgo()          Returns the current record's "ca_riesgo" value
 * @method string              getCaEtapa()           Returns the current record's "ca_etapa" value
 * @method string              getCaPotenciador()     Returns the current record's "ca_potenciador" value
 * @method string              getCaControles()       Returns the current record's "ca_controles" value
 * @method string              getCaAp()              Returns the current record's "ca_ap" value
 * @method string              getCaContingencia()    Returns the current record's "ca_contingencia" value
 * @method string              getCaUsucreado()       Returns the current record's "ca_usucreado" value
 * @method timestamp           getCaFchcreado()       Returns the current record's "ca_fchcreado" value
 * @method string              getCaUsuactualizado()  Returns the current record's "ca_usuactualizado" value
 * @method timestamp           getCaFchactualizado()  Returns the current record's "ca_fchactualizado" value
 * @method integer             getCaImpresion()       Returns the current record's "ca_impresion" value
 * @method boolean             getCaLaft()            Returns the current record's "ca_laft" value
 * @method boolean             getCaActivo()          Returns the current record's "ca_activo" value
 * @method IdgProcesos         getIdgProcesos()       Returns the current record's "IdgProcesos" value
 * @method Doctrine_Collection getIdgFactor()         Returns the current record's "IdgFactor" collection
 * @method Usuario             getUsuCreado()         Returns the current record's "UsuCreado" value
 * @method Usuario             getUsuActualizado()    Returns the current record's "UsuActualizado" value
 * @method Doctrine_Collection getIdgValoracion()     Returns the current record's "IdgValoracion" collection
 * @method Doctrine_Collection getIdgEventos()        Returns the current record's "IdgEventos" collection
 * @method Doctrine_Collection getIdgCausas()         Returns the current record's "IdgCausas" collection
 * @method IdgRiesgos          setCaIdriesgo()        Sets the current record's "ca_idriesgo" value
 * @method IdgRiesgos          setCaIdproceso()       Sets the current record's "ca_idproceso" value
 * @method IdgRiesgos          setCaCodigo()          Sets the current record's "ca_codigo" value
 * @method IdgRiesgos          setCaRiesgo()          Sets the current record's "ca_riesgo" value
 * @method IdgRiesgos          setCaEtapa()           Sets the current record's "ca_etapa" value
 * @method IdgRiesgos          setCaPotenciador()     Sets the current record's "ca_potenciador" value
 * @method IdgRiesgos          setCaControles()       Sets the current record's "ca_controles" value
 * @method IdgRiesgos          setCaAp()              Sets the current record's "ca_ap" value
 * @method IdgRiesgos          setCaContingencia()    Sets the current record's "ca_contingencia" value
 * @method IdgRiesgos          setCaUsucreado()       Sets the current record's "ca_usucreado" value
 * @method IdgRiesgos          setCaFchcreado()       Sets the current record's "ca_fchcreado" value
 * @method IdgRiesgos          setCaUsuactualizado()  Sets the current record's "ca_usuactualizado" value
 * @method IdgRiesgos          setCaFchactualizado()  Sets the current record's "ca_fchactualizado" value
 * @method IdgRiesgos          setCaImpresion()       Sets the current record's "ca_impresion" value
 * @method IdgRiesgos          setCaLaft()            Sets the current record's "ca_laft" value
 * @method IdgRiesgos          setCaActivo()          Sets the current record's "ca_activo" value
 * @method IdgRiesgos          setIdgProcesos()       Sets the current record's "IdgProcesos" value
 * @method IdgRiesgos          setIdgFactor()         Sets the current record's "IdgFactor" collection
 * @method IdgRiesgos          setUsuCreado()         Sets the current record's "UsuCreado" value
 * @method IdgRiesgos          setUsuActualizado()    Sets the current record's "UsuActualizado" value
 * @method IdgRiesgos          setIdgValoracion()     Sets the current record's "IdgValoracion" collection
 * @method IdgRiesgos          setIdgEventos()        Sets the current record's "IdgEventos" collection
 * @method IdgRiesgos          setIdgCausas()         Sets the current record's "IdgCausas" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseIdgRiesgos extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('idg.tb_riesgos');
        $this->hasColumn('ca_idriesgo', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ca_idproceso', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ca_codigo', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('ca_riesgo', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_etapa', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_potenciador', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_controles', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_ap', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_contingencia', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_usucreado', 'string', 15, array(
             'type' => 'string',
             'length' => '15',
             ));
        $this->hasColumn('ca_fchcreado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usuactualizado', 'string', 15, array(
             'type' => 'string',
             'length' => '15',
             ));
        $this->hasColumn('ca_fchactualizado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_impresion', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_laft', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('ca_activo', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('IdgProcesos', array(
             'local' => 'ca_idproceso',
             'foreign' => 'ca_idproceso'));

        $this->hasMany('IdgFactor', array(
             'local' => 'ca_idriesgo',
             'foreign' => 'ca_idriesgo'));

        $this->hasOne('Usuario as UsuCreado', array(
             'local' => 'ca_usucreado',
             'foreign' => 'ca_login'));

        $this->hasOne('Usuario as UsuActualizado', array(
             'local' => 'ca_usuactualizado',
             'foreign' => 'ca_login'));

        $this->hasMany('IdgValoracion', array(
             'local' => 'ca_idriesgo',
             'foreign' => 'ca_idriesgo'));

        $this->hasMany('IdgEventos', array(
             'local' => 'ca_idriesgo',
             'foreign' => 'ca_idriesgo'));

        $this->hasMany('IdgCausas', array(
             'local' => 'ca_idriesgo',
             'foreign' => 'ca_idriesgo'));
    }
}