<?php

/**
 * BaseIdsTipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ca_tipo
 * @property string $ca_nombre
 * @property string $ca_aplicacion
 * @property IdsAgente $IdsAgente
 * @property IdsProveedor $IdsProveedor
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6365 2009-09-15 18:22:38Z jwage $
 */
abstract class BaseIdsTipo extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ids.tb_tipos');
        $this->hasColumn('ca_tipo', 'string', 3, array(
             'type' => 'string',
             'primary' => true,
             'length' => '3',
             ));
        $this->hasColumn('ca_nombre', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('ca_aplicacion', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('IdsAgente', array(
             'local' => 'ca_tipo',
             'foreign' => 'ca_tipo'));

        $this->hasOne('IdsProveedor', array(
             'local' => 'ca_tipo',
             'foreign' => 'ca_tipo'));
    }
}