<?php

/**
 * BaseInoViExpoAduana
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idmaster
 * @property string $ca_referencia
 * @property integer $ca_ano
 * @property string $ca_mes
 * @property integer $ca_idreporte
 * @property string $ca_consecutivo
 * @property integer $ca_version
 * @property string $ca_sucursal
 * @property string $ca_traorigen
 * @property string $ca_origen
 * @property string $ca_ciuorigen
 * @property string $ca_destino
 * @property string $ca_ciudestino
 * @property string $ca_modalidad
 * @property string $ca_impoexpo
 * @property string $ca_transporte
 * @property integer, $ca_peso
 * @property integer, $ca_piezas
 * @property integer, $ca_volumen
 * @property date, $ca_fchllegada
 * @property date, $ca_fchsalida
 * @property string $ca_aplicaidg
 * @property integer $ca_idregimen
 * @property string $ca_regimen
 * @property integer $ca_idcliente
 * @property string $ca_compania
 * @property integer $ca_idagencia
 * @property string $ca_agencia
 * @property integer $ca_idlinea
 * @property string $ca_linea
 * @property integer $ca_idagente
 * @property string $ca_agente
 * @property string $ca_vendedor
 * @property string $ca_coordinador
 * @property string $ca_proveedor
 * @property string $ca_pedido
 * @property date $ca_fchcreado
 * @property string $ca_usucreado
 * @property date $ca_fchactualizado
 * @property string $ca_usuactualizado
 * @property date $ca_fchliquidado
 * @property string $ca_usuliquidado
 * @property date $ca_fchcerrado
 * @property string $ca_usucerrado
 * @property Reporte $Reporte
 * @property Usuario $Usuario
 * 
 * @method integer         getCaIdmaster()        Returns the current record's "ca_idmaster" value
 * @method string          getCaReferencia()      Returns the current record's "ca_referencia" value
 * @method integer         getCaAno()             Returns the current record's "ca_ano" value
 * @method string          getCaMes()             Returns the current record's "ca_mes" value
 * @method integer         getCaIdreporte()       Returns the current record's "ca_idreporte" value
 * @method string          getCaConsecutivo()     Returns the current record's "ca_consecutivo" value
 * @method integer         getCaVersion()         Returns the current record's "ca_version" value
 * @method string          getCaSucursal()        Returns the current record's "ca_sucursal" value
 * @method string          getCaTraorigen()       Returns the current record's "ca_traorigen" value
 * @method string          getCaOrigen()          Returns the current record's "ca_origen" value
 * @method string          getCaCiuorigen()       Returns the current record's "ca_ciuorigen" value
 * @method string          getCaDestino()         Returns the current record's "ca_destino" value
 * @method string          getCaCiudestino()      Returns the current record's "ca_ciudestino" value
 * @method string          getCaModalidad()       Returns the current record's "ca_modalidad" value
 * @method string          getCaImpoexpo()        Returns the current record's "ca_impoexpo" value
 * @method string          getCaTransporte()      Returns the current record's "ca_transporte" value
 * @method string          getCaAplicaidg()       Returns the current record's "ca_aplicaidg" value
 * @method integer         getCaIdregimen()       Returns the current record's "ca_idregimen" value
 * @method string          getCaRegimen()         Returns the current record's "ca_regimen" value
 * @method integer         getCaIdcliente()       Returns the current record's "ca_idcliente" value
 * @method string          getCaCompania()        Returns the current record's "ca_compania" value
 * @method integer         getCaIdagencia()       Returns the current record's "ca_idagencia" value
 * @method string          getCaAgencia()         Returns the current record's "ca_agencia" value
 * @method integer         getCaIdlinea()         Returns the current record's "ca_idlinea" value
 * @method string          getCaLinea()           Returns the current record's "ca_linea" value
 * @method integer         getCaIdagente()        Returns the current record's "ca_idagente" value
 * @method string          getCaAgente()          Returns the current record's "ca_agente" value
 * @method string          getCaVendedor()        Returns the current record's "ca_vendedor" value
 * @method string          getCaCoordinador()     Returns the current record's "ca_coordinador" value
 * @method string          getCaProveedor()       Returns the current record's "ca_proveedor" value
 * @method string          getCaPedido()          Returns the current record's "ca_pedido" value
 * @method date            getCaFchcreado()       Returns the current record's "ca_fchcreado" value
 * @method string          getCaUsucreado()       Returns the current record's "ca_usucreado" value
 * @method date            getCaFchactualizado()  Returns the current record's "ca_fchactualizado" value
 * @method string          getCaUsuactualizado()  Returns the current record's "ca_usuactualizado" value
 * @method date            getCaFchliquidado()    Returns the current record's "ca_fchliquidado" value
 * @method string          getCaUsuliquidado()    Returns the current record's "ca_usuliquidado" value
 * @method date            getCaFchcerrado()      Returns the current record's "ca_fchcerrado" value
 * @method string          getCaUsucerrado()      Returns the current record's "ca_usucerrado" value
 * @method Reporte         getReporte()           Returns the current record's "Reporte" value
 * @method Usuario         getUsuario()           Returns the current record's "Usuario" value
 * @method InoViExpoAduana setCaIdmaster()        Sets the current record's "ca_idmaster" value
 * @method InoViExpoAduana setCaReferencia()      Sets the current record's "ca_referencia" value
 * @method InoViExpoAduana setCaAno()             Sets the current record's "ca_ano" value
 * @method InoViExpoAduana setCaMes()             Sets the current record's "ca_mes" value
 * @method InoViExpoAduana setCaIdreporte()       Sets the current record's "ca_idreporte" value
 * @method InoViExpoAduana setCaConsecutivo()     Sets the current record's "ca_consecutivo" value
 * @method InoViExpoAduana setCaVersion()         Sets the current record's "ca_version" value
 * @method InoViExpoAduana setCaSucursal()        Sets the current record's "ca_sucursal" value
 * @method InoViExpoAduana setCaTraorigen()       Sets the current record's "ca_traorigen" value
 * @method InoViExpoAduana setCaOrigen()          Sets the current record's "ca_origen" value
 * @method InoViExpoAduana setCaCiuorigen()       Sets the current record's "ca_ciuorigen" value
 * @method InoViExpoAduana setCaDestino()         Sets the current record's "ca_destino" value
 * @method InoViExpoAduana setCaCiudestino()      Sets the current record's "ca_ciudestino" value
 * @method InoViExpoAduana setCaModalidad()       Sets the current record's "ca_modalidad" value
 * @method InoViExpoAduana setCaImpoexpo()        Sets the current record's "ca_impoexpo" value
 * @method InoViExpoAduana setCaTransporte()      Sets the current record's "ca_transporte" value
 * @method InoViExpoAduana setCaAplicaidg()       Sets the current record's "ca_aplicaidg" value
 * @method InoViExpoAduana setCaIdregimen()       Sets the current record's "ca_idregimen" value
 * @method InoViExpoAduana setCaRegimen()         Sets the current record's "ca_regimen" value
 * @method InoViExpoAduana setCaIdcliente()       Sets the current record's "ca_idcliente" value
 * @method InoViExpoAduana setCaCompania()        Sets the current record's "ca_compania" value
 * @method InoViExpoAduana setCaIdagencia()       Sets the current record's "ca_idagencia" value
 * @method InoViExpoAduana setCaAgencia()         Sets the current record's "ca_agencia" value
 * @method InoViExpoAduana setCaIdlinea()         Sets the current record's "ca_idlinea" value
 * @method InoViExpoAduana setCaLinea()           Sets the current record's "ca_linea" value
 * @method InoViExpoAduana setCaIdagente()        Sets the current record's "ca_idagente" value
 * @method InoViExpoAduana setCaAgente()          Sets the current record's "ca_agente" value
 * @method InoViExpoAduana setCaVendedor()        Sets the current record's "ca_vendedor" value
 * @method InoViExpoAduana setCaCoordinador()     Sets the current record's "ca_coordinador" value
 * @method InoViExpoAduana setCaProveedor()       Sets the current record's "ca_proveedor" value
 * @method InoViExpoAduana setCaPedido()          Sets the current record's "ca_pedido" value
 * @method InoViExpoAduana setCaFchcreado()       Sets the current record's "ca_fchcreado" value
 * @method InoViExpoAduana setCaUsucreado()       Sets the current record's "ca_usucreado" value
 * @method InoViExpoAduana setCaFchactualizado()  Sets the current record's "ca_fchactualizado" value
 * @method InoViExpoAduana setCaUsuactualizado()  Sets the current record's "ca_usuactualizado" value
 * @method InoViExpoAduana setCaFchliquidado()    Sets the current record's "ca_fchliquidado" value
 * @method InoViExpoAduana setCaUsuliquidado()    Sets the current record's "ca_usuliquidado" value
 * @method InoViExpoAduana setCaFchcerrado()      Sets the current record's "ca_fchcerrado" value
 * @method InoViExpoAduana setCaUsucerrado()      Sets the current record's "ca_usucerrado" value
 * @method InoViExpoAduana setReporte()           Sets the current record's "Reporte" value
 * @method InoViExpoAduana setUsuario()           Sets the current record's "Usuario" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseInoViExpoAduana extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('aduana.vi_ino_expoaduana');
        $this->hasColumn('ca_idmaster', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_referencia', 'string', null, array(
             'type' => 'string',
             'primary' => true,
             ));
        $this->hasColumn('ca_ano', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_mes', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_idreporte', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_consecutivo', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_version', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_sucursal', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_traorigen', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_origen', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_ciuorigen', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_destino', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_ciudestino', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_modalidad', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_impoexpo', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_transporte', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_peso', 'integer,', null, array(
             'type' => 'integer,',
             ));
        $this->hasColumn('ca_piezas', 'integer,', null, array(
             'type' => 'integer,',
             ));
        $this->hasColumn('ca_volumen', 'integer,', null, array(
             'type' => 'integer,',
             ));
        $this->hasColumn('ca_fchllegada', 'date,', null, array(
             'type' => 'date,',
             ));
        $this->hasColumn('ca_fchsalida', 'date,', null, array(
             'type' => 'date,',
             ));
        $this->hasColumn('ca_aplicaidg', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_idregimen', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_regimen', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_idcliente', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_compania', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_idagencia', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_agencia', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_idlinea', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_linea', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_idagente', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_agente', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_vendedor', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_coordinador', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_proveedor', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_pedido', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchcreado', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_usucreado', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchactualizado', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_usuactualizado', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchliquidado', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_usuliquidado', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchcerrado', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_usucerrado', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Reporte', array(
             'local' => 'ca_idreporte',
             'foreign' => 'ca_idreporte'));

        $this->hasOne('Usuario', array(
             'local' => 'ca_usuario',
             'foreign' => 'ca_login'));
    }
}