<?php

/**
 * BaseUsuBrigadas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ca_login
 * @property boolean $ca_donante
 * @property string $ca_enfermedad
 * @property string $ca_alergico
 * @property string $ca_comites
 * @property integer $ca_zona
 * @property string, $ca_propiedades
 * @property integer, $ca_ecivil
 * @property timestamp $ca_fchcreado
 * @property string $ca_usucreado
 * @property timestamp $ca_fchactualizado
 * @property string $ca_usuactualizado
 * @property Usuario $Usuario
 * @property Usuario $Usucreado
 * @property Usuario $Usuactualizado
 * 
 * @method string      getCaLogin()           Returns the current record's "ca_login" value
 * @method boolean     getCaDonante()         Returns the current record's "ca_donante" value
 * @method string      getCaEnfermedad()      Returns the current record's "ca_enfermedad" value
 * @method string      getCaAlergico()        Returns the current record's "ca_alergico" value
 * @method string      getCaComites()         Returns the current record's "ca_comites" value
 * @method integer     getCaZona()            Returns the current record's "ca_zona" value
 * @method timestamp   getCaFchcreado()       Returns the current record's "ca_fchcreado" value
 * @method string      getCaUsucreado()       Returns the current record's "ca_usucreado" value
 * @method timestamp   getCaFchactualizado()  Returns the current record's "ca_fchactualizado" value
 * @method string      getCaUsuactualizado()  Returns the current record's "ca_usuactualizado" value
 * @method Usuario     getUsuario()           Returns the current record's "Usuario" value
 * @method Usuario     getUsucreado()         Returns the current record's "Usucreado" value
 * @method Usuario     getUsuactualizado()    Returns the current record's "Usuactualizado" value
 * @method UsuBrigadas setCaLogin()           Sets the current record's "ca_login" value
 * @method UsuBrigadas setCaDonante()         Sets the current record's "ca_donante" value
 * @method UsuBrigadas setCaEnfermedad()      Sets the current record's "ca_enfermedad" value
 * @method UsuBrigadas setCaAlergico()        Sets the current record's "ca_alergico" value
 * @method UsuBrigadas setCaComites()         Sets the current record's "ca_comites" value
 * @method UsuBrigadas setCaZona()            Sets the current record's "ca_zona" value
 * @method UsuBrigadas setCaFchcreado()       Sets the current record's "ca_fchcreado" value
 * @method UsuBrigadas setCaUsucreado()       Sets the current record's "ca_usucreado" value
 * @method UsuBrigadas setCaFchactualizado()  Sets the current record's "ca_fchactualizado" value
 * @method UsuBrigadas setCaUsuactualizado()  Sets the current record's "ca_usuactualizado" value
 * @method UsuBrigadas setUsuario()           Sets the current record's "Usuario" value
 * @method UsuBrigadas setUsucreado()         Sets the current record's "Usucreado" value
 * @method UsuBrigadas setUsuactualizado()    Sets the current record's "Usuactualizado" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUsuBrigadas extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('control.tb_usu_brigadas');
        $this->hasColumn('ca_login', 'string', null, array(
             'type' => 'string',
             'primary' => true,
             ));
        $this->hasColumn('ca_donante', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('ca_enfermedad', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_alergico', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_comites', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_zona', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_propiedades', 'string,', null, array(
             'type' => 'string,',
             ));
        $this->hasColumn('ca_ecivil', 'integer,', null, array(
             'type' => 'integer,',
             ));
        $this->hasColumn('ca_fchcreado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usucreado', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchactualizado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usuactualizado', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'ca_login',
             'foreign' => 'ca_login'));

        $this->hasOne('Usuario as Usucreado', array(
             'local' => 'ca_usucreado',
             'foreign' => 'ca_login'));

        $this->hasOne('Usuario as Usuactualizado', array(
             'local' => 'ca_usuactualizado',
             'foreign' => 'ca_login'));
    }
}