<?php

/**
 * BaseTransporteAdu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_id
 * @property integer $ca_semana
 * @property string $ca_referencia
 * @property integer $ca_idcliente
 * @property numeric $ca_volumen
 * @property numeric $ca_piezas
 * @property numeric $ca_peso
 * @property string $ca_mercancia
 * @property string $ca_origen
 * @property string $ca_destino
 * @property string $ca_modalidad
 * @property string $ca_observaciones
 * @property timestamp $ca_fchcreado
 * @property string $ca_usucreado
 * @property timestamp $ca_fchactualizado
 * @property string $ca_usuactualizado
 * @property date $ca_fchsalida
 * @property string $ca_doctransporte
 * @property boolean $ca_escolta
 * @property numeric $ca_vlrventa
 * @property numeric $ca_vlrneta
 * @property integer $ca_idtransportista
 * @property Ciudad $Origen
 * @property Ciudad $Destino
 * @property Cliente $Cliente
 * @property IdsProveedor $IdsProveedor
 * 
 * @method integer       getCaId()               Returns the current record's "ca_id" value
 * @method integer       getCaSemana()           Returns the current record's "ca_semana" value
 * @method string        getCaReferencia()       Returns the current record's "ca_referencia" value
 * @method integer       getCaIdcliente()        Returns the current record's "ca_idcliente" value
 * @method numeric       getCaVolumen()          Returns the current record's "ca_volumen" value
 * @method numeric       getCaPiezas()           Returns the current record's "ca_piezas" value
 * @method numeric       getCaPeso()             Returns the current record's "ca_peso" value
 * @method string        getCaMercancia()        Returns the current record's "ca_mercancia" value
 * @method string        getCaOrigen()           Returns the current record's "ca_origen" value
 * @method string        getCaDestino()          Returns the current record's "ca_destino" value
 * @method string        getCaModalidad()        Returns the current record's "ca_modalidad" value
 * @method string        getCaObservaciones()    Returns the current record's "ca_observaciones" value
 * @method timestamp     getCaFchcreado()        Returns the current record's "ca_fchcreado" value
 * @method string        getCaUsucreado()        Returns the current record's "ca_usucreado" value
 * @method timestamp     getCaFchactualizado()   Returns the current record's "ca_fchactualizado" value
 * @method string        getCaUsuactualizado()   Returns the current record's "ca_usuactualizado" value
 * @method date          getCaFchsalida()        Returns the current record's "ca_fchsalida" value
 * @method string        getCaDoctransporte()    Returns the current record's "ca_doctransporte" value
 * @method boolean       getCaEscolta()          Returns the current record's "ca_escolta" value
 * @method numeric       getCaVlrventa()         Returns the current record's "ca_vlrventa" value
 * @method numeric       getCaVlrneta()          Returns the current record's "ca_vlrneta" value
 * @method integer       getCaIdtransportista()  Returns the current record's "ca_idtransportista" value
 * @method Ciudad        getOrigen()             Returns the current record's "Origen" value
 * @method Ciudad        getDestino()            Returns the current record's "Destino" value
 * @method Cliente       getCliente()            Returns the current record's "Cliente" value
 * @method IdsProveedor  getIdsProveedor()       Returns the current record's "IdsProveedor" value
 * @method TransporteAdu setCaId()               Sets the current record's "ca_id" value
 * @method TransporteAdu setCaSemana()           Sets the current record's "ca_semana" value
 * @method TransporteAdu setCaReferencia()       Sets the current record's "ca_referencia" value
 * @method TransporteAdu setCaIdcliente()        Sets the current record's "ca_idcliente" value
 * @method TransporteAdu setCaVolumen()          Sets the current record's "ca_volumen" value
 * @method TransporteAdu setCaPiezas()           Sets the current record's "ca_piezas" value
 * @method TransporteAdu setCaPeso()             Sets the current record's "ca_peso" value
 * @method TransporteAdu setCaMercancia()        Sets the current record's "ca_mercancia" value
 * @method TransporteAdu setCaOrigen()           Sets the current record's "ca_origen" value
 * @method TransporteAdu setCaDestino()          Sets the current record's "ca_destino" value
 * @method TransporteAdu setCaModalidad()        Sets the current record's "ca_modalidad" value
 * @method TransporteAdu setCaObservaciones()    Sets the current record's "ca_observaciones" value
 * @method TransporteAdu setCaFchcreado()        Sets the current record's "ca_fchcreado" value
 * @method TransporteAdu setCaUsucreado()        Sets the current record's "ca_usucreado" value
 * @method TransporteAdu setCaFchactualizado()   Sets the current record's "ca_fchactualizado" value
 * @method TransporteAdu setCaUsuactualizado()   Sets the current record's "ca_usuactualizado" value
 * @method TransporteAdu setCaFchsalida()        Sets the current record's "ca_fchsalida" value
 * @method TransporteAdu setCaDoctransporte()    Sets the current record's "ca_doctransporte" value
 * @method TransporteAdu setCaEscolta()          Sets the current record's "ca_escolta" value
 * @method TransporteAdu setCaVlrventa()         Sets the current record's "ca_vlrventa" value
 * @method TransporteAdu setCaVlrneta()          Sets the current record's "ca_vlrneta" value
 * @method TransporteAdu setCaIdtransportista()  Sets the current record's "ca_idtransportista" value
 * @method TransporteAdu setOrigen()             Sets the current record's "Origen" value
 * @method TransporteAdu setDestino()            Sets the current record's "Destino" value
 * @method TransporteAdu setCliente()            Sets the current record's "Cliente" value
 * @method TransporteAdu setIdsProveedor()       Sets the current record's "IdsProveedor" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTransporteAdu extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_brk_transporte');
        $this->hasColumn('ca_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ca_semana', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_referencia', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_idcliente', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_volumen', 'numeric', null, array(
             'type' => 'numeric',
             ));
        $this->hasColumn('ca_piezas', 'numeric', null, array(
             'type' => 'numeric',
             ));
        $this->hasColumn('ca_peso', 'numeric', null, array(
             'type' => 'numeric',
             ));
        $this->hasColumn('ca_mercancia', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_origen', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_destino', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_modalidad', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_observaciones', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchcreado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usucreado', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchactualizado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usuactualizado', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchsalida', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_doctransporte', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_escolta', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('ca_vlrventa', 'numeric', null, array(
             'type' => 'numeric',
             ));
        $this->hasColumn('ca_vlrneta', 'numeric', null, array(
             'type' => 'numeric',
             ));
        $this->hasColumn('ca_idtransportista', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ciudad as Origen', array(
             'local' => 'ca_origen',
             'foreign' => 'ca_idciudad'));

        $this->hasOne('Ciudad as Destino', array(
             'local' => 'ca_destino',
             'foreign' => 'ca_idciudad'));

        $this->hasOne('Cliente', array(
             'local' => 'ca_idcliente',
             'foreign' => 'ca_idcliente'));

        $this->hasOne('IdsProveedor', array(
             'local' => 'ca_idtransportista',
             'foreign' => 'ca_idproveedor'));
    }
}