<?php

/**
 * BaseRsgoFactor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idriesgo
 * @property string $ca_factor
 * @property Riesgos $Riesgos
 * 
 * @method integer    getCaIdriesgo()  Returns the current record's "ca_idriesgo" value
 * @method string     getCaFactor()    Returns the current record's "ca_factor" value
 * @method Riesgos    getRiesgos()     Returns the current record's "Riesgos" value
 * @method RsgoFactor setCaIdriesgo()  Sets the current record's "ca_idriesgo" value
 * @method RsgoFactor setCaFactor()    Sets the current record's "ca_factor" value
 * @method RsgoFactor setRiesgos()     Sets the current record's "Riesgos" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRsgoFactor extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('riesgos.tb_factores');
        $this->hasColumn('ca_idriesgo', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('ca_factor', 'string', null, array(
             'type' => 'string',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Riesgos', array(
             'local' => 'ca_idriesgo',
             'foreign' => 'ca_idriesgo'));
    }
}