<?php

/**
 * BaseRsgoValoracion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idvaloracion
 * @property integer $ca_idriesgo
 * @property integer $ca_ano
 * @property integer $ca_operativo
 * @property integer $ca_legal
 * @property integer $ca_economico
 * @property integer $ca_comercial
 * @property integer $ca_peso
 * @property string $ca_usucreado
 * @property timestamp $ca_fchcreado
 * @property string $ca_usuactualizado
 * @property timestamp $ca_fchactualizado
 * @property jsonb $ca_datos
 * @property string $ca_idsucursal
 * @property Riesgos $Riesgos
 * @property Usuario $UsuCreado
 * @property Usuario $UsuActualizado
 * @property Sucursal $Sucursal
 * 
 * @method integer        getCaIdvaloracion()    Returns the current record's "ca_idvaloracion" value
 * @method integer        getCaIdriesgo()        Returns the current record's "ca_idriesgo" value
 * @method integer        getCaAno()             Returns the current record's "ca_ano" value
 * @method integer        getCaOperativo()       Returns the current record's "ca_operativo" value
 * @method integer        getCaLegal()           Returns the current record's "ca_legal" value
 * @method integer        getCaEconomico()       Returns the current record's "ca_economico" value
 * @method integer        getCaComercial()       Returns the current record's "ca_comercial" value
 * @method integer        getCaPeso()            Returns the current record's "ca_peso" value
 * @method string         getCaUsucreado()       Returns the current record's "ca_usucreado" value
 * @method timestamp      getCaFchcreado()       Returns the current record's "ca_fchcreado" value
 * @method string         getCaUsuactualizado()  Returns the current record's "ca_usuactualizado" value
 * @method timestamp      getCaFchactualizado()  Returns the current record's "ca_fchactualizado" value
 * @method jsonb          getCaDatos()           Returns the current record's "ca_datos" value
 * @method string         getCaIdsucursal()      Returns the current record's "ca_idsucursal" value
 * @method Riesgos        getRiesgos()           Returns the current record's "Riesgos" value
 * @method Usuario        getUsuCreado()         Returns the current record's "UsuCreado" value
 * @method Usuario        getUsuActualizado()    Returns the current record's "UsuActualizado" value
 * @method Sucursal       getSucursal()          Returns the current record's "Sucursal" value
 * @method RsgoValoracion setCaIdvaloracion()    Sets the current record's "ca_idvaloracion" value
 * @method RsgoValoracion setCaIdriesgo()        Sets the current record's "ca_idriesgo" value
 * @method RsgoValoracion setCaAno()             Sets the current record's "ca_ano" value
 * @method RsgoValoracion setCaOperativo()       Sets the current record's "ca_operativo" value
 * @method RsgoValoracion setCaLegal()           Sets the current record's "ca_legal" value
 * @method RsgoValoracion setCaEconomico()       Sets the current record's "ca_economico" value
 * @method RsgoValoracion setCaComercial()       Sets the current record's "ca_comercial" value
 * @method RsgoValoracion setCaPeso()            Sets the current record's "ca_peso" value
 * @method RsgoValoracion setCaUsucreado()       Sets the current record's "ca_usucreado" value
 * @method RsgoValoracion setCaFchcreado()       Sets the current record's "ca_fchcreado" value
 * @method RsgoValoracion setCaUsuactualizado()  Sets the current record's "ca_usuactualizado" value
 * @method RsgoValoracion setCaFchactualizado()  Sets the current record's "ca_fchactualizado" value
 * @method RsgoValoracion setCaDatos()           Sets the current record's "ca_datos" value
 * @method RsgoValoracion setCaIdsucursal()      Sets the current record's "ca_idsucursal" value
 * @method RsgoValoracion setRiesgos()           Sets the current record's "Riesgos" value
 * @method RsgoValoracion setUsuCreado()         Sets the current record's "UsuCreado" value
 * @method RsgoValoracion setUsuActualizado()    Sets the current record's "UsuActualizado" value
 * @method RsgoValoracion setSucursal()          Sets the current record's "Sucursal" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRsgoValoracion extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('riesgos.tb_valoracion');
        $this->hasColumn('ca_idvaloracion', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ca_idriesgo', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_ano', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_operativo', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_legal', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_economico', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_comercial', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_peso', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_usucreado', 'string', 15, array(
             'type' => 'string',
             'length' => '15',
             ));
        $this->hasColumn('ca_fchcreado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usuactualizado', 'string', 15, array(
             'type' => 'string',
             'length' => '15',
             ));
        $this->hasColumn('ca_fchactualizado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_datos', 'jsonb', null, array(
             'type' => 'jsonb',
             ));
        $this->hasColumn('ca_idsucursal', 'string', 3, array(
             'type' => 'string',
             'length' => '3',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Riesgos', array(
             'local' => 'ca_idriesgo',
             'foreign' => 'ca_idriesgo'));

        $this->hasOne('Usuario as UsuCreado', array(
             'local' => 'ca_usucreado',
             'foreign' => 'ca_login'));

        $this->hasOne('Usuario as UsuActualizado', array(
             'local' => 'ca_usuactualizado',
             'foreign' => 'ca_login'));

        $this->hasOne('Sucursal', array(
             'local' => 'ca_idsucursal',
             'foreign' => 'ca_idsucursal'));
    }
}