<?php

/**
 * BaseExpoDocItems
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_item_number
 * @property integer $ca_iddoctransporte
 * @property string $ca_container_number
 * @property float $ca_number_packages
 * @property string $ca_kind_packages
 * @property float $ca_gross_weight
 * @property string $ca_gross_unit
 * @property float $ca_net_weight
 * @property string $ca_net_unit
 * @property float $ca_measurement_weight
 * @property string $ca_measurement_unit
 * @property string $ca_seals
 * @property string $ca_marks_numbers
 * @property string $ca_description_goods
 * @property boolean $ca_same_goods
 * @property timestamp $ca_fchcreado
 * @property string $ca_usucreado
 * @property timestamp $ca_fchactualizado
 * @property string $ca_usuactualizado
 * @property ExpoDoctransporte $ExpoDoctransporte
 * 
 * @method integer           getCaItemNumber()          Returns the current record's "ca_item_number" value
 * @method integer           getCaIddoctransporte()     Returns the current record's "ca_iddoctransporte" value
 * @method string            getCaContainerNumber()     Returns the current record's "ca_container_number" value
 * @method float             getCaNumberPackages()      Returns the current record's "ca_number_packages" value
 * @method string            getCaKindPackages()        Returns the current record's "ca_kind_packages" value
 * @method float             getCaGrossWeight()         Returns the current record's "ca_gross_weight" value
 * @method string            getCaGrossUnit()           Returns the current record's "ca_gross_unit" value
 * @method float             getCaNetWeight()           Returns the current record's "ca_net_weight" value
 * @method string            getCaNetUnit()             Returns the current record's "ca_net_unit" value
 * @method float             getCaMeasurementWeight()   Returns the current record's "ca_measurement_weight" value
 * @method string            getCaMeasurementUnit()     Returns the current record's "ca_measurement_unit" value
 * @method string            getCaSeals()               Returns the current record's "ca_seals" value
 * @method string            getCaMarksNumbers()        Returns the current record's "ca_marks_numbers" value
 * @method string            getCaDescriptionGoods()    Returns the current record's "ca_description_goods" value
 * @method boolean           getCaSameGoods()           Returns the current record's "ca_same_goods" value
 * @method timestamp         getCaFchcreado()           Returns the current record's "ca_fchcreado" value
 * @method string            getCaUsucreado()           Returns the current record's "ca_usucreado" value
 * @method timestamp         getCaFchactualizado()      Returns the current record's "ca_fchactualizado" value
 * @method string            getCaUsuactualizado()      Returns the current record's "ca_usuactualizado" value
 * @method ExpoDoctransporte getExpoDoctransporte()     Returns the current record's "ExpoDoctransporte" value
 * @method ExpoDocItems      setCaItemNumber()          Sets the current record's "ca_item_number" value
 * @method ExpoDocItems      setCaIddoctransporte()     Sets the current record's "ca_iddoctransporte" value
 * @method ExpoDocItems      setCaContainerNumber()     Sets the current record's "ca_container_number" value
 * @method ExpoDocItems      setCaNumberPackages()      Sets the current record's "ca_number_packages" value
 * @method ExpoDocItems      setCaKindPackages()        Sets the current record's "ca_kind_packages" value
 * @method ExpoDocItems      setCaGrossWeight()         Sets the current record's "ca_gross_weight" value
 * @method ExpoDocItems      setCaGrossUnit()           Sets the current record's "ca_gross_unit" value
 * @method ExpoDocItems      setCaNetWeight()           Sets the current record's "ca_net_weight" value
 * @method ExpoDocItems      setCaNetUnit()             Sets the current record's "ca_net_unit" value
 * @method ExpoDocItems      setCaMeasurementWeight()   Sets the current record's "ca_measurement_weight" value
 * @method ExpoDocItems      setCaMeasurementUnit()     Sets the current record's "ca_measurement_unit" value
 * @method ExpoDocItems      setCaSeals()               Sets the current record's "ca_seals" value
 * @method ExpoDocItems      setCaMarksNumbers()        Sets the current record's "ca_marks_numbers" value
 * @method ExpoDocItems      setCaDescriptionGoods()    Sets the current record's "ca_description_goods" value
 * @method ExpoDocItems      setCaSameGoods()           Sets the current record's "ca_same_goods" value
 * @method ExpoDocItems      setCaFchcreado()           Sets the current record's "ca_fchcreado" value
 * @method ExpoDocItems      setCaUsucreado()           Sets the current record's "ca_usucreado" value
 * @method ExpoDocItems      setCaFchactualizado()      Sets the current record's "ca_fchactualizado" value
 * @method ExpoDocItems      setCaUsuactualizado()      Sets the current record's "ca_usuactualizado" value
 * @method ExpoDocItems      setExpoDoctransporte()     Sets the current record's "ExpoDoctransporte" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseExpoDocItems extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_expo_doc_items');
        $this->hasColumn('ca_item_number', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('ca_iddoctransporte', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_container_number', 'string', 17, array(
             'type' => 'string',
             'length' => '17',
             ));
        $this->hasColumn('ca_number_packages', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('ca_kind_packages', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('ca_gross_weight', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('ca_gross_unit', 'string', 4, array(
             'type' => 'string',
             'length' => '4',
             ));
        $this->hasColumn('ca_net_weight', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('ca_net_unit', 'string', 4, array(
             'type' => 'string',
             'length' => '4',
             ));
        $this->hasColumn('ca_measurement_weight', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('ca_measurement_unit', 'string', 4, array(
             'type' => 'string',
             'length' => '4',
             ));
        $this->hasColumn('ca_seals', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('ca_marks_numbers', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_description_goods', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_same_goods', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('ca_fchcreado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usucreado', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('ca_fchactualizado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usuactualizado', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ExpoDoctransporte', array(
             'local' => 'ca_iddoctransporte',
             'foreign' => 'ca_iddoctransporte'));
    }
}