<?php

/**
 * BaseIdsEstadoSap
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_id
 * @property string $ca_tipo
 * @property integer $ca_idempresa
 * @property boolean $ca_activo
 * @property string $ca_ususap
 * @property timestamp $ca_fchsap
 * @property string $ca_usucreado
 * @property timestamp $ca_fchcreado
 * @property Ids $Ids
 * @property Empresa $Empresa
 * @property Usuario $Usucreado
 * 
 * @method integer      getCaId()         Returns the current record's "ca_id" value
 * @method string       getCaTipo()       Returns the current record's "ca_tipo" value
 * @method integer      getCaIdempresa()  Returns the current record's "ca_idempresa" value
 * @method boolean      getCaActivo()     Returns the current record's "ca_activo" value
 * @method string       getCaUsusap()     Returns the current record's "ca_ususap" value
 * @method timestamp    getCaFchsap()     Returns the current record's "ca_fchsap" value
 * @method string       getCaUsucreado()  Returns the current record's "ca_usucreado" value
 * @method timestamp    getCaFchcreado()  Returns the current record's "ca_fchcreado" value
 * @method Ids          getIds()          Returns the current record's "Ids" value
 * @method Empresa      getEmpresa()      Returns the current record's "Empresa" value
 * @method Usuario      getUsucreado()    Returns the current record's "Usucreado" value
 * @method IdsEstadoSap setCaId()         Sets the current record's "ca_id" value
 * @method IdsEstadoSap setCaTipo()       Sets the current record's "ca_tipo" value
 * @method IdsEstadoSap setCaIdempresa()  Sets the current record's "ca_idempresa" value
 * @method IdsEstadoSap setCaActivo()     Sets the current record's "ca_activo" value
 * @method IdsEstadoSap setCaUsusap()     Sets the current record's "ca_ususap" value
 * @method IdsEstadoSap setCaFchsap()     Sets the current record's "ca_fchsap" value
 * @method IdsEstadoSap setCaUsucreado()  Sets the current record's "ca_usucreado" value
 * @method IdsEstadoSap setCaFchcreado()  Sets the current record's "ca_fchcreado" value
 * @method IdsEstadoSap setIds()          Sets the current record's "Ids" value
 * @method IdsEstadoSap setEmpresa()      Sets the current record's "Empresa" value
 * @method IdsEstadoSap setUsucreado()    Sets the current record's "Usucreado" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseIdsEstadoSap extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ids.tb_estados_sap');
        $this->hasColumn('ca_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('ca_tipo', 'string', null, array(
             'type' => 'string',
             'primary' => true,
             ));
        $this->hasColumn('ca_idempresa', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('ca_activo', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('ca_ususap', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchsap', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usucreado', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchcreado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ids', array(
             'local' => 'ca_id',
             'foreign' => 'ca_id'));

        $this->hasOne('Empresa', array(
             'local' => 'ca_idempresa',
             'foreign' => 'ca_idempresa'));

        $this->hasOne('Usuario as Usucreado', array(
             'local' => 'ca_usucreado',
             'foreign' => 'ca_login'));
    }
}