<?php

/**
 * BaseRepStatusRespuesta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idrepstatusrespuestas
 * @property integer $ca_idstatus
 * @property string $ca_respuesta
 * @property string $ca_email
 * @property string $ca_login
 * @property string $ca_fchcreado
 * @property RepStatus $RepStatus
 * @property Usuario $Usuario
 * 
 * @method integer            getCaIdrepstatusrespuestas()  Returns the current record's "ca_idrepstatusrespuestas" value
 * @method integer            getCaIdstatus()               Returns the current record's "ca_idstatus" value
 * @method string             getCaRespuesta()              Returns the current record's "ca_respuesta" value
 * @method string             getCaEmail()                  Returns the current record's "ca_email" value
 * @method string             getCaLogin()                  Returns the current record's "ca_login" value
 * @method string             getCaFchcreado()              Returns the current record's "ca_fchcreado" value
 * @method RepStatus          getRepStatus()                Returns the current record's "RepStatus" value
 * @method Usuario            getUsuario()                  Returns the current record's "Usuario" value
 * @method RepStatusRespuesta setCaIdrepstatusrespuestas()  Sets the current record's "ca_idrepstatusrespuestas" value
 * @method RepStatusRespuesta setCaIdstatus()               Sets the current record's "ca_idstatus" value
 * @method RepStatusRespuesta setCaRespuesta()              Sets the current record's "ca_respuesta" value
 * @method RepStatusRespuesta setCaEmail()                  Sets the current record's "ca_email" value
 * @method RepStatusRespuesta setCaLogin()                  Sets the current record's "ca_login" value
 * @method RepStatusRespuesta setCaFchcreado()              Sets the current record's "ca_fchcreado" value
 * @method RepStatusRespuesta setRepStatus()                Sets the current record's "RepStatus" value
 * @method RepStatusRespuesta setUsuario()                  Sets the current record's "Usuario" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRepStatusRespuesta extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_repstatusrespuestas');
        $this->hasColumn('ca_idrepstatusrespuestas', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('ca_idstatus', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_respuesta', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_email', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_login', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchcreado', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RepStatus', array(
             'local' => 'ca_idstatus',
             'foreign' => 'ca_idstatus'));

        $this->hasOne('Usuario', array(
             'local' => 'ca_login',
             'foreign' => 'ca_login'));
    }
}