<?php

/**
 * BaseDianServicios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idservicio
 * @property string $ca_identificacion
 * @property string $ca_razonsocial
 * @property string $ca_ciudad
 * @property string $ca_codigo
 * @property string $ca_tipo
 * 
 * @method integer       getCaIdservicio()      Returns the current record's "ca_idservicio" value
 * @method string        getCaIdentificacion()  Returns the current record's "ca_identificacion" value
 * @method string        getCaRazonsocial()     Returns the current record's "ca_razonsocial" value
 * @method string        getCaCiudad()          Returns the current record's "ca_ciudad" value
 * @method string        getCaCodigo()          Returns the current record's "ca_codigo" value
 * @method string        getCaTipo()            Returns the current record's "ca_tipo" value
 * @method DianServicios setCaIdservicio()      Sets the current record's "ca_idservicio" value
 * @method DianServicios setCaIdentificacion()  Sets the current record's "ca_identificacion" value
 * @method DianServicios setCaRazonsocial()     Sets the current record's "ca_razonsocial" value
 * @method DianServicios setCaCiudad()          Sets the current record's "ca_ciudad" value
 * @method DianServicios setCaCodigo()          Sets the current record's "ca_codigo" value
 * @method DianServicios setCaTipo()            Sets the current record's "ca_tipo" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDianServicios extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_dianservicios');
        $this->hasColumn('ca_idservicio', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('ca_identificacion', 'string', 15, array(
             'type' => 'string',
             'primary' => true,
             'length' => '15',
             ));
        $this->hasColumn('ca_razonsocial', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_ciudad', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_codigo', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_tipo', 'string', null, array(
             'type' => 'string',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}