<?php

/**
 * BaseFalaShipmentInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ca_iddoc
 * @property date $ca_begin_window
 * @property date $ca_end_window
 * @property string $ca_commodities
 * @property string $ca_partial
 * @property string $ca_payment_terms
 * @property string $ca_incoterms
 * @property string $ca_container_type
 * @property string $ca_utv
 * @property string $ca_etv
 * @property string $ca_line
 * @property string $ca_contact_line
 * @property string $ca_contact_importer
 * @property numeric $ca_uppo
 * @property string $ca_eb
 * @property string $ca_edd
 * @property string $ca_port
 * @property string $ca_transshipment
 * @property string $ca_transshipment_port
 * @property string $ca_shipping_org
 * @property string $ca_original_org
 * @property string $ca_fwd_copy_org
 * @property string $ca_fcr_org
 * @property string $ca_shipping_dst
 * @property string $ca_original_dst
 * @property string $ca_fwd_copy_dst
 * @property string $ca_fcr_dst
 * @property string $ca_transport_via
 * @property string $ca_invoice_org
 * @property string $ca_packing_list_org
 * @property string $ca_document_org
 * @property string $ca_oc_org
 * @property string $ca_others_docs_org
 * @property string $ca_invoice_cps
 * @property string $ca_packing_list_cps
 * @property string $ca_document_cps
 * @property string $ca_oc_cps
 * @property varchar $ca_others_docs_cps
 * @property varchar $ca_final_port
 * @property varchar $ca_alter_port
 * @property date $ca_limit_date
 * @property FalaHeader $FalaHeader
 * 
 * @method string           getCaIddoc()               Returns the current record's "ca_iddoc" value
 * @method date             getCaBeginWindow()         Returns the current record's "ca_begin_window" value
 * @method date             getCaEndWindow()           Returns the current record's "ca_end_window" value
 * @method string           getCaCommodities()         Returns the current record's "ca_commodities" value
 * @method string           getCaPartial()             Returns the current record's "ca_partial" value
 * @method string           getCaPaymentTerms()        Returns the current record's "ca_payment_terms" value
 * @method string           getCaIncoterms()           Returns the current record's "ca_incoterms" value
 * @method string           getCaContainerType()       Returns the current record's "ca_container_type" value
 * @method string           getCaUtv()                 Returns the current record's "ca_utv" value
 * @method string           getCaEtv()                 Returns the current record's "ca_etv" value
 * @method string           getCaLine()                Returns the current record's "ca_line" value
 * @method string           getCaContactLine()         Returns the current record's "ca_contact_line" value
 * @method string           getCaContactImporter()     Returns the current record's "ca_contact_importer" value
 * @method numeric          getCaUppo()                Returns the current record's "ca_uppo" value
 * @method string           getCaEb()                  Returns the current record's "ca_eb" value
 * @method string           getCaEdd()                 Returns the current record's "ca_edd" value
 * @method string           getCaPort()                Returns the current record's "ca_port" value
 * @method string           getCaTransshipment()       Returns the current record's "ca_transshipment" value
 * @method string           getCaTransshipmentPort()   Returns the current record's "ca_transshipment_port" value
 * @method string           getCaShippingOrg()         Returns the current record's "ca_shipping_org" value
 * @method string           getCaOriginalOrg()         Returns the current record's "ca_original_org" value
 * @method string           getCaFwdCopyOrg()          Returns the current record's "ca_fwd_copy_org" value
 * @method string           getCaFcrOrg()              Returns the current record's "ca_fcr_org" value
 * @method string           getCaShippingDst()         Returns the current record's "ca_shipping_dst" value
 * @method string           getCaOriginalDst()         Returns the current record's "ca_original_dst" value
 * @method string           getCaFwdCopyDst()          Returns the current record's "ca_fwd_copy_dst" value
 * @method string           getCaFcrDst()              Returns the current record's "ca_fcr_dst" value
 * @method string           getCaTransportVia()        Returns the current record's "ca_transport_via" value
 * @method string           getCaInvoiceOrg()          Returns the current record's "ca_invoice_org" value
 * @method string           getCaPackingListOrg()      Returns the current record's "ca_packing_list_org" value
 * @method string           getCaDocumentOrg()         Returns the current record's "ca_document_org" value
 * @method string           getCaOcOrg()               Returns the current record's "ca_oc_org" value
 * @method string           getCaOthersDocsOrg()       Returns the current record's "ca_others_docs_org" value
 * @method string           getCaInvoiceCps()          Returns the current record's "ca_invoice_cps" value
 * @method string           getCaPackingListCps()      Returns the current record's "ca_packing_list_cps" value
 * @method string           getCaDocumentCps()         Returns the current record's "ca_document_cps" value
 * @method string           getCaOcCps()               Returns the current record's "ca_oc_cps" value
 * @method varchar          getCaOthersDocsCps()       Returns the current record's "ca_others_docs_cps" value
 * @method varchar          getCaFinalPort()           Returns the current record's "ca_final_port" value
 * @method varchar          getCaAlterPort()           Returns the current record's "ca_alter_port" value
 * @method date             getCaLimitDate()           Returns the current record's "ca_limit_date" value
 * @method FalaHeader       getFalaHeader()            Returns the current record's "FalaHeader" value
 * @method FalaShipmentInfo setCaIddoc()               Sets the current record's "ca_iddoc" value
 * @method FalaShipmentInfo setCaBeginWindow()         Sets the current record's "ca_begin_window" value
 * @method FalaShipmentInfo setCaEndWindow()           Sets the current record's "ca_end_window" value
 * @method FalaShipmentInfo setCaCommodities()         Sets the current record's "ca_commodities" value
 * @method FalaShipmentInfo setCaPartial()             Sets the current record's "ca_partial" value
 * @method FalaShipmentInfo setCaPaymentTerms()        Sets the current record's "ca_payment_terms" value
 * @method FalaShipmentInfo setCaIncoterms()           Sets the current record's "ca_incoterms" value
 * @method FalaShipmentInfo setCaContainerType()       Sets the current record's "ca_container_type" value
 * @method FalaShipmentInfo setCaUtv()                 Sets the current record's "ca_utv" value
 * @method FalaShipmentInfo setCaEtv()                 Sets the current record's "ca_etv" value
 * @method FalaShipmentInfo setCaLine()                Sets the current record's "ca_line" value
 * @method FalaShipmentInfo setCaContactLine()         Sets the current record's "ca_contact_line" value
 * @method FalaShipmentInfo setCaContactImporter()     Sets the current record's "ca_contact_importer" value
 * @method FalaShipmentInfo setCaUppo()                Sets the current record's "ca_uppo" value
 * @method FalaShipmentInfo setCaEb()                  Sets the current record's "ca_eb" value
 * @method FalaShipmentInfo setCaEdd()                 Sets the current record's "ca_edd" value
 * @method FalaShipmentInfo setCaPort()                Sets the current record's "ca_port" value
 * @method FalaShipmentInfo setCaTransshipment()       Sets the current record's "ca_transshipment" value
 * @method FalaShipmentInfo setCaTransshipmentPort()   Sets the current record's "ca_transshipment_port" value
 * @method FalaShipmentInfo setCaShippingOrg()         Sets the current record's "ca_shipping_org" value
 * @method FalaShipmentInfo setCaOriginalOrg()         Sets the current record's "ca_original_org" value
 * @method FalaShipmentInfo setCaFwdCopyOrg()          Sets the current record's "ca_fwd_copy_org" value
 * @method FalaShipmentInfo setCaFcrOrg()              Sets the current record's "ca_fcr_org" value
 * @method FalaShipmentInfo setCaShippingDst()         Sets the current record's "ca_shipping_dst" value
 * @method FalaShipmentInfo setCaOriginalDst()         Sets the current record's "ca_original_dst" value
 * @method FalaShipmentInfo setCaFwdCopyDst()          Sets the current record's "ca_fwd_copy_dst" value
 * @method FalaShipmentInfo setCaFcrDst()              Sets the current record's "ca_fcr_dst" value
 * @method FalaShipmentInfo setCaTransportVia()        Sets the current record's "ca_transport_via" value
 * @method FalaShipmentInfo setCaInvoiceOrg()          Sets the current record's "ca_invoice_org" value
 * @method FalaShipmentInfo setCaPackingListOrg()      Sets the current record's "ca_packing_list_org" value
 * @method FalaShipmentInfo setCaDocumentOrg()         Sets the current record's "ca_document_org" value
 * @method FalaShipmentInfo setCaOcOrg()               Sets the current record's "ca_oc_org" value
 * @method FalaShipmentInfo setCaOthersDocsOrg()       Sets the current record's "ca_others_docs_org" value
 * @method FalaShipmentInfo setCaInvoiceCps()          Sets the current record's "ca_invoice_cps" value
 * @method FalaShipmentInfo setCaPackingListCps()      Sets the current record's "ca_packing_list_cps" value
 * @method FalaShipmentInfo setCaDocumentCps()         Sets the current record's "ca_document_cps" value
 * @method FalaShipmentInfo setCaOcCps()               Sets the current record's "ca_oc_cps" value
 * @method FalaShipmentInfo setCaOthersDocsCps()       Sets the current record's "ca_others_docs_cps" value
 * @method FalaShipmentInfo setCaFinalPort()           Sets the current record's "ca_final_port" value
 * @method FalaShipmentInfo setCaAlterPort()           Sets the current record's "ca_alter_port" value
 * @method FalaShipmentInfo setCaLimitDate()           Sets the current record's "ca_limit_date" value
 * @method FalaShipmentInfo setFalaHeader()            Sets the current record's "FalaHeader" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseFalaShipmentInfo extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_falashipmentinfo');
        $this->hasColumn('ca_iddoc', 'string', null, array(
             'type' => 'string',
             'primary' => true,
             ));
        $this->hasColumn('ca_begin_window', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_end_window', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_commodities', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_partial', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_payment_terms', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_incoterms', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_container_type', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_utv', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_etv', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_line', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_contact_line', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_contact_importer', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_uppo', 'numeric', null, array(
             'type' => 'numeric',
             ));
        $this->hasColumn('ca_eb', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_edd', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_port', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_transshipment', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_transshipment_port', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_shipping_org', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_original_org', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fwd_copy_org', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fcr_org', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_shipping_dst', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_original_dst', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fwd_copy_dst', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fcr_dst', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_transport_via', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_invoice_org', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_packing_list_org', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_document_org', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_oc_org', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_others_docs_org', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_invoice_cps', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_packing_list_cps', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_document_cps', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_oc_cps', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_others_docs_cps', 'varchar', null, array(
             'type' => 'varchar',
             ));
        $this->hasColumn('ca_final_port', 'varchar', null, array(
             'type' => 'varchar',
             ));
        $this->hasColumn('ca_alter_port', 'varchar', null, array(
             'type' => 'varchar',
             ));
        $this->hasColumn('ca_limit_date', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FalaHeader', array(
             'local' => 'ca_iddoc',
             'foreign' => 'ca_iddoc'));
    }
}