<?php

/**
 * BaseInoMaestraAir
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ca_referencia
 * @property integer $ca_idlinea
 * 
 * @method string        getCaReferencia()  Returns the current record's "ca_referencia" value
 * @method integer       getCaIdlinea()     Returns the current record's "ca_idlinea" value
 * @method InoMaestraAir setCaReferencia()  Sets the current record's "ca_referencia" value
 * @method InoMaestraAir setCaIdlinea()     Sets the current record's "ca_idlinea" value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6508 2009-10-14 06:28:49Z jwage $
 */
abstract class BaseInoMaestraAir extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_inomaestra_air');
        $this->hasColumn('ca_referencia', 'string', 16, array(
             'type' => 'string',
             'primary' => true,
             'autoincrement' => true,
             'length' => '16',
             ));
        $this->hasColumn('ca_idlinea', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}