<?php

/**
 * BaseTrackingUserLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ca_id
 * @property string $ca_email
 * @property timestamp $ca_fchevento
 * @property string $ca_url
 * @property string $ca_evento
 * @property string $ca_ipaddress
 * @property string $ca_useragent
 * @property TrackingUser $TrackingUser
 * 
 * @method string          getCaId()         Returns the current record's "ca_id" value
 * @method string          getCaEmail()      Returns the current record's "ca_email" value
 * @method timestamp       getCaFchevento()  Returns the current record's "ca_fchevento" value
 * @method string          getCaUrl()        Returns the current record's "ca_url" value
 * @method string          getCaEvento()     Returns the current record's "ca_evento" value
 * @method string          getCaIpaddress()  Returns the current record's "ca_ipaddress" value
 * @method string          getCaUseragent()  Returns the current record's "ca_useragent" value
 * @method TrackingUser    getTrackingUser() Returns the current record's "TrackingUser" value
 * @method TrackingUserLog setCaId()         Sets the current record's "ca_id" value
 * @method TrackingUserLog setCaEmail()      Sets the current record's "ca_email" value
 * @method TrackingUserLog setCaFchevento()  Sets the current record's "ca_fchevento" value
 * @method TrackingUserLog setCaUrl()        Sets the current record's "ca_url" value
 * @method TrackingUserLog setCaEvento()     Sets the current record's "ca_evento" value
 * @method TrackingUserLog setCaIpaddress()  Sets the current record's "ca_ipaddress" value
 * @method TrackingUserLog setCaUseragent()  Sets the current record's "ca_useragent" value
 * @method TrackingUserLog setTrackingUser() Sets the current record's "TrackingUser" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTrackingUserLog extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_tracking_users_log');
        $this->hasColumn('ca_id', 'string', null, array(
             'type' => 'string',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ca_email', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchevento', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_url', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_evento', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_ipaddress', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_useragent', 'string', null, array(
             'type' => 'string',
             ));


        $this->setAttribute(Doctrine_Core::ATTR_EXPORT, Doctrine_Core::EXPORT_TABLES);

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TrackingUser', array(
             'local' => 'ca_email',
             'foreign' => 'ca_email'));
    }
}