<?php

/**
 * BaseFestivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $ca_fchfestivo
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class BaseFestivo extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_festivos');
        $this->hasColumn('ca_fchfestivo', 'date', null, array(
             'type' => 'date',
             'primary' => true,
             ));
    }

}