<?php

/**
 * BaseIdsContacto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idcontacto
 * @property integer $ca_idsucursal
 * @property string $ca_nombres
 * @property string $ca_papellido
 * @property string $ca_sapellido
 * @property string $ca_saludo
 * @property string $ca_direccion
 * @property string $ca_telefonos
 * @property string $ca_fax
 * @property string $ca_email
 * @property string $ca_impoexpo
 * @property string $ca_transporte
 * @property string $ca_cargo
 * @property string $ca_departamento
 * @property string $ca_observaciones
 * @property boolean $ca_sugerido
 * @property integer $ca_visibilidad
 * @property boolean $ca_activo
 * @property string $ca_codigoarea
 * @property string $ca_usucreado
 * @property timestamp $ca_fchcreado
 * @property string $ca_usuactualizado
 * @property timestamp $ca_fchactualizado
 * @property timestamp $ca_fcheliminado
 * @property string $ca_usueliminado
 * @property IdsSucursal $IdsSucursal
 * @property Doctrine_Collection $CotContactoAg
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6508 2009-10-14 06:28:49Z jwage $
 */
abstract class BaseIdsContacto extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ids.tb_contactos');
        $this->hasColumn('ca_idcontacto', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ca_idsucursal', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_nombres', 'string', 60, array(
             'type' => 'string',
             'length' => '60',
             ));
        $this->hasColumn('ca_papellido', 'string', 60, array(
             'type' => 'string',
             'length' => '60',
             ));
        $this->hasColumn('ca_sapellido', 'string', 60, array(
             'type' => 'string',
             'length' => '60',
             ));
        $this->hasColumn('ca_saludo', 'string', 15, array(
             'type' => 'string',
             'length' => '15',
             ));
        $this->hasColumn('ca_direccion', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('ca_telefonos', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('ca_fax', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('ca_email', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('ca_impoexpo', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_transporte', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_cargo', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('ca_departamento', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('ca_observaciones', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('ca_sugerido', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('ca_visibilidad', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_activo', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('ca_codigoarea', 'string', 4, array(
             'type' => 'string',
             'length' => '4',
             ));
        $this->hasColumn('ca_usucreado', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('ca_fchcreado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usuactualizado', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('ca_fchactualizado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_fcheliminado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usueliminado', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('IdsSucursal', array(
             'local' => 'ca_idsucursal',
             'foreign' => 'ca_idsucursal'));

        $this->hasMany('CotContactoAg', array(
             'local' => 'ca_idcontacto',
             'foreign' => 'ca_idcontacto'));
    }
}