<?php

/**
 * BaseSiigoDetComprobante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_movcont
 * @property integer $id_uneg_movcont
 * @property string $cod_doccont_movcont
 * @property integer $num_tip_doccont_movcont
 * @property numeric $num_doccont_movcont
 * @property string $cta_movcont
 * @property string $tp_idepcte_movcont
 * @property string $suc_movcont
 * @property integer $ident_pcte_movcont
 * @property string $descrip_movcont
 * @property numeric $valor_movcont
 * @property string $natu_movcont
 * @property integer $vl_base_movcont
 * @property string $id_cc_movcont
 * @property string $id_bodega_movcont
 * @property string $codal_inv_movcont
 * @property numeric $cant_inv_movcont
 * @property string $codalt_dep_movcont
 * @property string $codalt_bod_movcont
 * @property string $codalt_ubi_movcont
 * @property string $codalt_cc_movcont
 * @property string $id_area_movcont
 * @property string $codalt_scc_movcont
 * @property string $tp_idter_movcont
 * @property string $ident_ter_movcont
 * @property string $tip_con_car_movcont
 * @property integer $com_con_car_movcont
 * @property numeric $num_con_car_movcont
 * @property integer $vct_con_car_movcont
 * @property date, $fec_con_movcont
 * @property string $nom_terc_movcont
 * @property integer $concepto_nom_movcont
 * @property numeric $variable_acum_movcont
 * @property integer $nroquin_acum_movcont
 * @property string $tip_mod_movhb_movcont
 * @property string $ref_mas_movhb_movcont
 * @property string $nro_blh_movhb_movcont
 * @property SiigoComprobante $SiigoComprobante
 * 
 * @method integer             getIdMovcont()               Returns the current record's "id_movcont" value
 * @method integer             getIdUnegMovcont()           Returns the current record's "id_uneg_movcont" value
 * @method string              getCodDoccontMovcont()       Returns the current record's "cod_doccont_movcont" value
 * @method integer             getNumTipDoccontMovcont()    Returns the current record's "num_tip_doccont_movcont" value
 * @method numeric             getNumDoccontMovcont()       Returns the current record's "num_doccont_movcont" value
 * @method string              getCtaMovcont()              Returns the current record's "cta_movcont" value
 * @method string              getTpIdepcteMovcont()        Returns the current record's "tp_idepcte_movcont" value
 * @method string              getSucMovcont()              Returns the current record's "suc_movcont" value
 * @method integer             getIdentPcteMovcont()        Returns the current record's "ident_pcte_movcont" value
 * @method string              getDescripMovcont()          Returns the current record's "descrip_movcont" value
 * @method numeric             getValorMovcont()            Returns the current record's "valor_movcont" value
 * @method string              getNatuMovcont()             Returns the current record's "natu_movcont" value
 * @method integer             getVlBaseMovcont()           Returns the current record's "vl_base_movcont" value
 * @method string              getIdCcMovcont()             Returns the current record's "id_cc_movcont" value
 * @method string              getIdBodegaMovcont()         Returns the current record's "id_bodega_movcont" value
 * @method string              getCodalInvMovcont()         Returns the current record's "codal_inv_movcont" value
 * @method numeric             getCantInvMovcont()          Returns the current record's "cant_inv_movcont" value
 * @method string              getCodaltDepMovcont()        Returns the current record's "codalt_dep_movcont" value
 * @method string              getCodaltBodMovcont()        Returns the current record's "codalt_bod_movcont" value
 * @method string              getCodaltUbiMovcont()        Returns the current record's "codalt_ubi_movcont" value
 * @method string              getCodaltCcMovcont()         Returns the current record's "codalt_cc_movcont" value
 * @method string              getIdAreaMovcont()           Returns the current record's "id_area_movcont" value
 * @method string              getCodaltSccMovcont()        Returns the current record's "codalt_scc_movcont" value
 * @method string              getTpIdterMovcont()          Returns the current record's "tp_idter_movcont" value
 * @method string              getIdentTerMovcont()         Returns the current record's "ident_ter_movcont" value
 * @method string              getTipConCarMovcont()        Returns the current record's "tip_con_car_movcont" value
 * @method integer             getComConCarMovcont()        Returns the current record's "com_con_car_movcont" value
 * @method numeric             getNumConCarMovcont()        Returns the current record's "num_con_car_movcont" value
 * @method integer             getVctConCarMovcont()        Returns the current record's "vct_con_car_movcont" value
 * @method string              getNomTercMovcont()          Returns the current record's "nom_terc_movcont" value
 * @method integer             getConceptoNomMovcont()      Returns the current record's "concepto_nom_movcont" value
 * @method numeric             getVariableAcumMovcont()     Returns the current record's "variable_acum_movcont" value
 * @method integer             getNroquinAcumMovcont()      Returns the current record's "nroquin_acum_movcont" value
 * @method string              getTipModMovhbMovcont()      Returns the current record's "tip_mod_movhb_movcont" value
 * @method string              getRefMasMovhbMovcont()      Returns the current record's "ref_mas_movhb_movcont" value
 * @method string              getNroBlhMovhbMovcont()      Returns the current record's "nro_blh_movhb_movcont" value
 * @method SiigoComprobante    getSiigoComprobante()        Returns the current record's "SiigoComprobante" value
 * @method SiigoDetComprobante setIdMovcont()               Sets the current record's "id_movcont" value
 * @method SiigoDetComprobante setIdUnegMovcont()           Sets the current record's "id_uneg_movcont" value
 * @method SiigoDetComprobante setCodDoccontMovcont()       Sets the current record's "cod_doccont_movcont" value
 * @method SiigoDetComprobante setNumTipDoccontMovcont()    Sets the current record's "num_tip_doccont_movcont" value
 * @method SiigoDetComprobante setNumDoccontMovcont()       Sets the current record's "num_doccont_movcont" value
 * @method SiigoDetComprobante setCtaMovcont()              Sets the current record's "cta_movcont" value
 * @method SiigoDetComprobante setTpIdepcteMovcont()        Sets the current record's "tp_idepcte_movcont" value
 * @method SiigoDetComprobante setSucMovcont()              Sets the current record's "suc_movcont" value
 * @method SiigoDetComprobante setIdentPcteMovcont()        Sets the current record's "ident_pcte_movcont" value
 * @method SiigoDetComprobante setDescripMovcont()          Sets the current record's "descrip_movcont" value
 * @method SiigoDetComprobante setValorMovcont()            Sets the current record's "valor_movcont" value
 * @method SiigoDetComprobante setNatuMovcont()             Sets the current record's "natu_movcont" value
 * @method SiigoDetComprobante setVlBaseMovcont()           Sets the current record's "vl_base_movcont" value
 * @method SiigoDetComprobante setIdCcMovcont()             Sets the current record's "id_cc_movcont" value
 * @method SiigoDetComprobante setIdBodegaMovcont()         Sets the current record's "id_bodega_movcont" value
 * @method SiigoDetComprobante setCodalInvMovcont()         Sets the current record's "codal_inv_movcont" value
 * @method SiigoDetComprobante setCantInvMovcont()          Sets the current record's "cant_inv_movcont" value
 * @method SiigoDetComprobante setCodaltDepMovcont()        Sets the current record's "codalt_dep_movcont" value
 * @method SiigoDetComprobante setCodaltBodMovcont()        Sets the current record's "codalt_bod_movcont" value
 * @method SiigoDetComprobante setCodaltUbiMovcont()        Sets the current record's "codalt_ubi_movcont" value
 * @method SiigoDetComprobante setCodaltCcMovcont()         Sets the current record's "codalt_cc_movcont" value
 * @method SiigoDetComprobante setIdAreaMovcont()           Sets the current record's "id_area_movcont" value
 * @method SiigoDetComprobante setCodaltSccMovcont()        Sets the current record's "codalt_scc_movcont" value
 * @method SiigoDetComprobante setTpIdterMovcont()          Sets the current record's "tp_idter_movcont" value
 * @method SiigoDetComprobante setIdentTerMovcont()         Sets the current record's "ident_ter_movcont" value
 * @method SiigoDetComprobante setTipConCarMovcont()        Sets the current record's "tip_con_car_movcont" value
 * @method SiigoDetComprobante setComConCarMovcont()        Sets the current record's "com_con_car_movcont" value
 * @method SiigoDetComprobante setNumConCarMovcont()        Sets the current record's "num_con_car_movcont" value
 * @method SiigoDetComprobante setVctConCarMovcont()        Sets the current record's "vct_con_car_movcont" value
 * @method SiigoDetComprobante setNomTercMovcont()          Sets the current record's "nom_terc_movcont" value
 * @method SiigoDetComprobante setConceptoNomMovcont()      Sets the current record's "concepto_nom_movcont" value
 * @method SiigoDetComprobante setVariableAcumMovcont()     Sets the current record's "variable_acum_movcont" value
 * @method SiigoDetComprobante setNroquinAcumMovcont()      Sets the current record's "nroquin_acum_movcont" value
 * @method SiigoDetComprobante setTipModMovhbMovcont()      Sets the current record's "tip_mod_movhb_movcont" value
 * @method SiigoDetComprobante setRefMasMovhbMovcont()      Sets the current record's "ref_mas_movhb_movcont" value
 * @method SiigoDetComprobante setNroBlhMovhbMovcont()      Sets the current record's "nro_blh_movhb_movcont" value
 * @method SiigoDetComprobante setSiigoComprobante()        Sets the current record's "SiigoComprobante" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseSiigoDetComprobante extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_detcontable');
        $this->hasColumn('id_movcont', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('id_uneg_movcont', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('cod_doccont_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('num_tip_doccont_movcont', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('num_doccont_movcont', 'numeric', null, array(
             'type' => 'numeric',
             ));
        $this->hasColumn('cta_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('tp_idepcte_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('suc_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ident_pcte_movcont', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('descrip_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('valor_movcont', 'numeric', null, array(
             'type' => 'numeric',
             ));
        $this->hasColumn('natu_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('vl_base_movcont', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('id_cc_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('id_bodega_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('codal_inv_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('cant_inv_movcont', 'numeric', null, array(
             'type' => 'numeric',
             ));
        $this->hasColumn('codalt_dep_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('codalt_bod_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('codalt_ubi_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('codalt_cc_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('id_area_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('codalt_scc_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('tp_idter_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ident_ter_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('tip_con_car_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('com_con_car_movcont', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('num_con_car_movcont', 'numeric', null, array(
             'type' => 'numeric',
             ));
        $this->hasColumn('vct_con_car_movcont', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('fec_con_movcont', 'date,', null, array(
             'type' => 'date,',
             ));
        $this->hasColumn('nom_terc_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('concepto_nom_movcont', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('variable_acum_movcont', 'numeric', null, array(
             'type' => 'numeric',
             ));
        $this->hasColumn('nroquin_acum_movcont', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tip_mod_movhb_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ref_mas_movhb_movcont', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('nro_blh_movhb_movcont', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SiigoComprobante', array(
             'local' => 'id_uneg_movcont',
             'foreign' => 'id_uneg_cont'));
    }
}