<?php

/**
 * BaseColsysConfigValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ca_idvalue
 * @property integer $ca_idconfig
 * @property string $ca_ident
 * @property string $ca_value
 * @property string $ca_value2
 * @property ColsysConfig $ColsysConfig
 * @property ResultadoEncuesta $ResultadoEncuesta
 * @property Doctrine_Collection $IdsBanco
 * @property Doctrine_Collection $DocCliente
 * 
 * @method string              getCaIdvalue()         Returns the current record's "ca_idvalue" value
 * @method integer             getCaIdconfig()        Returns the current record's "ca_idconfig" value
 * @method string              getCaIdent()           Returns the current record's "ca_ident" value
 * @method string              getCaValue()           Returns the current record's "ca_value" value
 * @method string              getCaValue2()          Returns the current record's "ca_value2" value
 * @method ColsysConfig        getColsysConfig()      Returns the current record's "ColsysConfig" value
 * @method ResultadoEncuesta   getResultadoEncuesta() Returns the current record's "ResultadoEncuesta" value
 * @method Doctrine_Collection getIdsBanco()          Returns the current record's "IdsBanco" collection
 * @method Doctrine_Collection getDocCliente()        Returns the current record's "DocCliente" collection
 * @method ColsysConfigValue   setCaIdvalue()         Sets the current record's "ca_idvalue" value
 * @method ColsysConfigValue   setCaIdconfig()        Sets the current record's "ca_idconfig" value
 * @method ColsysConfigValue   setCaIdent()           Sets the current record's "ca_ident" value
 * @method ColsysConfigValue   setCaValue()           Sets the current record's "ca_value" value
 * @method ColsysConfigValue   setCaValue2()          Sets the current record's "ca_value2" value
 * @method ColsysConfigValue   setColsysConfig()      Sets the current record's "ColsysConfig" value
 * @method ColsysConfigValue   setResultadoEncuesta() Sets the current record's "ResultadoEncuesta" value
 * @method ColsysConfigValue   setIdsBanco()          Sets the current record's "IdsBanco" collection
 * @method ColsysConfigValue   setDocCliente()        Sets the current record's "DocCliente" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseColsysConfigValue extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('control.tb_config_values');
        $this->hasColumn('ca_idvalue', 'string', null, array(
             'type' => 'string',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ca_idconfig', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_ident', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_value', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_value2', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ColsysConfig', array(
             'local' => 'ca_idconfig',
             'foreign' => 'ca_idconfig'));

        $this->hasOne('ResultadoEncuesta', array(
             'local' => 'ca_ident',
             'foreign' => 'ca_servicio'));

        $this->hasMany('IdsBanco', array(
             'local' => 'ca_idvalue',
             'foreign' => 'ca_codigo_entidad'));

        $this->hasMany('DocCliente', array(
             'local' => 'ca_idvalue',
             'foreign' => 'ca_iddocumento'));
    }
}