<?php

/**
 * BaseConcepto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idconcepto
 * @property string $ca_concepto
 * @property string $ca_unidad
 * @property string $ca_transporte
 * @property string $ca_modalidad
 * @property integer $ca_liminferior
 * @property Doctrine_Collection $PricFlete
 * @property Doctrine_Collection $PricFleteBs
 * @property Doctrine_Collection $PricRecargoxConcepto
 * @property Doctrine_Collection $PricRecargoxConceptoBs
 * @property Doctrine_Collection $PricRecargoxLinea
 * @property Doctrine_Collection $RepEquipo
 * @property Doctrine_Collection $RepTarifa
 * @property Doctrine_Collection $RepGasto
 * @property Doctrine_Collection $CotOpcion
 * @property Doctrine_Collection $CotRecargo
 * @property Doctrine_Collection $CotContinuacion
 * @property Doctrine_Collection $InoEquiposSea
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6365 2009-09-15 18:22:38Z jwage $
 */
abstract class BaseConcepto extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_conceptos');
        $this->hasColumn('ca_idconcepto', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ca_concepto', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_unidad', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_transporte', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_modalidad', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_liminferior', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('PricFlete', array(
             'local' => 'ca_idconcepto',
             'foreign' => 'ca_idconcepto'));

        $this->hasMany('PricFleteBs', array(
             'local' => 'ca_idconcepto',
             'foreign' => 'ca_idconcepto'));

        $this->hasMany('PricRecargoxConcepto', array(
             'local' => 'ca_idconcepto',
             'foreign' => 'ca_idconcepto'));

        $this->hasMany('PricRecargoxConceptoBs', array(
             'local' => 'ca_idconcepto',
             'foreign' => 'ca_idconcepto'));

        $this->hasMany('PricRecargoxLinea', array(
             'local' => 'ca_idconcepto',
             'foreign' => 'ca_idconcepto'));

        $this->hasMany('RepEquipo', array(
             'local' => 'ca_idconcepto',
             'foreign' => 'ca_idconcepto'));

        $this->hasMany('RepTarifa', array(
             'local' => 'ca_idconcepto',
             'foreign' => 'ca_idconcepto'));

        $this->hasMany('RepGasto', array(
             'local' => 'ca_idconcepto',
             'foreign' => 'ca_idconcepto'));

        $this->hasMany('CotOpcion', array(
             'local' => 'ca_idconcepto',
             'foreign' => 'ca_idconcepto'));

        $this->hasMany('CotRecargo', array(
             'local' => 'ca_idconcepto',
             'foreign' => 'ca_idconcepto'));

        $this->hasMany('CotContinuacion', array(
             'local' => 'ca_idconcepto',
             'foreign' => 'ca_idequipo'));

        $this->hasMany('InoEquiposSea', array(
             'local' => 'ca_idconcepto',
             'foreign' => 'ca_idconcepto'));
    }
}