<?php

/**
 * BaseRsgoProcesos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idproceso
 * @property string $ca_nombre
 * @property integer $ca_idempresa
 * @property integer $ca_orden
 * @property string $ca_prefijo
 * @property boolean $ca_activo
 * @property Doctrine_Collection $Riesgos
 * @property Empresa $Empresa
 * @property Doctrine_Collection $Idg
 * @property Doctrine_Collection $RsgoUsuProcesos
 * @property Doctrine_Collection $RsgoVersion
 * @property Doctrine_Collection $RsgoPermisos
 * @property Doctrine_Collection $RsgoViRiesgos
 * @property Doctrine_Collection $RsgoViProcesos
 * 
 * @method integer             getCaIdproceso()     Returns the current record's "ca_idproceso" value
 * @method string              getCaNombre()        Returns the current record's "ca_nombre" value
 * @method integer             getCaIdempresa()     Returns the current record's "ca_idempresa" value
 * @method integer             getCaOrden()         Returns the current record's "ca_orden" value
 * @method string              getCaPrefijo()       Returns the current record's "ca_prefijo" value
 * @method boolean             getCaActivo()        Returns the current record's "ca_activo" value
 * @method Doctrine_Collection getRiesgos()         Returns the current record's "Riesgos" collection
 * @method Empresa             getEmpresa()         Returns the current record's "Empresa" value
 * @method Doctrine_Collection getIdg()             Returns the current record's "Idg" collection
 * @method Doctrine_Collection getRsgoUsuProcesos() Returns the current record's "RsgoUsuProcesos" collection
 * @method Doctrine_Collection getRsgoVersion()     Returns the current record's "RsgoVersion" collection
 * @method Doctrine_Collection getRsgoPermisos()    Returns the current record's "RsgoPermisos" collection
 * @method Doctrine_Collection getRsgoViRiesgos()   Returns the current record's "RsgoViRiesgos" collection
 * @method Doctrine_Collection getRsgoViProcesos()  Returns the current record's "RsgoViProcesos" collection
 * @method RsgoProcesos        setCaIdproceso()     Sets the current record's "ca_idproceso" value
 * @method RsgoProcesos        setCaNombre()        Sets the current record's "ca_nombre" value
 * @method RsgoProcesos        setCaIdempresa()     Sets the current record's "ca_idempresa" value
 * @method RsgoProcesos        setCaOrden()         Sets the current record's "ca_orden" value
 * @method RsgoProcesos        setCaPrefijo()       Sets the current record's "ca_prefijo" value
 * @method RsgoProcesos        setCaActivo()        Sets the current record's "ca_activo" value
 * @method RsgoProcesos        setRiesgos()         Sets the current record's "Riesgos" collection
 * @method RsgoProcesos        setEmpresa()         Sets the current record's "Empresa" value
 * @method RsgoProcesos        setIdg()             Sets the current record's "Idg" collection
 * @method RsgoProcesos        setRsgoUsuProcesos() Sets the current record's "RsgoUsuProcesos" collection
 * @method RsgoProcesos        setRsgoVersion()     Sets the current record's "RsgoVersion" collection
 * @method RsgoProcesos        setRsgoPermisos()    Sets the current record's "RsgoPermisos" collection
 * @method RsgoProcesos        setRsgoViRiesgos()   Sets the current record's "RsgoViRiesgos" collection
 * @method RsgoProcesos        setRsgoViProcesos()  Sets the current record's "RsgoViProcesos" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRsgoProcesos extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('riesgos.tb_procesos');
        $this->hasColumn('ca_idproceso', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ca_nombre', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('ca_idempresa', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_orden', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_prefijo', 'string', 5, array(
             'type' => 'string',
             'length' => '5',
             ));
        $this->hasColumn('ca_activo', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Riesgos', array(
             'local' => 'ca_idproceso',
             'foreign' => 'ca_idproceso'));

        $this->hasOne('Empresa', array(
             'local' => 'ca_idempresa',
             'foreign' => 'ca_idempresa'));

        $this->hasMany('Idg', array(
             'local' => 'ca_idproceso',
             'foreign' => 'ca_idproceso'));

        $this->hasMany('RsgoUsuProcesos', array(
             'local' => 'ca_idproceso',
             'foreign' => 'ca_idproceso'));

        $this->hasMany('RsgoVersion', array(
             'local' => 'ca_idproceso',
             'foreign' => 'ca_idproceso'));

        $this->hasMany('RsgoPermisos', array(
             'local' => 'ca_idproceso',
             'foreign' => 'ca_idproceso'));

        $this->hasMany('RsgoViRiesgos', array(
             'local' => 'ca_idproceso',
             'foreign' => 'ca_idproceso'));

        $this->hasMany('RsgoViProcesos', array(
             'local' => 'ca_idproceso',
             'foreign' => 'ca_idproceso'));
    }
}