<?php

/**
 * BaseRsgoUsuProcesos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idproceso
 * @property string $ca_login
 * @property integer $ca_idperfil
 * @property RsgoProcesos $RsgoProcesos
 * @property Usuario $Usuario
 * @property Parametro $Parametro
 * 
 * @method integer         getCaIdproceso()  Returns the current record's "ca_idproceso" value
 * @method string          getCaLogin()      Returns the current record's "ca_login" value
 * @method integer         getCaIdperfil()   Returns the current record's "ca_idperfil" value
 * @method RsgoProcesos    getRsgoProcesos() Returns the current record's "RsgoProcesos" value
 * @method Usuario         getUsuario()      Returns the current record's "Usuario" value
 * @method Parametro       getParametro()    Returns the current record's "Parametro" value
 * @method RsgoUsuProcesos setCaIdproceso()  Sets the current record's "ca_idproceso" value
 * @method RsgoUsuProcesos setCaLogin()      Sets the current record's "ca_login" value
 * @method RsgoUsuProcesos setCaIdperfil()   Sets the current record's "ca_idperfil" value
 * @method RsgoUsuProcesos setRsgoProcesos() Sets the current record's "RsgoProcesos" value
 * @method RsgoUsuProcesos setUsuario()      Sets the current record's "Usuario" value
 * @method RsgoUsuProcesos setParametro()    Sets the current record's "Parametro" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRsgoUsuProcesos extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('riesgos.tb_usuprocesos');
        $this->hasColumn('ca_idproceso', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('ca_login', 'string', null, array(
             'type' => 'string',
             'primary' => true,
             ));
        $this->hasColumn('ca_idperfil', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RsgoProcesos', array(
             'local' => 'ca_idproceso',
             'foreign' => 'ca_idproceso'));

        $this->hasOne('Usuario', array(
             'local' => 'ca_login',
             'foreign' => 'ca_login'));

        $this->hasOne('Parametro', array(
             'local' => 'ca_idperfil',
             'foreign' => 'ca_identificacion'));
    }
}