<?php

/**
 * BaseKBCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idcategory
 * @property integer $ca_parent
 * @property string $ca_name
 * @property integer $ca_order
 * @property string $ca_icon
 * @property boolean $ca_main
 * @property Doctrine_Collection $SubCategory
 * @property Doctrine_Collection $KBIssue
 * @property Doctrine_Collection $KBTooltip
 * @property KBCategory $KBCategory
 * 
 * @method integer             getCaIdcategory()  Returns the current record's "ca_idcategory" value
 * @method integer             getCaParent()      Returns the current record's "ca_parent" value
 * @method string              getCaName()        Returns the current record's "ca_name" value
 * @method integer             getCaOrder()       Returns the current record's "ca_order" value
 * @method string              getCaIcon()        Returns the current record's "ca_icon" value
 * @method boolean             getCaMain()        Returns the current record's "ca_main" value
 * @method Doctrine_Collection getSubCategory()   Returns the current record's "SubCategory" collection
 * @method Doctrine_Collection getKBIssue()       Returns the current record's "KBIssue" collection
 * @method Doctrine_Collection getKBTooltip()     Returns the current record's "KBTooltip" collection
 * @method KBCategory          getKBCategory()    Returns the current record's "KBCategory" value
 * @method KBCategory          setCaIdcategory()  Sets the current record's "ca_idcategory" value
 * @method KBCategory          setCaParent()      Sets the current record's "ca_parent" value
 * @method KBCategory          setCaName()        Sets the current record's "ca_name" value
 * @method KBCategory          setCaOrder()       Sets the current record's "ca_order" value
 * @method KBCategory          setCaIcon()        Sets the current record's "ca_icon" value
 * @method KBCategory          setCaMain()        Sets the current record's "ca_main" value
 * @method KBCategory          setSubCategory()   Sets the current record's "SubCategory" collection
 * @method KBCategory          setKBIssue()       Sets the current record's "KBIssue" collection
 * @method KBCategory          setKBTooltip()     Sets the current record's "KBTooltip" collection
 * @method KBCategory          setKBCategory()    Sets the current record's "KBCategory" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseKBCategory extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('helpdesk.tb_kbcategories');
        $this->hasColumn('ca_idcategory', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ca_parent', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_order', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_icon', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_main', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('KBCategory as SubCategory', array(
             'local' => 'ca_idcategory',
             'foreign' => 'ca_parent',
             'orderBy' => 'ca_order ASC'));

        $this->hasMany('KBIssue', array(
             'local' => 'ca_idcategory',
             'foreign' => 'ca_idcategory'));

        $this->hasMany('KBTooltip', array(
             'local' => 'ca_idcategory',
             'foreign' => 'ca_idcategory'));

        $this->hasOne('KBCategory', array(
             'local' => 'ca_parent',
             'foreign' => 'ca_idcategory'));
    }
}