<?php

/**
 * BaseAduFalaDetControlAereo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_id_fal_det_control_aereo
 * @property integer $ca_id_fal_cab_control
 * @property date $ca_fcheta
 * @property date $ca_fchingresodep
 * @property string $ca_referencia
 * @property boolean $ca_preinspeccion
 * @property boolean $ca_inspeccion
 * @property string $ca_paisorigen
 * @property date $ca_fchconsolidado
 * @property integer $ca_consolidado
 * @property string $ca_doctransporte
 * @property date $ca_fchdoctransporte
 * @property string $ca_proveedor
 * @property string $ca_carpeta
 * @property integer $ca_lognet
 * @property integer $ca_tipocarga
 * @property numeric $ca_valor
 * @property string $ca_factura
 * @property date $ca_fchfactura
 * @property date $ca_fchlistempaque
 * @property string $ca_certfletes
 * @property date $ca_fchcertfletes
 * @property date $ca_fchpago
 * @property date $ca_fchconsinv
 * @property date $ca_fchrecepcion
 * @property date $ca_fchdescripciones
 * @property date $ca_fchlevante
 * @property date $ca_fchentregatrans
 * @property string $ca_atiempo
 * @property timestamp $ca_fchcreado
 * @property string $ca_usucreado
 * @property timestamp $ca_fchactualizado
 * @property string $ca_usuactualizado
 * @property string $ca_datos
 * @property Usuario $Usucreado
 * @property AduIndCabControl $AduIndCabControl
 * @property InoMaestraAdu $InoMaestraAdu
 * 
 * @method integer                getCaIdFalDetControlAereo()      Returns the current record's "ca_id_fal_det_control_aereo" value
 * @method integer                getCaIdFalCabControl()           Returns the current record's "ca_id_fal_cab_control" value
 * @method date                   getCaFcheta()                    Returns the current record's "ca_fcheta" value
 * @method date                   getCaFchingresodep()             Returns the current record's "ca_fchingresodep" value
 * @method string                 getCaReferencia()                Returns the current record's "ca_referencia" value
 * @method boolean                getCaPreinspeccion()             Returns the current record's "ca_preinspeccion" value
 * @method boolean                getCaInspeccion()                Returns the current record's "ca_inspeccion" value
 * @method string                 getCaPaisorigen()                Returns the current record's "ca_paisorigen" value
 * @method date                   getCaFchconsolidado()            Returns the current record's "ca_fchconsolidado" value
 * @method integer                getCaConsolidado()               Returns the current record's "ca_consolidado" value
 * @method string                 getCaDoctransporte()             Returns the current record's "ca_doctransporte" value
 * @method date                   getCaFchdoctransporte()          Returns the current record's "ca_fchdoctransporte" value
 * @method string                 getCaProveedor()                 Returns the current record's "ca_proveedor" value
 * @method string                 getCaCarpeta()                   Returns the current record's "ca_carpeta" value
 * @method integer                getCaLognet()                    Returns the current record's "ca_lognet" value
 * @method integer                getCaTipocarga()                 Returns the current record's "ca_tipocarga" value
 * @method numeric                getCaValor()                     Returns the current record's "ca_valor" value
 * @method string                 getCaFactura()                   Returns the current record's "ca_factura" value
 * @method date                   getCaFchfactura()                Returns the current record's "ca_fchfactura" value
 * @method date                   getCaFchlistempaque()            Returns the current record's "ca_fchlistempaque" value
 * @method string                 getCaCertfletes()                Returns the current record's "ca_certfletes" value
 * @method date                   getCaFchcertfletes()             Returns the current record's "ca_fchcertfletes" value
 * @method date                   getCaFchpago()                   Returns the current record's "ca_fchpago" value
 * @method date                   getCaFchconsinv()                Returns the current record's "ca_fchconsinv" value
 * @method date                   getCaFchrecepcion()              Returns the current record's "ca_fchrecepcion" value
 * @method date                   getCaFchdescripciones()          Returns the current record's "ca_fchdescripciones" value
 * @method date                   getCaFchlevante()                Returns the current record's "ca_fchlevante" value
 * @method date                   getCaFchentregatrans()           Returns the current record's "ca_fchentregatrans" value
 * @method string                 getCaAtiempo()                   Returns the current record's "ca_atiempo" value
 * @method timestamp              getCaFchcreado()                 Returns the current record's "ca_fchcreado" value
 * @method string                 getCaUsucreado()                 Returns the current record's "ca_usucreado" value
 * @method timestamp              getCaFchactualizado()            Returns the current record's "ca_fchactualizado" value
 * @method string                 getCaUsuactualizado()            Returns the current record's "ca_usuactualizado" value
 * @method string                 getCaDatos()                     Returns the current record's "ca_datos" value
 * @method Usuario                getUsucreado()                   Returns the current record's "Usucreado" value
 * @method AduIndCabControl       getAduIndCabControl()            Returns the current record's "AduIndCabControl" value
 * @method InoMaestraAdu          getInoMaestraAdu()               Returns the current record's "InoMaestraAdu" value
 * @method AduFalaDetControlAereo setCaIdFalDetControlAereo()      Sets the current record's "ca_id_fal_det_control_aereo" value
 * @method AduFalaDetControlAereo setCaIdFalCabControl()           Sets the current record's "ca_id_fal_cab_control" value
 * @method AduFalaDetControlAereo setCaFcheta()                    Sets the current record's "ca_fcheta" value
 * @method AduFalaDetControlAereo setCaFchingresodep()             Sets the current record's "ca_fchingresodep" value
 * @method AduFalaDetControlAereo setCaReferencia()                Sets the current record's "ca_referencia" value
 * @method AduFalaDetControlAereo setCaPreinspeccion()             Sets the current record's "ca_preinspeccion" value
 * @method AduFalaDetControlAereo setCaInspeccion()                Sets the current record's "ca_inspeccion" value
 * @method AduFalaDetControlAereo setCaPaisorigen()                Sets the current record's "ca_paisorigen" value
 * @method AduFalaDetControlAereo setCaFchconsolidado()            Sets the current record's "ca_fchconsolidado" value
 * @method AduFalaDetControlAereo setCaConsolidado()               Sets the current record's "ca_consolidado" value
 * @method AduFalaDetControlAereo setCaDoctransporte()             Sets the current record's "ca_doctransporte" value
 * @method AduFalaDetControlAereo setCaFchdoctransporte()          Sets the current record's "ca_fchdoctransporte" value
 * @method AduFalaDetControlAereo setCaProveedor()                 Sets the current record's "ca_proveedor" value
 * @method AduFalaDetControlAereo setCaCarpeta()                   Sets the current record's "ca_carpeta" value
 * @method AduFalaDetControlAereo setCaLognet()                    Sets the current record's "ca_lognet" value
 * @method AduFalaDetControlAereo setCaTipocarga()                 Sets the current record's "ca_tipocarga" value
 * @method AduFalaDetControlAereo setCaValor()                     Sets the current record's "ca_valor" value
 * @method AduFalaDetControlAereo setCaFactura()                   Sets the current record's "ca_factura" value
 * @method AduFalaDetControlAereo setCaFchfactura()                Sets the current record's "ca_fchfactura" value
 * @method AduFalaDetControlAereo setCaFchlistempaque()            Sets the current record's "ca_fchlistempaque" value
 * @method AduFalaDetControlAereo setCaCertfletes()                Sets the current record's "ca_certfletes" value
 * @method AduFalaDetControlAereo setCaFchcertfletes()             Sets the current record's "ca_fchcertfletes" value
 * @method AduFalaDetControlAereo setCaFchpago()                   Sets the current record's "ca_fchpago" value
 * @method AduFalaDetControlAereo setCaFchconsinv()                Sets the current record's "ca_fchconsinv" value
 * @method AduFalaDetControlAereo setCaFchrecepcion()              Sets the current record's "ca_fchrecepcion" value
 * @method AduFalaDetControlAereo setCaFchdescripciones()          Sets the current record's "ca_fchdescripciones" value
 * @method AduFalaDetControlAereo setCaFchlevante()                Sets the current record's "ca_fchlevante" value
 * @method AduFalaDetControlAereo setCaFchentregatrans()           Sets the current record's "ca_fchentregatrans" value
 * @method AduFalaDetControlAereo setCaAtiempo()                   Sets the current record's "ca_atiempo" value
 * @method AduFalaDetControlAereo setCaFchcreado()                 Sets the current record's "ca_fchcreado" value
 * @method AduFalaDetControlAereo setCaUsucreado()                 Sets the current record's "ca_usucreado" value
 * @method AduFalaDetControlAereo setCaFchactualizado()            Sets the current record's "ca_fchactualizado" value
 * @method AduFalaDetControlAereo setCaUsuactualizado()            Sets the current record's "ca_usuactualizado" value
 * @method AduFalaDetControlAereo setCaDatos()                     Sets the current record's "ca_datos" value
 * @method AduFalaDetControlAereo setUsucreado()                   Sets the current record's "Usucreado" value
 * @method AduFalaDetControlAereo setAduIndCabControl()            Sets the current record's "AduIndCabControl" value
 * @method AduFalaDetControlAereo setInoMaestraAdu()               Sets the current record's "InoMaestraAdu" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAduFalaDetControlAereo extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('aduana.tb_fal_det_control_aereo');
        $this->hasColumn('ca_id_fal_det_control_aereo', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ca_id_fal_cab_control', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_fcheta', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_fchingresodep', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_referencia', 'string', 17, array(
             'type' => 'string',
             'length' => '17',
             ));
        $this->hasColumn('ca_preinspeccion', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('ca_inspeccion', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('ca_paisorigen', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('ca_fchconsolidado', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_consolidado', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_doctransporte', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('ca_fchdoctransporte', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_proveedor', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_carpeta', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_lognet', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_tipocarga', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_valor', 'numeric', null, array(
             'type' => 'numeric',
             ));
        $this->hasColumn('ca_factura', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchfactura', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_fchlistempaque', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_certfletes', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchcertfletes', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_fchpago', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_fchconsinv', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_fchrecepcion', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_fchdescripciones', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_fchlevante', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_fchentregatrans', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_atiempo', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchcreado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usucreado', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchactualizado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usuactualizado', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_datos', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario as Usucreado', array(
             'local' => 'ca_usucreado',
             'foreign' => 'ca_login'));

        $this->hasOne('AduIndCabControl', array(
             'local' => 'ca_id_fal_cab_control',
             'foreign' => 'ca_id_fal_cab_control'));

        $this->hasOne('InoMaestraAdu', array(
             'local' => 'ca_referencia',
             'foreign' => 'ca_referencia'));
    }
}