<?php

/**
 * BaseIdsCriterio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idcriterio
 * @property string $ca_tipo
 * @property string $ca_criterio
 * @property integer $ca_ponderacion
 * @property string $ca_tipocriterio
 * @property boolean $ca_activo
 * @property string $ca_impoexpo
 * @property string $ca_transporte
 * @property string $ca_usucreado
 * @property timestamp $ca_fchcreado
 * @property string $ca_usuactualizado
 * @property timestamp $ca_fchactualizado
 * @property Doctrine_Collection $IdsEvaluacionxCriterio
 * @property Doctrine_Collection $IdsEvento
 * @property IdsTipo $IdsTipo
 * 
 * @method integer             getCaIdcriterio()           Returns the current record's "ca_idcriterio" value
 * @method string              getCaTipo()                 Returns the current record's "ca_tipo" value
 * @method string              getCaCriterio()             Returns the current record's "ca_criterio" value
 * @method integer             getCaPonderacion()          Returns the current record's "ca_ponderacion" value
 * @method string              getCaTipocriterio()         Returns the current record's "ca_tipocriterio" value
 * @method boolean             getCaActivo()               Returns the current record's "ca_activo" value
 * @method string              getCaImpoexpo()             Returns the current record's "ca_impoexpo" value
 * @method string              getCaTransporte()           Returns the current record's "ca_transporte" value
 * @method string              getCaUsucreado()            Returns the current record's "ca_usucreado" value
 * @method timestamp           getCaFchcreado()            Returns the current record's "ca_fchcreado" value
 * @method string              getCaUsuactualizado()       Returns the current record's "ca_usuactualizado" value
 * @method timestamp           getCaFchactualizado()       Returns the current record's "ca_fchactualizado" value
 * @method Doctrine_Collection getIdsEvaluacionxCriterio() Returns the current record's "IdsEvaluacionxCriterio" collection
 * @method Doctrine_Collection getIdsEvento()              Returns the current record's "IdsEvento" collection
 * @method IdsTipo             getIdsTipo()                Returns the current record's "IdsTipo" value
 * @method IdsCriterio         setCaIdcriterio()           Sets the current record's "ca_idcriterio" value
 * @method IdsCriterio         setCaTipo()                 Sets the current record's "ca_tipo" value
 * @method IdsCriterio         setCaCriterio()             Sets the current record's "ca_criterio" value
 * @method IdsCriterio         setCaPonderacion()          Sets the current record's "ca_ponderacion" value
 * @method IdsCriterio         setCaTipocriterio()         Sets the current record's "ca_tipocriterio" value
 * @method IdsCriterio         setCaActivo()               Sets the current record's "ca_activo" value
 * @method IdsCriterio         setCaImpoexpo()             Sets the current record's "ca_impoexpo" value
 * @method IdsCriterio         setCaTransporte()           Sets the current record's "ca_transporte" value
 * @method IdsCriterio         setCaUsucreado()            Sets the current record's "ca_usucreado" value
 * @method IdsCriterio         setCaFchcreado()            Sets the current record's "ca_fchcreado" value
 * @method IdsCriterio         setCaUsuactualizado()       Sets the current record's "ca_usuactualizado" value
 * @method IdsCriterio         setCaFchactualizado()       Sets the current record's "ca_fchactualizado" value
 * @method IdsCriterio         setIdsEvaluacionxCriterio() Sets the current record's "IdsEvaluacionxCriterio" collection
 * @method IdsCriterio         setIdsEvento()              Sets the current record's "IdsEvento" collection
 * @method IdsCriterio         setIdsTipo()                Sets the current record's "IdsTipo" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseIdsCriterio extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ids.tb_criterios');
        $this->hasColumn('ca_idcriterio', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ca_tipo', 'string', 3, array(
             'type' => 'string',
             'length' => '3',
             ));
        $this->hasColumn('ca_criterio', 'string', 60, array(
             'type' => 'string',
             'length' => '60',
             ));
        $this->hasColumn('ca_ponderacion', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('ca_tipocriterio', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('ca_activo', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('ca_impoexpo', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_transporte', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_usucreado', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('ca_fchcreado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usuactualizado', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('ca_fchactualizado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('IdsEvaluacionxCriterio', array(
             'local' => 'ca_idcriterio',
             'foreign' => 'ca_idcriterio'));

        $this->hasMany('IdsEvento', array(
             'local' => 'ca_idcriterio',
             'foreign' => 'ca_idcriterio'));

        $this->hasOne('IdsTipo', array(
             'local' => 'ca_tipo',
             'foreign' => 'ca_tipo'));
    }
}