<?php

/**
 * BaseIdgEventoCausa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idevento
 * @property integer $ca_idcausa
 * @property IdgEventos $IdgEventos
 * @property Doctrine_Collection $IdgCausas
 * 
 * @method integer             getCaIdevento()  Returns the current record's "ca_idevento" value
 * @method integer             getCaIdcausa()   Returns the current record's "ca_idcausa" value
 * @method IdgEventos          getIdgEventos()  Returns the current record's "IdgEventos" value
 * @method Doctrine_Collection getIdgCausas()   Returns the current record's "IdgCausas" collection
 * @method IdgEventoCausa      setCaIdevento()  Sets the current record's "ca_idevento" value
 * @method IdgEventoCausa      setCaIdcausa()   Sets the current record's "ca_idcausa" value
 * @method IdgEventoCausa      setIdgEventos()  Sets the current record's "IdgEventos" value
 * @method IdgEventoCausa      setIdgCausas()   Sets the current record's "IdgCausas" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseIdgEventoCausa extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('idg.tb_eventos_causas');
        $this->hasColumn('ca_idevento', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('ca_idcausa', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('IdgEventos', array(
             'local' => 'ca_idevento',
             'foreign' => 'ca_idevento'));

        $this->hasMany('IdgCausas', array(
             'local' => 'ca_idcausa',
             'foreign' => 'ca_idcausa'));
    }
}