<?php

/**
 * BaseViClientesSeguimientos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idevento
 * @property integer $ca_idcliente
 * @property timestamp $ca_fchevento
 * @property string $ca_tipo
 * @property string $ca_asunto
 * @property string $ca_detalle
 * @property string $ca_compromisos
 * @property timestamp $ca_fchcompromiso
 * @property integer $ca_idantecedente
 * @property string $ca_usuario
 * @property text $ca_datos
 * @property string $ca_vendedor
 * @property string $ca_coltrans_std
 * @property string $ca_colmas_std
 * @property string $ca_colotm_std
 * @property string $ca_coldepositos_std
 * @property IdsCliente $IdsCliente
 * @property Usuario $Usuario
 * 
 * @method integer                getCaIdevento()          Returns the current record's "ca_idevento" value
 * @method integer                getCaIdcliente()         Returns the current record's "ca_idcliente" value
 * @method timestamp              getCaFchevento()         Returns the current record's "ca_fchevento" value
 * @method string                 getCaTipo()              Returns the current record's "ca_tipo" value
 * @method string                 getCaAsunto()            Returns the current record's "ca_asunto" value
 * @method string                 getCaDetalle()           Returns the current record's "ca_detalle" value
 * @method string                 getCaCompromisos()       Returns the current record's "ca_compromisos" value
 * @method timestamp              getCaFchcompromiso()     Returns the current record's "ca_fchcompromiso" value
 * @method integer                getCaIdantecedente()     Returns the current record's "ca_idantecedente" value
 * @method string                 getCaUsuario()           Returns the current record's "ca_usuario" value
 * @method text                   getCaDatos()             Returns the current record's "ca_datos" value
 * @method string                 getCaVendedor()          Returns the current record's "ca_vendedor" value
 * @method string                 getCaColtransStd()       Returns the current record's "ca_coltrans_std" value
 * @method string                 getCaColmasStd()         Returns the current record's "ca_colmas_std" value
 * @method string                 getCaColotmStd()         Returns the current record's "ca_colotm_std" value
 * @method string                 getCaColdepositosStd()   Returns the current record's "ca_coldepositos_std" value
 * @method IdsCliente             getIdsCliente()          Returns the current record's "IdsCliente" value
 * @method Usuario                getUsuario()             Returns the current record's "Usuario" value
 * @method ViClientesSeguimientos setCaIdevento()          Sets the current record's "ca_idevento" value
 * @method ViClientesSeguimientos setCaIdcliente()         Sets the current record's "ca_idcliente" value
 * @method ViClientesSeguimientos setCaFchevento()         Sets the current record's "ca_fchevento" value
 * @method ViClientesSeguimientos setCaTipo()              Sets the current record's "ca_tipo" value
 * @method ViClientesSeguimientos setCaAsunto()            Sets the current record's "ca_asunto" value
 * @method ViClientesSeguimientos setCaDetalle()           Sets the current record's "ca_detalle" value
 * @method ViClientesSeguimientos setCaCompromisos()       Sets the current record's "ca_compromisos" value
 * @method ViClientesSeguimientos setCaFchcompromiso()     Sets the current record's "ca_fchcompromiso" value
 * @method ViClientesSeguimientos setCaIdantecedente()     Sets the current record's "ca_idantecedente" value
 * @method ViClientesSeguimientos setCaUsuario()           Sets the current record's "ca_usuario" value
 * @method ViClientesSeguimientos setCaDatos()             Sets the current record's "ca_datos" value
 * @method ViClientesSeguimientos setCaVendedor()          Sets the current record's "ca_vendedor" value
 * @method ViClientesSeguimientos setCaColtransStd()       Sets the current record's "ca_coltrans_std" value
 * @method ViClientesSeguimientos setCaColmasStd()         Sets the current record's "ca_colmas_std" value
 * @method ViClientesSeguimientos setCaColotmStd()         Sets the current record's "ca_colotm_std" value
 * @method ViClientesSeguimientos setCaColdepositosStd()   Sets the current record's "ca_coldepositos_std" value
 * @method ViClientesSeguimientos setIdsCliente()          Sets the current record's "IdsCliente" value
 * @method ViClientesSeguimientos setUsuario()             Sets the current record's "Usuario" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseViClientesSeguimientos extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vi_clientes_seguimientos');
        $this->hasColumn('ca_idevento', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ca_idcliente', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_fchevento', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_tipo', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_asunto', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_detalle', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_compromisos', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchcompromiso', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_idantecedente', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_usuario', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_datos', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('ca_vendedor', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_coltrans_std', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_colmas_std', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_colotm_std', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_coldepositos_std', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('IdsCliente', array(
             'local' => 'ca_idcliente',
             'foreign' => 'ca_idcliente'));

        $this->hasOne('Usuario', array(
             'local' => 'ca_usuario',
             'foreign' => 'ca_login'));
    }
}