<?php

/**
 * BaseFalaDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ca_iddoc
 * @property string $ca_sku
 * @property string $ca_vpn
 * @property string $ca_num_cont_part1
 * @property string $ca_num_cont_part2
 * @property string $ca_num_cont_sell
 * @property string $ca_container_iso
 * @property integer $ca_cantidad_pedido
 * @property integer $ca_cantidad_miles
 * @property string $ca_unidad_medidad_cantidad
 * @property string $ca_descripcion_item
 * @property decimal $ca_cantidad_paquetes_miles
 * @property string $ca_unidad_medida_paquetes
 * @property decimal $ca_cantidad_volumen_miles
 * @property string $ca_unidad_medida_volumen
 * @property decimal $ca_cantidad_peso_miles
 * @property string $ca_unidad_medida_peso
 * @property FalaHeader $FalaHeader
 * 
 * @method string     getCaIddoc()                    Returns the current record's "ca_iddoc" value
 * @method string     getCaSku()                      Returns the current record's "ca_sku" value
 * @method string     getCaVpn()                      Returns the current record's "ca_vpn" value
 * @method string     getCaNumContPart1()             Returns the current record's "ca_num_cont_part1" value
 * @method string     getCaNumContPart2()             Returns the current record's "ca_num_cont_part2" value
 * @method string     getCaNumContSell()              Returns the current record's "ca_num_cont_sell" value
 * @method string     getCaContainerIso()             Returns the current record's "ca_container_iso" value
 * @method integer    getCaCantidadPedido()           Returns the current record's "ca_cantidad_pedido" value
 * @method integer    getCaCantidadMiles()            Returns the current record's "ca_cantidad_miles" value
 * @method string     getCaUnidadMedidadCantidad()    Returns the current record's "ca_unidad_medidad_cantidad" value
 * @method string     getCaDescripcionItem()          Returns the current record's "ca_descripcion_item" value
 * @method decimal    getCaCantidadPaquetesMiles()    Returns the current record's "ca_cantidad_paquetes_miles" value
 * @method string     getCaUnidadMedidaPaquetes()     Returns the current record's "ca_unidad_medida_paquetes" value
 * @method decimal    getCaCantidadVolumenMiles()     Returns the current record's "ca_cantidad_volumen_miles" value
 * @method string     getCaUnidadMedidaVolumen()      Returns the current record's "ca_unidad_medida_volumen" value
 * @method decimal    getCaCantidadPesoMiles()        Returns the current record's "ca_cantidad_peso_miles" value
 * @method string     getCaUnidadMedidaPeso()         Returns the current record's "ca_unidad_medida_peso" value
 * @method FalaHeader getFalaHeader()                 Returns the current record's "FalaHeader" value
 * @method FalaDetail setCaIddoc()                    Sets the current record's "ca_iddoc" value
 * @method FalaDetail setCaSku()                      Sets the current record's "ca_sku" value
 * @method FalaDetail setCaVpn()                      Sets the current record's "ca_vpn" value
 * @method FalaDetail setCaNumContPart1()             Sets the current record's "ca_num_cont_part1" value
 * @method FalaDetail setCaNumContPart2()             Sets the current record's "ca_num_cont_part2" value
 * @method FalaDetail setCaNumContSell()              Sets the current record's "ca_num_cont_sell" value
 * @method FalaDetail setCaContainerIso()             Sets the current record's "ca_container_iso" value
 * @method FalaDetail setCaCantidadPedido()           Sets the current record's "ca_cantidad_pedido" value
 * @method FalaDetail setCaCantidadMiles()            Sets the current record's "ca_cantidad_miles" value
 * @method FalaDetail setCaUnidadMedidadCantidad()    Sets the current record's "ca_unidad_medidad_cantidad" value
 * @method FalaDetail setCaDescripcionItem()          Sets the current record's "ca_descripcion_item" value
 * @method FalaDetail setCaCantidadPaquetesMiles()    Sets the current record's "ca_cantidad_paquetes_miles" value
 * @method FalaDetail setCaUnidadMedidaPaquetes()     Sets the current record's "ca_unidad_medida_paquetes" value
 * @method FalaDetail setCaCantidadVolumenMiles()     Sets the current record's "ca_cantidad_volumen_miles" value
 * @method FalaDetail setCaUnidadMedidaVolumen()      Sets the current record's "ca_unidad_medida_volumen" value
 * @method FalaDetail setCaCantidadPesoMiles()        Sets the current record's "ca_cantidad_peso_miles" value
 * @method FalaDetail setCaUnidadMedidaPeso()         Sets the current record's "ca_unidad_medida_peso" value
 * @method FalaDetail setFalaHeader()                 Sets the current record's "FalaHeader" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseFalaDetail extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_faladetails');
        $this->hasColumn('ca_iddoc', 'string', null, array(
             'type' => 'string',
             'primary' => true,
             ));
        $this->hasColumn('ca_sku', 'string', null, array(
             'type' => 'string',
             'primary' => true,
             ));
        $this->hasColumn('ca_vpn', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_num_cont_part1', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_num_cont_part2', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_num_cont_sell', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_container_iso', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_cantidad_pedido', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_cantidad_miles', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_unidad_medidad_cantidad', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_descripcion_item', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_cantidad_paquetes_miles', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('ca_unidad_medida_paquetes', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_cantidad_volumen_miles', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('ca_unidad_medida_volumen', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_cantidad_peso_miles', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('ca_unidad_medida_peso', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FalaHeader', array(
             'local' => 'ca_iddoc',
             'foreign' => 'ca_iddoc'));
    }
}