<?php

/**
 * BaseInoParametroCosto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idparametro
 * @property integer $ca_idconcepto
 * @property integer $ca_idccosto
 * @property integer $ca_idcuenta
 * @property InoConcepto $InoConcepto
 * @property InoCentroCosto $InoCentroCosto
 * @property InoCuenta $InoCuenta
 * 
 * @method integer           getCaIdparametro()  Returns the current record's "ca_idparametro" value
 * @method integer           getCaIdconcepto()   Returns the current record's "ca_idconcepto" value
 * @method integer           getCaIdccosto()     Returns the current record's "ca_idccosto" value
 * @method integer           getCaIdcuenta()     Returns the current record's "ca_idcuenta" value
 * @method InoConcepto       getInoConcepto()    Returns the current record's "InoConcepto" value
 * @method InoCentroCosto    getInoCentroCosto() Returns the current record's "InoCentroCosto" value
 * @method InoCuenta         getInoCuenta()      Returns the current record's "InoCuenta" value
 * @method InoParametroCosto setCaIdparametro()  Sets the current record's "ca_idparametro" value
 * @method InoParametroCosto setCaIdconcepto()   Sets the current record's "ca_idconcepto" value
 * @method InoParametroCosto setCaIdccosto()     Sets the current record's "ca_idccosto" value
 * @method InoParametroCosto setCaIdcuenta()     Sets the current record's "ca_idcuenta" value
 * @method InoParametroCosto setInoConcepto()    Sets the current record's "InoConcepto" value
 * @method InoParametroCosto setInoCentroCosto() Sets the current record's "InoCentroCosto" value
 * @method InoParametroCosto setInoCuenta()      Sets the current record's "InoCuenta" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseInoParametroCosto extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ino.tb_parametros_costos');
        $this->hasColumn('ca_idparametro', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('ca_idconcepto', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_idccosto', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_idcuenta', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('InoConcepto', array(
             'local' => 'ca_idconcepto',
             'foreign' => 'ca_idconcepto'));

        $this->hasOne('InoCentroCosto', array(
             'local' => 'ca_idccosto',
             'foreign' => 'ca_idccosto'));

        $this->hasOne('InoCuenta', array(
             'local' => 'ca_idcuenta',
             'foreign' => 'ca_idcuenta'));
    }
}