<?php

/**
 * BaseAduDocumentos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_consecutivo
 * @property integer $ca_idmaestra
 * @property string $ca_documento
 * @property date $ca_fecha
 * @property string $ca_numero
 * @property string $ca_observaciones
 * @property date $ca_fecha_recibido
 * @property time $ca_hora_recibido
 * @property timestamp $ca_fchcreado
 * @property string $ca_usucreado
 * @property timestamp $ca_fchactualizado
 * @property string $ca_usuactualizado
 * @property InoMaestra $InoMaestra
 * @property Usuario $UsuCreado
 * @property Usuario $UsuActualizado
 * 
 * @method integer       getCaConsecutivo()     Returns the current record's "ca_consecutivo" value
 * @method integer       getCaIdmaestra()       Returns the current record's "ca_idmaestra" value
 * @method string        getCaDocumento()       Returns the current record's "ca_documento" value
 * @method date          getCaFecha()           Returns the current record's "ca_fecha" value
 * @method string        getCaNumero()          Returns the current record's "ca_numero" value
 * @method string        getCaObservaciones()   Returns the current record's "ca_observaciones" value
 * @method date          getCaFechaRecibido()   Returns the current record's "ca_fecha_recibido" value
 * @method time          getCaHoraRecibido()    Returns the current record's "ca_hora_recibido" value
 * @method timestamp     getCaFchcreado()       Returns the current record's "ca_fchcreado" value
 * @method string        getCaUsucreado()       Returns the current record's "ca_usucreado" value
 * @method timestamp     getCaFchactualizado()  Returns the current record's "ca_fchactualizado" value
 * @method string        getCaUsuactualizado()  Returns the current record's "ca_usuactualizado" value
 * @method InoMaestra    getInoMaestra()        Returns the current record's "InoMaestra" value
 * @method Usuario       getUsuCreado()         Returns the current record's "UsuCreado" value
 * @method Usuario       getUsuActualizado()    Returns the current record's "UsuActualizado" value
 * @method AduDocumentos setCaConsecutivo()     Sets the current record's "ca_consecutivo" value
 * @method AduDocumentos setCaIdmaestra()       Sets the current record's "ca_idmaestra" value
 * @method AduDocumentos setCaDocumento()       Sets the current record's "ca_documento" value
 * @method AduDocumentos setCaFecha()           Sets the current record's "ca_fecha" value
 * @method AduDocumentos setCaNumero()          Sets the current record's "ca_numero" value
 * @method AduDocumentos setCaObservaciones()   Sets the current record's "ca_observaciones" value
 * @method AduDocumentos setCaFechaRecibido()   Sets the current record's "ca_fecha_recibido" value
 * @method AduDocumentos setCaHoraRecibido()    Sets the current record's "ca_hora_recibido" value
 * @method AduDocumentos setCaFchcreado()       Sets the current record's "ca_fchcreado" value
 * @method AduDocumentos setCaUsucreado()       Sets the current record's "ca_usucreado" value
 * @method AduDocumentos setCaFchactualizado()  Sets the current record's "ca_fchactualizado" value
 * @method AduDocumentos setCaUsuactualizado()  Sets the current record's "ca_usuactualizado" value
 * @method AduDocumentos setInoMaestra()        Sets the current record's "InoMaestra" value
 * @method AduDocumentos setUsuCreado()         Sets the current record's "UsuCreado" value
 * @method AduDocumentos setUsuActualizado()    Sets the current record's "UsuActualizado" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAduDocumentos extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('adu.tb_documentos');
        $this->hasColumn('ca_consecutivo', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('ca_idmaestra', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ca_documento', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('ca_fecha', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_numero', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_observaciones', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fecha_recibido', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_hora_recibido', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('ca_fchcreado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usucreado', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchactualizado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usuactualizado', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('InoMaestra', array(
             'local' => 'ca_idmaestra',
             'foreign' => 'ca_idmaestra'));

        $this->hasOne('Usuario as UsuCreado', array(
             'local' => 'ca_usucreado',
             'foreign' => 'ca_login'));

        $this->hasOne('Usuario as UsuActualizado', array(
             'local' => 'ca_usuactualizado',
             'foreign' => 'ca_login'));
    }
}