<?php

/**
 * BaseInoComprobante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idcomprobante
 * @property integer $ca_id
 * @property integer $ca_idtipo
 * @property string $ca_consecutivo
 * @property date $ca_fchcomprobante
 * @property integer $ca_idmaster
 * @property integer $ca_idhouse
 * @property integer $ca_plazo
 * @property decimal $ca_tcambio
 * @property string $ca_observaciones
 * @property integer $ca_estado
 * @property float $ca_valor
 * @property float $ca_valor2
 * @property integer $ca_idsucursal
 * @property string $ca_idmoneda
 * @property timestamp $ca_fchcreado
 * @property string $ca_usucreado
 * @property timestamp $ca_fchactualizado
 * @property string $ca_usuactualizado
 * @property timestamp $ca_fchanulado
 * @property string $ca_usuanulado
 * @property string $ca_propiedades
 * @property timestamp $ca_fchgenero
 * @property string $ca_usugenero
 * @property integer $ca_idcomprobante_cruce
 * @property integer $ca_idccosto
 * @property integer $ca_docentry
 * @property integer $ca_estadofe
 * @property string $ca_datos
 * @property string $ca_datosfe
 * @property Ids $Ids
 * @property Usuario $UsuCreado
 * @property Usuario $UsuActualizado
 * @property Doctrine_Collection $InoDetalle
 * @property InoTipoComprobante $InoTipoComprobante
 * @property Moneda $Moneda
 * @property IdsSucursal $IdsSucursal
 * @property InoCentroCosto $InoCentroCosto
 * @property InoComprobante $InoComprobanteCruce
 * @property Doctrine_Collection $InoCosto
 * @property InoHouse $InoHouse
 * @property Doctrine_Collection $InoComprobante
 * @property Doctrine_Collection $InoDeduccion
 * @property InoViConsComprobante $InoViConsComprobante
 * @property InoViBusqueda $InoViBusqueda
 * 
 * @method integer              getCaIdcomprobante()        Returns the current record's "ca_idcomprobante" value
 * @method integer              getCaId()                   Returns the current record's "ca_id" value
 * @method integer              getCaIdtipo()               Returns the current record's "ca_idtipo" value
 * @method string               getCaConsecutivo()          Returns the current record's "ca_consecutivo" value
 * @method date                 getCaFchcomprobante()       Returns the current record's "ca_fchcomprobante" value
 * @method integer              getCaIdmaster()             Returns the current record's "ca_idmaster" value
 * @method integer              getCaIdhouse()              Returns the current record's "ca_idhouse" value
 * @method integer              getCaPlazo()                Returns the current record's "ca_plazo" value
 * @method decimal              getCaTcambio()              Returns the current record's "ca_tcambio" value
 * @method string               getCaObservaciones()        Returns the current record's "ca_observaciones" value
 * @method integer              getCaEstado()               Returns the current record's "ca_estado" value
 * @method float                getCaValor()                Returns the current record's "ca_valor" value
 * @method float                getCaValor2()               Returns the current record's "ca_valor2" value
 * @method integer              getCaIdsucursal()           Returns the current record's "ca_idsucursal" value
 * @method string               getCaIdmoneda()             Returns the current record's "ca_idmoneda" value
 * @method timestamp            getCaFchcreado()            Returns the current record's "ca_fchcreado" value
 * @method string               getCaUsucreado()            Returns the current record's "ca_usucreado" value
 * @method timestamp            getCaFchactualizado()       Returns the current record's "ca_fchactualizado" value
 * @method string               getCaUsuactualizado()       Returns the current record's "ca_usuactualizado" value
 * @method timestamp            getCaFchanulado()           Returns the current record's "ca_fchanulado" value
 * @method string               getCaUsuanulado()           Returns the current record's "ca_usuanulado" value
 * @method string               getCaPropiedades()          Returns the current record's "ca_propiedades" value
 * @method timestamp            getCaFchgenero()            Returns the current record's "ca_fchgenero" value
 * @method string               getCaUsugenero()            Returns the current record's "ca_usugenero" value
 * @method integer              getCaIdcomprobanteCruce()   Returns the current record's "ca_idcomprobante_cruce" value
 * @method integer              getCaIdccosto()             Returns the current record's "ca_idccosto" value
 * @method integer              getCaDocentry()             Returns the current record's "ca_docentry" value
 * @method integer              getCaEstadofe()               Returns the current record's "ca_estadofe" value
 * @method string               getCaDatos()                Returns the current record's "ca_datos" value
 * @method string               getCaDatosfe()                Returns the current record's "ca_datosfe" value
 * @method Ids                  getIds()                    Returns the current record's "Ids" value
 * @method Usuario              getUsuCreado()              Returns the current record's "UsuCreado" value
 * @method Usuario              getUsuActualizado()         Returns the current record's "UsuActualizado" value
 * @method Doctrine_Collection  getInoDetalle()             Returns the current record's "InoDetalle" collection
 * @method InoTipoComprobante   getInoTipoComprobante()     Returns the current record's "InoTipoComprobante" value
 * @method Moneda               getMoneda()                 Returns the current record's "Moneda" value
 * @method IdsSucursal          getIdsSucursal()            Returns the current record's "IdsSucursal" value
 * @method InoCentroCosto       getInoCentroCosto()         Returns the current record's "InoCentroCosto" value
 * @method InoComprobante       getInoComprobanteCruce()    Returns the current record's "InoComprobanteCruce" value
 * @method Doctrine_Collection  getInoCosto()               Returns the current record's "InoCosto" collection
 * @method InoHouse             getInoHouse()               Returns the current record's "InoHouse" value
 * @method Doctrine_Collection  getInoComprobante()         Returns the current record's "InoComprobante" collection
 * @method Doctrine_Collection  getInoDeduccion()           Returns the current record's "InoDeduccion" collection
 * @method InoViConsComprobante getInoViConsComprobante()   Returns the current record's "InoViConsComprobante" value
 * @method InoViBusqueda        getInoViBusqueda()          Returns the current record's "InoViBusqueda" value
 * @method Doctrine_Collection  getSiigoComprobante()       Returns the current record's "SiigoComprobante" collection
 * @method InoComprobante       setCaIdcomprobante()        Sets the current record's "ca_idcomprobante" value
 * @method InoComprobante       setCaId()                   Sets the current record's "ca_id" value
 * @method InoComprobante       setCaIdtipo()               Sets the current record's "ca_idtipo" value
 * @method InoComprobante       setCaConsecutivo()          Sets the current record's "ca_consecutivo" value
 * @method InoComprobante       setCaFchcomprobante()       Sets the current record's "ca_fchcomprobante" value
 * @method InoComprobante       setCaIdmaster()             Sets the current record's "ca_idmaster" value
 * @method InoComprobante       setCaIdhouse()              Sets the current record's "ca_idhouse" value
 * @method InoComprobante       setCaPlazo()                Sets the current record's "ca_plazo" value
 * @method InoComprobante       setCaTcambio()              Sets the current record's "ca_tcambio" value
 * @method InoComprobante       setCaObservaciones()        Sets the current record's "ca_observaciones" value
 * @method InoComprobante       setCaEstado()               Sets the current record's "ca_estado" value
 * @method InoComprobante       setCaValor()                Sets the current record's "ca_valor" value
 * @method InoComprobante       setCaValor2()               Sets the current record's "ca_valor2" value
 * @method InoComprobante       setCaIdsucursal()           Sets the current record's "ca_idsucursal" value
 * @method InoComprobante       setCaIdmoneda()             Sets the current record's "ca_idmoneda" value
 * @method InoComprobante       setCaFchcreado()            Sets the current record's "ca_fchcreado" value
 * @method InoComprobante       setCaUsucreado()            Sets the current record's "ca_usucreado" value
 * @method InoComprobante       setCaFchactualizado()       Sets the current record's "ca_fchactualizado" value
 * @method InoComprobante       setCaUsuactualizado()       Sets the current record's "ca_usuactualizado" value
 * @method InoComprobante       setCaFchanulado()           Sets the current record's "ca_fchanulado" value
 * @method InoComprobante       setCaUsuanulado()           Sets the current record's "ca_usuanulado" value
 * @method InoComprobante       setCaPropiedades()          Sets the current record's "ca_propiedades" value
 * @method InoComprobante       setCaFchgenero()            Sets the current record's "ca_fchgenero" value
 * @method InoComprobante       setCaUsugenero()            Sets the current record's "ca_usugenero" value
 * @method InoComprobante       setCaIdcomprobanteCruce()   Sets the current record's "ca_idcomprobante_cruce" value
 * @method InoComprobante       setCaIdccosto()             Sets the current record's "ca_idccosto" value
 * @method InoComprobante       setCaDocentry()             Sets the current record's "ca_docentry" value
 * @method InoComprobante       setCaEstadofe()               Sets the current record's "ca_estadofe" value
 * @method InoComprobante       setCaDatos()                Sets the current record's "ca_datos" value
 * @method InoComprobante       setCaDatosfe()                Sets the current record's "ca_datosfe" value
 * @method InoComprobante       setIds()                    Sets the current record's "Ids" value
 * @method InoComprobante       setUsuCreado()              Sets the current record's "UsuCreado" value
 * @method InoComprobante       setUsuActualizado()         Sets the current record's "UsuActualizado" value
 * @method InoComprobante       setInoDetalle()             Sets the current record's "InoDetalle" collection
 * @method InoComprobante       setInoTipoComprobante()     Sets the current record's "InoTipoComprobante" value
 * @method InoComprobante       setMoneda()                 Sets the current record's "Moneda" value
 * @method InoComprobante       setIdsSucursal()            Sets the current record's "IdsSucursal" value
 * @method InoComprobante       setInoCentroCosto()         Sets the current record's "InoCentroCosto" value
 * @method InoComprobante       setInoComprobanteCruce()    Sets the current record's "InoComprobanteCruce" value
 * @method InoComprobante       setInoCosto()               Sets the current record's "InoCosto" collection
 * @method InoComprobante       setInoHouse()               Sets the current record's "InoHouse" value
 * @method InoComprobante       setInoComprobante()         Sets the current record's "InoComprobante" collection
 * @method InoComprobante       setInoDeduccion()           Sets the current record's "InoDeduccion" collection
 * @method InoComprobante       setInoViConsComprobante()   Sets the current record's "InoViConsComprobante" value
 * @method InoComprobante       setInoViBusqueda()          Sets the current record's "InoViBusqueda" value 
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseInoComprobante extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ino.tb_comprobantes');
        $this->hasColumn('ca_idcomprobante', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('ca_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_idtipo', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_consecutivo', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchcomprobante', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ca_idmaster', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_idhouse', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_plazo', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_tcambio', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('ca_observaciones', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_estado', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_valor', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('ca_valor2', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('ca_idsucursal', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_idmoneda', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchcreado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usucreado', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchactualizado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usuactualizado', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchanulado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usuanulado', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_propiedades', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchgenero', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usugenero', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_idcomprobante_cruce', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_idccosto', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_docentry', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_datos', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_estadofe', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_datosfe', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ids', array(
             'local' => 'ca_id',
             'foreign' => 'ca_id'));

        $this->hasOne('Usuario as UsuCreado', array(
             'local' => 'ca_usucreado',
             'foreign' => 'ca_login'));

        $this->hasOne('Usuario as UsuActualizado', array(
             'local' => 'ca_usuactualizado',
             'foreign' => 'ca_login'));

        $this->hasMany('InoDetalle', array(
             'local' => 'ca_idcomprobante',
             'foreign' => 'ca_idcomprobante'));

        $this->hasOne('InoTipoComprobante', array(
             'local' => 'ca_idtipo',
             'foreign' => 'ca_idtipo'));

        $this->hasOne('Moneda', array(
             'local' => 'ca_idmoneda',
             'foreign' => 'ca_idmoneda'));

        $this->hasOne('IdsSucursal', array(
             'local' => 'ca_idsucursal',
             'foreign' => 'ca_idsucursal'));

        $this->hasOne('InoCentroCosto', array(
             'local' => 'ca_idccosto',
             'foreign' => 'ca_idccosto'));

        $this->hasOne('InoComprobante as InoComprobanteCruce', array(
             'local' => 'ca_idcomprobante_cruce',
             'foreign' => 'ca_idcomprobante'));

        $this->hasMany('InoCosto', array(
             'local' => 'ca_idcomprobante',
             'foreign' => 'ca_idcomprobante'));

        $this->hasOne('InoHouse', array(
             'local' => 'ca_idhouse',
             'foreign' => 'ca_idhouse'));

        $this->hasMany('InoComprobante', array(
             'local' => 'ca_idcomprobante',
             'foreign' => 'ca_idcomprobante_cruce'));

        $this->hasMany('InoDeduccion', array(
             'local' => 'ca_idcomprobante',
             'foreign' => 'ca_idcomprobante'));

        $this->hasOne('InoViConsComprobante', array(
             'local' => 'ca_idhouse',
             'foreign' => 'ca_idhouse'));

        $this->hasOne('InoViBusqueda', array(
             'local' => 'ca_idhouse',
             'foreign' => 'ca_idhouse'));
        
    }
}