<?php

/**
 * BaseNotListaTareas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idlistatarea
 * @property string $ca_nombre
 * @property string $ca_descripcion
 * @property Doctrine_Collection $NotTarea
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6508 2009-10-14 06:28:49Z jwage $
 */
abstract class BaseNotListaTareas extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notificaciones.tb_listatareas');
        $this->hasColumn('ca_idlistatarea', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ca_nombre', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_descripcion', 'string', null, array(
             'type' => 'string',
             ));


        $this->setAttribute(Doctrine_Core::ATTR_EXPORT, Doctrine_Core::EXPORT_TABLES);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('NotTarea', array(
             'local' => 'ca_idlistatarea',
             'foreign' => 'ca_idlistatarea'));
    }
}