<?php

/**
 * BaseUsuHijos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idhijo
 * @property integer $ca_documento
 * @property string $ca_nombres
 * @property date $ca_fchnacimiento
 * @property integer $ca_escolaridad
 * @property timestamp $ca_fchcreado
 * @property string $ca_usucreado
 * @property timestamp $ca_fchactualizado
 * @property string $ca_usuactualizado
 * @property Usuario $UsuCreado
 * @property Usuario $UsuActualizado
 * @property UsuParents $UsuParents
 * 
 * @method integer    getCaIdhijo()          Returns the current record's "ca_idhijo" value
 * @method integer    getCaDocumento()       Returns the current record's "ca_documento" value
 * @method string     getCaNombres()         Returns the current record's "ca_nombres" value
 * @method date       getCaFchnacimiento()   Returns the current record's "ca_fchnacimiento" value
 * @method integer    getCaEscolaridad()     Returns the current record's "ca_escolaridad" value
 * @method timestamp  getCaFchcreado()       Returns the current record's "ca_fchcreado" value
 * @method string     getCaUsucreado()       Returns the current record's "ca_usucreado" value
 * @method timestamp  getCaFchactualizado()  Returns the current record's "ca_fchactualizado" value
 * @method string     getCaUsuactualizado()  Returns the current record's "ca_usuactualizado" value
 * @method Usuario    getUsuCreado()         Returns the current record's "UsuCreado" value
 * @method Usuario    getUsuActualizado()    Returns the current record's "UsuActualizado" value
 * @method UsuParents getUsuParents()        Returns the current record's "UsuParents" value
 * @method UsuHijos   setCaIdhijo()          Sets the current record's "ca_idhijo" value
 * @method UsuHijos   setCaDocumento()       Sets the current record's "ca_documento" value
 * @method UsuHijos   setCaNombres()         Sets the current record's "ca_nombres" value
 * @method UsuHijos   setCaFchnacimiento()   Sets the current record's "ca_fchnacimiento" value
 * @method UsuHijos   setCaEscolaridad()     Sets the current record's "ca_escolaridad" value
 * @method UsuHijos   setCaFchcreado()       Sets the current record's "ca_fchcreado" value
 * @method UsuHijos   setCaUsucreado()       Sets the current record's "ca_usucreado" value
 * @method UsuHijos   setCaFchactualizado()  Sets the current record's "ca_fchactualizado" value
 * @method UsuHijos   setCaUsuactualizado()  Sets the current record's "ca_usuactualizado" value
 * @method UsuHijos   setUsuCreado()         Sets the current record's "UsuCreado" value
 * @method UsuHijos   setUsuActualizado()    Sets the current record's "UsuActualizado" value
 * @method UsuHijos   setUsuParents()        Sets the current record's "UsuParents" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUsuHijos extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('intranet.tb_usuhijos');
        $this->hasColumn('ca_idhijo', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ca_documento', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_nombres', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('ca_fchnacimiento', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('ca_escolaridad', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ca_fchcreado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usucreado', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_fchactualizado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ca_usuactualizado', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('form', true);
        $this->option('filter', true);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario as UsuCreado', array(
             'local' => 'ca_usucreado',
             'foreign' => 'ca_login'));

        $this->hasOne('Usuario as UsuActualizado', array(
             'local' => 'ca_usuactualizado',
             'foreign' => 'ca_login'));

        $this->hasOne('UsuParents', array(
             'local' => 'ca_idhijo',
             'foreign' => 'ca_idhijo'));
    }
}