<?php

/**
 * BaseSia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ca_idsia
 * @property string $ca_nombre
 * @property string $ca_tel
 * @property string $ca_contacto
 * @property Doctrine_Collection $RepExpo
 * 
 * @method integer             getCaIdsia()     Returns the current record's "ca_idsia" value
 * @method string              getCaNombre()    Returns the current record's "ca_nombre" value
 * @method string              getCaTel()       Returns the current record's "ca_tel" value
 * @method string              getCaContacto()  Returns the current record's "ca_contacto" value
 * @method Doctrine_Collection getRepExpo()     Returns the current record's "RepExpo" collection
 * @method Sia                 setCaIdsia()     Sets the current record's "ca_idsia" value
 * @method Sia                 setCaNombre()    Sets the current record's "ca_nombre" value
 * @method Sia                 setCaTel()       Sets the current record's "ca_tel" value
 * @method Sia                 setCaContacto()  Sets the current record's "ca_contacto" value
 * @method Sia                 setRepExpo()     Sets the current record's "RepExpo" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseSia extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_sia');
        $this->hasColumn('ca_idsia', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ca_nombre', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_tel', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ca_contacto', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RepExpo', array(
             'local' => 'ca_idsia',
             'foreign' => 'ca_idsia'));
    }
}