<?php

/**
 * BaseIdsTipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ca_tipo
 * @property string $ca_nombre
 * @property string $ca_aplicacion
 * @property IdsAgente $IdsAgente
 * @property IdsProveedor $IdsProveedor
 * 
 * @method string       getCaTipo()        Returns the current record's "ca_tipo" value
 * @method string       getCaNombre()      Returns the current record's "ca_nombre" value
 * @method string       getCaAplicacion()  Returns the current record's "ca_aplicacion" value
 * @method IdsAgente    getIdsAgente()     Returns the current record's "IdsAgente" value
 * @method IdsProveedor getIdsProveedor()  Returns the current record's "IdsProveedor" value
 * @method IdsTipo      setCaTipo()        Sets the current record's "ca_tipo" value
 * @method IdsTipo      setCaNombre()      Sets the current record's "ca_nombre" value
 * @method IdsTipo      setCaAplicacion()  Sets the current record's "ca_aplicacion" value
 * @method IdsTipo      setIdsAgente()     Sets the current record's "IdsAgente" value
 * @method IdsTipo      setIdsProveedor()  Sets the current record's "IdsProveedor" value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseIdsTipo extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ids.tb_tipos');
        $this->hasColumn('ca_tipo', 'string', 3, array(
             'type' => 'string',
             'primary' => true,
             'length' => '3',
             ));
        $this->hasColumn('ca_nombre', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('ca_aplicacion', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('IdsAgente', array(
             'local' => 'ca_tipo',
             'foreign' => 'ca_tipo'));

        $this->hasOne('IdsProveedor', array(
             'local' => 'ca_tipo',
             'foreign' => 'ca_tipo'));
    }
}