<?php

/**
 * Empresa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Empresa extends BaseEmpresa
{
    function getLogoHtml(){
        
        switch($this->getCaIdempresa()){
            case 1:
                $link = 'http://www.coltrans.com.co/logosoficiales/colmas/ColmasSmall.png';
                break;
            case 2:
                $link = 'http://www.coltrans.com.co/logosoficiales/coltrans/ColtransSmall.png';
                break;
            case 4:
                $link = 'http://www.coltrans.com.co/logosoficiales/consolcargo/ConsolcargoSmall.png';
                break;
            case 8:
                $link = 'http://www.coltrans.com.co/logosoficiales/colotm/logo_colotm.png';
                break;
            case 11:
                $link = 'http://www.coltrans.com.co/logosoficiales/coldepositos/ColdepositosSmall.jpg';
                break;
            default:
                $link = "";
        }
        
        return $link;
    }
}