#Recuerde identar correctamente las notas y los correspondientes espacios entre renglones 
#RECOMENDACION USE NOTEPAD++ PARA EDITAR ESTE ARCHIVO 
saludo: |
  Estimado cliente, reciba un cordial saludo

mensajeEmbarqueMaritimo: |
  - FAVOR TENER EN CUENTA QUE LA FECHA DE ARRIBO ES UN ESTIMADO. TAN PRONTO EL BUQUE LLEGUE A PUERTO, NUESTRO DEPARTAMENTO OPERATIVO MARITIMO LES NOTIFICARÁ.

mensajeEmbarqueOTM: |
  - COMO REQUISITO INDISPENSABLE PARA EFECTUAR EL OTM NECESITAMOS COPIA DE LA FACTURA COMERCIAL EN LA CUAL APAREZCA LA NEGOCIACION INCOTERM CON SU RESPECTIVO VALOR, ORIGINAL DEL CONOCIMIENTO DE EMBARQUE (HBL).

mensajeReservaMaritimo: |
  - FAVOR TENER EN CUENTA QUE LA FECHA DE ZARPE Y DE ARRIBO SON UN ESTIMADO. TAN PRONTO EL BUQUE ZARPE, NUESTRO DEPARTAMENTO DE TRAFICOS LES NOTIFICARÁ.

mensajeAereo: |
  De acuerdo a las condiciones del contrato de transporte, la persona con derecho a la entrega deberá reclamar por escrito al transportista en caso de daño visible a la mercancía; a mas tardar a los catorce (14) días a partir de la fecha de manifiesto o llegada de la misma al país.

mensajeConfOTM: |
  Respetado cliente buenos días, nos complace suministrarle nueva información en relación a su carga en OTM. 
mensajeCierreOTM: |  
  Confirmamos cierre y finalización de los documentos del proceso de OTM, los cuales se encuentran en nuestras oficinas para la correspondiente liberación.
  
mensajeConfOTMCliente: |
  Como requisito indispensable para efectuar el OTM necesitamos los siguientes documentos:
  - HBL original
  - Copia Factura Comercial con Término de Negociación
  - Copia Lista de Empaque
  - Copia Póliza de Seguro
  
  Si su mercancía requiere tramite Invima favor enviar original del certificado del proveedor de mercancia apta para el consumo humano+ el registro de importación.
  
  
  Cualquier información adicional respecto al OTM favor contactar a  
