#Recuerde identar correctamente las notas y los correspondientes espacios entre renglones 
#RECOMENDACION USE NOTEPAD++ PARA EDITAR ESTE ARCHIVO 
saludo: |
  Estimado cliente, reciba un cordial saludo

mensajeEmbarqueMaritimo: |
  - FAVOR TENER EN CUENTA QUE LA FECHA DE ARRIBO ES UN ESTIMADO. TAN PRONTO EL BUQUE LLEGUE A PUERTO, NUESTRO DEPARTAMENTO OPERATIVO MARITIMO LES NOTIFICARÁ.

mensajeEmbarqueOTM: |
  - COMO REQUISITO INDISPENSABLE PARA EFECTUAR EL OTM NECESITAMOS COPIA DE LA FACTURA COMERCIAL EN LA CUAL APAREZCA LA NEGOCIACION INCOTERM CON SU RESPECTIVO VALOR, ORIGINAL DEL CONOCIMIENTO DE EMBARQUE (HBL).

mensajeReservaMaritimo: |
  - FAVOR TENER EN CUENTA QUE LA FECHA DE ZARPE Y DE ARRIBO SON UN ESTIMADO. TAN PRONTO EL BUQUE ZARPE, NUESTRO DEPARTAMENTO DE TRAFICOS LES NOTIFICARÁ.

mensajeAereo: |
  De acuerdo a las condiciones del contrato de transporte, la persona con derecho a la entrega deberá reclamar por escrito al transportista en caso de daño visible a la mercancía; a mas tardar a los catorce (14) días a partir de la fecha de manifiesto o llegada de la misma al país.

mensajeConfOTM: |
  Respetado cliente buenos días, nos complace suministrarle nueva información en relación a su carga en OTM. 
mensajeCierreOTM: |  
  Confirmamos cierre y finalización de los documentos del proceso de OTM, los cuales se encuentran en nuestras oficinas para la correspondiente liberación.
  
mensajeConfOTMCliente: |
  Como requisito indispensable para efectuar el OTM necesitamos los siguientes documentos:
  - Hbl original
  - Copia de la factura comercial conteniendo la siguiente información: Moneda, termino de negociación,Nombre del Proveedor , debe venir consignada a nombre del Importador, Numero de factura .
  - Copia de la lista de empaque, debe detallar las piezas y peso de la mercancía.
  - Descripción de la mercancía en español.
  - Enviar certificación de gastos adicionales si se requieren dependiendo del termino de negociación de la factura comercial.
  - Certificación de fletes.
  - RUT del importador actualizado.
  - Copia del registro de importación o certificación de las posiciones arancelarias.
  - Copia de la póliza de Seguros amparando el trayecto interno e incluyendo el valor de los tributos Aduaneros + Iva. Los reclamos serán atendidos vía subrogación.
  
  Si su mercancía requiere tramite Invima favor enviar original del certificado del proveedor de mercancia apta para el consumo humano+ el registro de importación.
  
  
  Cualquier información adicional respecto al OTM favor contactar a  
