#Recuerde identar correctamente las notas y los correspondientes espacios entre renglones 
#RECOMENDACION USE NOTEPAD++ PARA EDITAR ESTE ARCHIVO 

mensajeEmbarqueMaritimo: |
  - FAVOR TENER EN CUENTA QUE LA FECHA DE ARRIBO ES UN ESTIMADO. TAN PRONTO EL BUQUE LLEGUE A PUERTO, NUESTRO DEPARTAMENTO OPERATIVO MARITIMO LES NOTIFICARÁ.

mensajeEmbarqueOTM: |
  - COMO REQUISITO INDISPENSABLE PARA EFECTUAR EL OTM NECESITAMOS COPIA DE LA FACTURA COMERCIAL EN LA CUAL APAREZCA LA NEGOCIACION INCOTERM CON SU RESPECTIVO VALOR, ORIGINAL DEL CONOCIMIENTO DE EMBARQUE (HBL).

mensajeReservaMaritimo: |
  - FAVOR TENER EN CUENTA QUE LA FECHA DE ZARPE Y DE ARRIBO SON UN ESTIMADO. TAN PRONTO EL BUQUE ZARPE, NUESTRO DEPARTAMENTO DE TRAFICOS LES NOTIFICARÁ.

mensajeAereo: |
  De acuerdo a las condiciones del contrato de transporte, la persona con derecho a la entrega deberá reclamar por escrito al transportista en caso de daño visible a la mercancía; a mas tardar a los catorce (14) días a partir de la fecha de manifiesto o llegada de la misma al país.

  

