# default values
all:
  digitalFile:
    root:  /srv/www/digitalFile/
#     root:  C:\Desarrollo\digitalFile\
  smtp:
    host: 10.192.1.30
#    user:  tasas_cambios
#    passwd:  tasas_cambios
    port: 25
    debugAddress: abotero@coltrans.com.co

