# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:
all:
  digitalFile:
    root:  /srv/www/digitalFile/
    
  sourceCode:
    plugins:  /srv/www/colsys_sf3/plugins/
    lib:  /srv/www/colsys_sf3/lib/

  branding:
    template: coltrans
    url: www.colsys.com.co
    name: Coltrans S.A.S. - Colmas S.A.S.
    from: serclientebog@coltrans.com.co

  smtp:
    host: 172.16.1.18
    user:  tasas_cambios
    passwd:  tasas_cambios
    port: 25
#    debugAddress: abotero@coltrans.com.co
    
  ldap:
    host: 172.16.1.22
    auth_enabled: true
