# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~
  

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: none

dev:
  mailer:
    param:
      delivery_strategy: none

all:
  storage:
#    class: sfSessionStorage
#    param:
#      session_name: coltrans_tracking
    class: sfCacheSessionStorage
    param:
      session_name: coltrans_tracking
      session_cookie_secure: true
      session_cookie_secret: ArdttE!hvaaad
      session_cookie_lifetime: null
      cache:
        class: sfMemcacheCache
        param:
          storeCacheInfo: false
          lifetime: 86400
          prefix: tracksess
          servers:
            localserver:
              host: 172.16.1.13
              port: 11211
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true

