default:
  http_metas:
    content-type: text/html

  metas:
    title:        Coltrans S.A - Colmas LTDA.
    robots:       index, follow
    description:  sistema de tracking 
    keywords:     tracking, cargo
    language:     es

  stylesheets:    [tracking, ext/css/ext-all, ext/css/xtheme-gray]

  javascripts:    [tracking, ext/adapter/ext/ext-base, ext/ext-all-debug, tracking ]

  has_layout:     true
  layout:         layout
