#all:
#  propel:
#    class:          sfPropelDatabase
#    param:
#      dsn:          mysql://root:@localhost/dbname

#all:
#  propel:
#    class:          sfPropelDatabase
#    param:
#      dsn:          pgsql://postgres:Codigo0@localhost/Pruebas
#      dsn:          pgsql://Administrador:sistemassrv@10.192.1.127/Pruebas

all:
  propel:
    class:                sfPropelDatabase
    param:
      phptype:            pgsql     # Database vendor
      hostspec:           10.192.1.127
      database:           Pruebas
      username:           postgres
      password:           sistemassrv
      port:               5432
