dev:
  doctrine:
    param:
      classname: DebugPDO
cli:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'pgsql:dbname=Coltrans;host=172.16.1.16'
      username: postgres
      password: V9p0%rRc9$
      encoding: iso8859-1

prod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      is_master: true
      dsn: 'pgsql:dbname=Coltrans;host=172.16.1.16'
      username: postgres
      password: V9p0%rRc9$
      encoding: iso8859-1

coltrans:
  doctrine:
    class: sfDoctrineDatabase
    param:
      is_master: true
      dsn: 'pgsql:dbname=Coltrans;host=172.16.1.16'
      username: postgres
      password: V9p0%rRc9$
      encoding: iso8859-1

consolcargo:
  doctrine:
    class: sfDoctrineDatabase
    param:
      is_master: true
      dsn: 'pgsql:dbname=Consolcargo;host=172.16.1.16'
      username: postgres
      password: V9p0%rRc9$
      encoding: iso8859-1
