dev:
  doctrine:
    param:
      classname: DebugPDO
cli:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'pgsql:dbname=Coltrans;host=10.192.1.65'
      username: postgres
      password: cglti$col91
      encoding: iso8859-1



all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      is_master: true
      dsn: 'pgsql:dbname=Coltrans;host=10.192.1.65'

      username: Administrador
      password: cglti$col91
      encoding: iso8859-1
