dev:
  doctrine:
    param:
      classname: DebugPDO
all:  
  doctrine:
    class: sfDoctrineDatabase
    param:
#      dsn: 'pgsql:dbname=Coltrans;host=10.192.1.127'
#      username: Administrador
#      password: cglti$col91

      dsn: 'pgsql:dbname=Coltrans;host=localhost'
      username: Administrador
      password: sistemassrv
      
      encoding: iso8859-1
