dev:
  doctrine:
    param:
      classname: DebugPDO
all:  
  doctrine:
    class: sfDoctrineDatabase
    param:
#      dsn: 'pgsql:dbname=Coltrans;host=10.192.1.127'
      dsn: 'pgsql:dbname=Coltrans;host=10.192.1.87'
#      dsn: 'pgsql:dbname=Coltrans;host=10.192.1.126'
      username: Administrador
#      username: pgpool2
#      password: cglti$col91
      password: sistemassrv
      encoding: iso8859-1
