#Recuerde identar correctamente las notas y los correspondientes espacios entre renglones 
#RECOMENDACION USE NOTEPAD++ PARA EDITAR ESTE ARCHIVO 

asunto: COTIZACION

saludo: 'Respetados Señores:'  

entrada: 'Nos  complace  saludarlos,  nos permitimos presentar oferta para el transporte internacional de mercancía no peligrosa ni extradimensionada así:'

despedida: Esperamos que esta cotización sea de su conveniencia y quedamos a su entera disposición para atender cualquier inquietud adicional.

anexos: Notas importantes para sus importaciones y/o exportaciones.

asuntoEmail: 'COTIZACION COLTRANS N° C%s'
  
mensajeEmail: |
  Estimado(a)  señor(a)  %s:
  
  Anexo  nos permitimos enviar  nuestra  comunicación No.  %s  correspondiente  al  servicio  de  transporte  internacional  de  mercancía  no peligrosa  ni  extradimensionada.
  
  Esperamos que esta oferta sea de su conveniencia y quedamos atentos a cualquier inquietud adicional  que  se  pueda  presentar.
  
  Cordialmente,
