# default values
all:
  digitalFile:
    root:  /home/abotero/Desarrollo/digitalFile/    
#    root:  C:\Desarrollo\digitalFile\


  branding:
    template: coltrans
    url: www.coltrans.com.co
    name: Coltrans S.A. - Colmas Ltda.

  smtp:
    host: smtp.coltrans.com.co
    user:  tasas_cambios
    passwd:  tasas_cambios
#    host: smtp.colmas.com.co
#    user: bogota-aduana@colmas.com.co
#    passwd:  bogotaadu
    port: 25
#    debugAddress: maquinche@coltrans.com.co
    debugAddress: abotero@coltrans.com.co
#    debugAddress: botero82@gmail.com
#    public_ip: 200.14.235.62

  ldap:
    host: 10.192.1.83
    auth_enabled: true


  memcache:
#    host: 127.0.0.1
    host: 10.192.1.62
    port: 11211
    prefix: colsess

  session:
    maxinactive: 1800
#archivos de falabella
  falabella:
    input:  /home/falabella/OUT
    input_processed:  /home/falabella/OUT/processed
    output:  /home/falabella/IN    
#    input: c:\fala\
#    input_processed: c:\fala\procesados\
  gestDocumental:
    noAuth: KBaseWeb, KBase

 