# default values
all:
  digitalFile:
#    root:  /srv/www/digitalFile/
     root:  C:\Desarrollo\digitalFile\

  smtp:
    host: 10.192.1.30
#    host: smtp.colmas.com.co
    user:  tasas_cambios
#    user: bogota-aduana@colmas.com.co
    passwd:  tasas_cambios
#    passwd:  gbvFR5
    port: 25
#    public_ip: 200.14.235.62

  ldap:
    host: 10.192.1.15
    user: abotero
    passwd: krxo4578


#archivos de falabella
  falabella:
#    input:  /home/falabella/OUT  
#    input_processed:  /home/falabella/OUT/processed
    output:  /home/falabella/IN    
    input: c:\fala\
    input_processed: c:\fala\procesados\

 