# default values
all:
  digitalFile:
    root:  /srv/www/digitalFile/   

  sourceCode:
    plugins:  /srv/www/colsys_sf3/plugins/
    lib:  /srv/www/colsys_sf3/lib/

  branding:
    template: coltrans
    template4: consolcargo
    url: www.coltrans.com.co
    name: Coltrans S.A.S. - Colmas S.A.S.
    name1: Coltrans S.A.S.
    name2: Colmas S.A.S.
    from: serclientebog@coltrans.com.co
    idempresa: 800024075

  smtp:
    host: 172.16.1.18	
    host2: smtp-relay.gmail.com
    host3: smtp-relay.gmail.com
#    host3: consolcargo-com.mail.protection.outlook.com

    port: 25
    security: null   

#    debugAddress: alramirez@coltrans.com.co

#     GOOGLE
#    host: smtp.gmail.com
#    port: 465
#    security: ssl
#    user: maquinche@coltrans.co
#    passwd:  80166236


  ldap:
#    host: 172.16.1.22
    host: 10.192.1.26
    auth_enabled: true
#    user: colsys
#    passwd: $tlco5903Am

  memcache:
    host: 172.16.1.13
    port: 11211
    prefix: colsess

  session:
    maxinactive: 1800
  ip:
    trusted: 127.0.0.1 10.192.1 10.192.2

 #archivos de falabella
  falabella:
    input:  /home/falabella/OUT
    input_processed:  /home/falabella/OUT/processed
    output:  /home/falabella/IN    

    input_adu:  /home/falafact/OUT
    input_processed_adu:  /home/falafact/OUT/processed
    output_adu:  /home/falafact/IN

 #archivos de clariant
  clariant:
    input:  /home/clariant/OUT
    input_processed:  /home/clariant/OUT/processed
    output:  /home/clariant/IN


  gestDocumental:
    noAuth: KBaseWeb, KBase

  soap:
    secret: srTYudsa%&7dsa!Por#az+zX985>Fm
    adminUsers:
      updateUser: false
      wsdl_uri: https://www.colsys.com.co/ws/users/usersWS?wsdl

    gincomex:
      url: http://www.gincomex.biz/pruebas/webservices/servicio.php
      pass: HJDSJHSDUU3313JKIAASSJU12

    siigo:
      wsdl_uri: http://10.192.1.90:8000/w/WebService1.asmx?wsdl

    open:
      wsdl_uri: https://www.colsys.com.co/ws/colsys/InformeOpenWS?wsdl

  sinteParams:
    url: http://WS_LOCALCHECK.SINTE.CO:8081
    username: FANNY.GUTIERREZ
    password: fanny@201610
    percent: 90
