prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~
cli:
  controller:
    class: sfConsoleController
  request:
    class: sfConsoleRequest
  response:
    class: sfConsoleResponse

test:
  storage:
    class: sfSessionTestStorage

all:
#  controller:
#    class: sfFrontWebController
#
#  request:
#    class: sfWebRequest
#
#  response:
#    class: sfWebResponse
#
#  user:
#    class: myUser
#
  storage:
    class: sfSessionStorage
    param:
      session_name: colsys
  
#    class: mySessionStorage
#    param:
#      db_table:    session_storage              # Name of the table storing the sessions
#      database:    session               # Name of the database connection to use
      # Optional parameters
#      db_id_col:   sess_id              # Name of the column storing the session id
#      db_data_col: sess_data            # Name of the column storing the session data
#      db_time_col: sess_time            # Name of the column storing the session timestamp

#
#  view_cache:
#    class: sfFileCache
#    param:
#      automatic_cleaning_factor: 0
#      prefix:                    %SF_APP_DIR%
#      cache_dir:                %SF_TEMPLATE_CACHE_DIR%
