prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~
cli:
  controller:
    class: sfConsoleController
  request:
    class: sfConsoleRequest
  response:
    class: sfConsoleResponse

test:
  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  storage:
    class: sfSessionTestStorage

all:
#  controller:
#    class: sfFrontWebController
#
#  request:
#    class: sfWebRequest
#
#  response:
#    class: sfWebResponse
#
#  user:
#    class: myUser
#
#  storage:
#    class: sfSessionStorage
#    param:
#      session_name: colsys  

  storage:
    class: mySessionStorage
    param:
      session_name: colsys
      db_table:     control.tb_sessions
      database:     propel
      db_id_col:    sess_id
      db_data_col:  sess_data
      db_time_col:  sess_time
      db_maxinactive_col:  max_inactive

#
#  view_cache:
#    class: sfFileCache
#    param:
#      automatic_cleaning_factor: 0
#      prefix:                    %SF_APP_DIR%
#      cache_dir:                %SF_TEMPLATE_CACHE_DIR%
