rendering: ~
security:  ~

loginValidation:                 # Filters need a unique name
  class: loginValidationFilter
  param:
    cookie_name: coltranscookie

localeValidation:                 # Filters need a unique name
  class: localeFilter
  param:
    culture: es_ES	

cache:     ~
common:    ~


execution: ~


    

