rendering: ~
security:  ~

loginValidation:                 # Filters need a unique name
  class: loginValidationFilter
  param:
    cookie_name: coltranscookie

	
cache:     ~
common:    ~


execution: ~


    

