concepto:
  class: sfPropelRouteCollection
  options:
    model:               Concepto
    module:              conceptos
    prefix_path:         conceptos
    column:              ca_idconcepto
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
  
article_by_title:
  url:    expo/:reporteNegocioImprimir/:reporteId/:title.pdf
  param:  { module: expo, action: reporteNegocioImprimir }
  