default:
  http_metas:
    content-type: text/html; charset=iso-8859-1 

  metas:
    title:        Sistema de informacion - Coltrans S.A.
    robots:       index, follow
    description:  Sistema integrado de informacion Coltrans S.A., Colmas Ltda.
    keywords:     symfony, project
    language:     en	

  stylesheets:    [coltrans, print: { media: print }, yui/calendar/calendar, tooltips/tooltips, ext/css/ext-all, ext/css/xtheme-gray.css, menu/menu]

  javascripts:    [comunes, yui/yahoo/yahoo, yui/event/event, yui/dom/dom, yui/calendar/calendar, ext/adapter/ext/ext-base, ext/ext-all-debug, menu/menu]

  has_layout:     on
  layout:         layout
