<?php

/**
 * Ids
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
class Ids extends BaseIds
{
    const FOLDER = "ids";

    public function __toString(){
        return $this->getcaNombre();
    }
    /*
    *
    */
    public function getSucursalPrincipal( ){        
        return Doctrine::getTable("IdsSucursal")
                         ->createQuery("s")
                         ->where("s.ca_principal = ?", true)
                         ->addWhere("s.ca_id = ? ", $this->getCaId())
                         ->fetchOne();
    }

    /*
    *
    */
    public function getDocumento( $idtipo ){        
        return Doctrine::getTable("IdsDocumento")
                ->createQuery("d")
                ->where("d.ca_idtipo = ?",$idtipo )
                ->where("d.ca_id = ?",$this->getCaId() )
                ->addOrderBy("d.ca_iddocumento")
                ->fetchOne();

    }
}