<?php

/**
 * IdsContacto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
class IdsContacto extends BaseIdsContacto {

    public function getNombre() {
        return ucwords(strtolower($this->getCaNombres() . " " . $this->getCaPapellido() . " " . $this->getCaSapellido()));
    }

    public function getCargo() {
        return ucwords(strtolower($this->getCaCargo()));
    }

    public function getDepartamento() {
        return ucwords(strtolower($this->getCaDepartamento()));
    }

    public function getCodigoarea() {
        $codigo = $this->getCaCodigoarea();
        if ($codigo) {
            return intval($codigo);
        } else {
            return $this->getIdsSucursal()->getCiudad()->getCodigoarea();
        }
    }

    public function getConsultaListas($tipoConsulta) {
        $username = sfConfig::get("app_sinteParams_username");
        $password = sfConfig::get("app_sinteParams_password");
        $percent = sfConfig::get("app_sinteParams_percent");

        ProjectConfiguration::registerZend();

        $client = new Zend_Http_Client();

        $uri = "http://app.sinte.co:16080/WS_COLTRANS/webresources/listas/consultar";
        $client->setUri($uri);

        $client->setAuth($username, $password, Zend_Http_Client::AUTH_BASIC);

        $client->setParameterGet('tipo_consulta', $tipoConsulta);
        $identificacion = $this->getCaIdentificacion();
        $nombre_completo = trim($this->getCaNombres())." ".trim($this->getCaPapellido()).(($this->getCaSapellido())?$this->getCaSapellido():"");
        if ($tipoConsulta == "DOCUMENTO") {
            $client->setParameterGet('parametro', $this->getCaIdentificacion());
        } else {
            $client->setParameterGet('parametro', $nombre_completo);
            $client->setParameterGet('pcoincidencia', $percent);
        }
        $result = $client->request(Zend_Http_Client::GET);

        $json_response = json_decode($result->getBody());

        $consulta = new IdsRestrictivas();
        $consulta->setCaId($this->getIdsSucursal()->getIds()->getCaId());
        $consulta->setCaTipoConsulta($tipoConsulta);
        $consulta->setCaIdrespuesta($json_response->id);
        $consulta->setCaRespuesta(($json_response->respuesta) ? $json_response->respuesta : null);
        $consulta->setCaFchconsultado($json_response->fecha);
        $consulta->save();
        if ($json_response->respuesta) {        // Si el Nit o Razón Social se encuentra reportado
            $contentHTML = "<br /><br />
            ***** ALERTA *****
            <br />
            La consulta en Listas Restrictivas generó el siguiente resultado:<br />
            <table>
                    <tr>
                        <td><strong>Nit:</strong></td><td>" . $identificacion . "</td>
                    </tr>
                    <tr>
                        <td><strong>Nombre:</strong></td><td>" . $nombre_completo . "</td>
                    </tr>
                    <tr>
                        <td colspan=\"2\">$nbsp</td>
                    </tr>
                    <tr>
                        <td><strong>Tipo Consulta:</strong></td><td>$tipoConsulta</td>
                    </tr>
                    <tr>
                        <td><strong>Resultado:</strong></td><td>$json_response->respuesta</td>
                    </tr>
                    <tr>
                        <td><strong>Fecha:</strong></td><td>$json_response->fecha</td>
                    </tr>
            </table>
            <br />
            Agradecemos tomar las acciones correspondientes e informar a los interesados.";

            $parametro = Doctrine::getTable("Parametro")->find(array("CU267", 1, "defaultEmails"));
            if (stripos($parametro->getCaValor2(), ',') !== false) {
                $defaultEmail = explode(",", $parametro->getCaValor2());
            } else {
                $defaultEmail = array($parametro->getCaValor2());
            }
            $parametro = Doctrine::getTable("Parametro")->find(array("CU267", 2, "ccEmails"));
            if (stripos($parametro->getCaValor2(), ',') !== false) {
                $ccEmails = explode(",", $parametro->getCaValor2());
            } else {
                $ccEmails = array($parametro->getCaValor2());
            }

            $email = new Email();
            $email->setCaUsuenvio("Administrador");
            $email->setCaTipo("ConsultaSinte");
            $email->setCaFrom("no-reply@coltrans.com.co");
            $email->setCaFromname("Colsys Notificaciones");
            reset($defaultEmail);
            while (list ($clave, $val) = each($defaultEmail)) {
                $email->addTo($val);
            }
            reset($ccEmails);
            while (list ($clave, $val) = each($ccEmails)) {
                $email->addCc($val);
            }
            $email->setCaSubject("ALERTA! Resultado en Listas Restrictivas " . $nombre_completo . " Id: " . $identificacion);
            $email->setCaBodyhtml($contentHTML);
            $email->setCaBody($contentPlain);
            $email->save();
        }
        return $consulta;
    }

}
