# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow
  #stylesheets:    [intranet.css, blog, /js/ext4/resources/css/ext-all-neptune.css, font-awesome-4.3.0/css/font-awesome.min.css, jquery/jquery-ui.min.css, jquery/jquery-ui.structure.min.css]
  stylesheets:    [intranet.css, blog, /js/ext5/packages/ext-theme-crisp/build/resources/ext-theme-crisp-all-debug.css, font-awesome-4.3.0/css/font-awesome.min.css, jquery/jquery-ui.min.css, jquery/jquery-ui.structure.min.css]

  #javascripts:    [ext4/ext-all.js, ext4/ux/multiupload/swfobject.js, comunes.js, jquery/jquery.js, jquery/jquery.tooltip.js, jquery/jquery.dimensions.js]
  javascripts:    [ext5/ext-all.js, comunes.js, jquery/jquery.js, jquery/jquery.dimensions.js]

  has_layout:     true
  layout:         layout