<?php

/**
 * PricFlete
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
class PricFlete extends BasePricFlete
{
    /*
	* Retorna el estilo que se debe aplicar a las filas de acuerdo al
	* estado que se encuentre
	* Author: Andres Botero
	*/
	public function getEstilo(){
		switch( $this->getCaEstado() ){
			case 1:
				return "yellow";
				break;
			case 2:
				return "pink";
				break;
                        case 3:
				return "green";
				break;
			default:
				return "";
				break;
		}
	}

	/*
	* Coloca el estilo que se debe aplicar a las filas de acuerdoa al estado que se encuentre
	* Author: Andres Botero
	*/
	public function setEstilo( $estilo ){
		switch( $estilo ){
			case "yellow":
				$this->setCaEstado(1);
				break;
			case "pink":
				$this->setCaEstado(2);
				break;
                        case "green":
				$this->setCaEstado(3);
				break;
			default:
				$this->setCaEstado(null);
				break;
		}
	}


    /*
	* Guarda el recargo y determina el # de actualizacion
	* Author: Andres Botero
	*/
    /*public function save( Doctrine_Connection $con=null){


        if( !$con ){
            $con = $this->getTable()->getConnection();
}
        $con->beginTransaction();

        parent::save($con);

        $sql = "SELECT currval('pric.tb_fletes_id') as next";

       
        $stmt = $con->execute($sql);
        $row = $stmt->fetch();
        $this->setCaConsecutivo($row['next']);

        $con->commit();

    }*/

}
