
HdeskGroup:
  generatePath: helpdesk
  tableName: helpdesk.tb_groups
  columns:
    ca_idgroup:
      type: integer
      primary: true
      autoincrement: true
    ca_iddepartament: integer
    ca_name: string
    ca_maxresponsetime: integer
  relations:
    Departamento:
      local: ca_iddepartament
      foreign: ca_iddepartament
      type: one
    HdeskTicket:
      local: ca_idgroup
      foreign: ca_idgroup
      type: many
    Departamento:
      local: ca_iddepartament
      foreign: ca_iddepartamento
      type: one
    
HdeskTicket:
  generatePath: helpdesk
  tableName: helpdesk.tb_tickets
  columns:
    ca_idticket:
      type: integer
      primary: true
      autoincrement: true
    ca_idgroup: integer
    ca_idproject: integer
    ca_login: string(15)
    ca_title: string(255)
    ca_text: string
    ca_priority: string(8)
    ca_opened: timestamp
    ca_type: string(20)
    ca_assignedto: string(15)
    ca_action: string(15)
    ca_responsetime: timestamp
    ca_idtarea: integer
    ca_idseguimiento: integer
    ca_order: integer
    ca_estimatedhours: integer
    ca_percentage: integer
  relations:
    HdeskResponse:
      local: ca_idticket
      foreign: ca_idticket
      type: many
    HdeskGroup:
      local: ca_idgroup
      foreign: ca_idgroup
      type: one
    HdeskProject:
      local: ca_idproject
      foreign: ca_idproject
      type: one    
    HdeskTicketUser:
      local: ca_idticket
      foreign: ca_idticket
      type: many
    NotTarea:
      local: ca_idtarea
      foreign: ca_idtarea
      type: one
    Usuario:
      local: ca_login
      foreign: ca_login
      type: one


HdeskResponse:
  generatePath: helpdesk
  tableName: helpdesk.tb_responses
  columns:
    ca_idresponse:
      type: integer
      primary: true
      autoincrement: true
    ca_idticket: integer
    ca_login: string(15)
    ca_createdat: timestamp
    ca_text: string
  relations:
    HdeskTicket:
      local: ca_idticket
      foreign: ca_idticket
      type: one
    Usuario:
      local: ca_login
      foreign: ca_login
      type: one


HdeskProject:
  generatePath: helpdesk
  tableName: helpdesk.tb_projects
  columns:
    ca_idproject:
      type: integer
      primary: true
      autoincrement: true
    ca_idgroup: integer
    ca_name: string
    ca_description: string
    ca_active: boolean
  relations:
    HdeskGroup:
      local: ca_idgroup
      foreign: ca_idgroup
      type: many


HdeskUserGroup:
  generatePath: helpdesk
  tableName: helpdesk.tb_usersgroups
  columns:
    ca_idgroup:
      type: integer
      primary: true      
    ca_login:
      type: string(20)
      primary: true      
  relations:
    HdeskGroup:
      local: ca_idgroup
      foreign: ca_idgroup
      type: one
    Usuario:
      local: ca_login
      foreign: ca_login
      type: one

HdeskTicketUser:
  generatePath: helpdesk
  tableName: helpdesk.tb_tickets_usuarios
  columns:
    ca_idticket:
      type: integer
      primary: true
    ca_login:
      type: string(20)
      primary: true
  relations:
    HdeskTicket:
      local: ca_idticket
      foreign: ca_idticket
      type: one
    Usuario:
      local: ca_login
      foreign: ca_login
      type: one

HdeskKBase:
  generatePath: helpdesk
  tableName: helpdesk.tb_kbase
  columns:
    ca_idkbase:
      type: integer
      primary: true
      autoincrement: true
    ca_idcategory: string
    ca_login: string
    ca_createdat: timestamp
    ca_text: string
    ca_title: string
    ca_private: boolean
  relations:
    HdeskKBaseCategory:
      local: ca_idcategory
      foreign: ca_idcategory
      type: one


HdeskKBaseCategory:
  generatePath: helpdesk
  tableName: helpdesk.tb_kbasecategory
  columns:
    ca_idcategory:
      type: integer
      primary: true
      autoincrement: true
    ca_parent: integer
    ca_name: string
  relations:
    HdeskKBase:
      local: ca_idcategory
      foreign: ca_idcategory
      type: many

