HdeskGroup:
  options:
    symfony:
      form: false
      filter: false
  generatePath: helpdesk
  tableName: helpdesk.tb_groups
  columns:
    ca_idgroup:
      type: integer
      primary: true
      autoincrement: true
    ca_iddepartament: integer
    ca_name: string
    ca_maxresponsetime: integer
    ca_idtipo: integer
    ca_activo: boolean
    ca_interno: boolean
  relations:    
    HdeskTicket:
      local: ca_idgroup
      foreign: ca_idgroup
      type: many
    HdeskProject:
      local: ca_idgroup
      foreign: ca_idgroup
      type: many
      orderBy: ca_name ASC
    HdeskUserGroup:
      local: ca_idgroup
      foreign: ca_idgroup
      type: many
    Departamento:
      local: ca_iddepartament
      foreign: ca_iddepartamento      
      type: one
    SurvTipo:
      local: ca_idtipo
      foreign: ca_idtipo
      type: one
    
HdeskTicket:
  options:
    symfony:
      form: false
      filter: false
  generatePath: helpdesk
  tableName: helpdesk.tb_tickets
  columns:
    ca_idticket:
      type: integer
      primary: true
      autoincrement: true
    ca_idgroup: integer
    ca_idproject: integer
    ca_login: string(15)
    ca_title: string(255)
    ca_text: string
    ca_priority: string(8)
    ca_opened: timestamp
    ca_type: string(20)
    ca_assignedto: string(15)
    ca_action: string(15)
    ca_responsetime: timestamp
    ca_idtarea: integer
    ca_idseguimiento: integer
    ca_order: integer
    ca_estimatedhours: integer
    ca_percentage: integer
    ca_idmilestone: integer
    ca_reportedby: string(20)    
    ca_idevaluacion: integer
    ca_starred: boolean
    ca_closedat: timestamp
    ca_closedby: string(15)
    ca_status: integer
    ca_idactivo: integer
    ca_idempresa: integer
    ca_estimated: date
    ca_parent: integer
  relations:    
    HdeskGroup:
      local: ca_idgroup
      foreign: ca_idgroup
      type: one
    HdeskResponse:
      local: ca_idticket
      foreign: ca_idticket
      type: many
    HdeskProject:
      local: ca_idproject
      foreign: ca_idproject
      type: one    
    HdeskTicketUser:
      local: ca_idticket
      foreign: ca_idticket
      type: many
    HdeskAuditDocuments:
      local: ca_idticket
      foreign: ca_idticket
      type: many
    HdeskUserGroup:
      local: ca_idgroup
      foreign: ca_idgroup
      type: many
    HdeskMilestone:
      local: ca_idmilestone
      foreign: ca_idmilestone
      type: one
    HdeskTask:
      local: ca_idticket
      foreign: ca_idticket
      type: many
    NotTarea:
      local: ca_idtarea
      foreign: ca_idtarea
      type: one
    Usuario:
      local: ca_login
      foreign: ca_login
      type: one
    ReportedBy:
      local: ca_login
      foreign: ca_login
      type: one
      class: Usuario
    AssignedTo:
      local: ca_assignedto
      foreign: ca_login
      type: one
      class: Usuario
    ClosedBy:
      local: ca_closedby
      foreign: ca_login
      type: one
      class: Usuario
    SurvEvaluacion:
      local: ca_idevaluacion
      foreign: ca_idevaluacion
    InvActivo:
      local: ca_idactivo
      foreign: ca_idactivo
      type: one
    Empresa:
      class: Empresa
      local: ca_idempresa
      foreign: ca_idempresa
      type: one
    Email:
      local: ca_idticket
      foreign: ca_idcaso
      type: one
    Parent:
      local: ca_parent
      foreign: ca_idticket
      type: one
      class: HdeskTicket
    Children:
      local: ca_idticket
      foreign: ca_parent
      type: many
      class: HdeskTicket


HdeskResponse:
  options:
    symfony:
      form: false
      filter: false
  generatePath: helpdesk
  tableName: helpdesk.tb_responses
  columns:
    ca_idresponse:
      type: integer
      primary: true
      autoincrement: true
    ca_idticket: integer
    ca_responseto: integer
    ca_text: string
    ca_login: string(15)
    ca_createdat: timestamp
    ca_idissue: integer
    ca_idtarea: integer
  relations:    
    Usuario:
      local: ca_login
      foreign: ca_login
      type: one
    KBIssue:
      local: ca_idissue
      foreign: ca_idissue
      type: one
    Response:
      local: ca_idresponse
      foreign: ca_responseto
      type: many
      class: HdeskResponse
      orderBy: ca_createdat ASC
    NotTarea:
      local: ca_idtarea
      foreign: ca_idtarea
      type: one

HdeskProject:
  options:
    symfony:
      form: false
      filter: false
  generatePath: helpdesk
  tableName: helpdesk.tb_projects
  columns:
    ca_idproject:
      type: integer
      primary: true
      autoincrement: true
    ca_idgroup: integer
    ca_name: string
    ca_description: string
    ca_active: boolean
    ca_manager: string
  relations:
    HdeskGroup:
      local: ca_idgroup
      foreign: ca_idgroup
      type: many
    HdeskMilestone:
      local: ca_idgroup
      foreign: ca_idgroup
      type: many


HdeskUserGroup:
  options:
    symfony:
      form: false
      filter: false
  generatePath: helpdesk
  tableName: helpdesk.tb_usersgroups
  columns:
    ca_idgroup:
      type: integer
      primary: true      
    ca_login:
      type: string(20)
      primary: true      
  relations:
    HdeskGroup:
      local: ca_idgroup
      foreign: ca_idgroup
      type: one
    Usuario:
      local: ca_login
      foreign: ca_login
      type: one

HdeskTicketUser:
  options:
    symfony:
      form: false
      filter: false
  generatePath: helpdesk
  tableName: helpdesk.tb_tickets_usuarios
  columns:
    ca_idticket:
      type: integer
      primary: true
    ca_login:
      type: string(20)
      primary: true
  relations:
    HdeskTicket:
      local: ca_idticket
      foreign: ca_idticket
      type: one
    Usuario:
      local: ca_login
      foreign: ca_login
      type: one

HdeskDepartamentClasification:
  options:
    symfony:
      form: false
      filter: false
  generatePath: helpdesk
  tableName: helpdesk.tb_departament_clasification
  columns:
    ca_iddepartament:
      type: integer
      primary: true
    ca_clasification:
      type: string
      primary: true
    ca_order: integer
  relations:
    Departamento:
      local: ca_iddepartament
      foreign: ca_iddepartamento
      type: one

HdeskMilestone:
  options:
    symfony:
      form: false
      filter: false
  generatePath: helpdesk
  tableName: helpdesk.tb_milestones
  columns:
    ca_idmilestone:
      type: integer
      primary: true
      autoincrement: true
    ca_idproject: integer
    ca_title: string(25)
    ca_text: string(255)
    ca_due: date
    ca_end: date
  relations:
    HdeskProject:
      local: ca_idproject
      foreign: ca_idproject
      type: one


HdeskAuditDocuments:
  options:
    symfony:
      form: false
      filter: false
  generatePath: helpdesk
  tableName: helpdesk.tb_auditdocs
  columns:
    ca_idauditdocs:
      type: integer
      primary: true
      autoincrement: true
    ca_idticket: integer
    ca_tipo_doc: string(25)
    ca_numero_doc: string(255)
    ca_recuperacion: decimal
    ca_perdida: decimal
    ca_observaciones: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
  relations:
    HdeskTicket:
      local: ca_idticket
      foreign: ca_idticket
      type: one
    Usuario:
      local: ca_assigned_to
      foreign: ca_assigned_to
      type: one
      
HdeskEstimations:
  options:
    symfony:
      form: false
      filter: false
  generatePath: helpdesk
  tableName: helpdesk.tb_estimations
  columns:
    ca_idstage:
      type: integer
      primary: true
      autoincrement: true
    ca_idticket: integer      
    ca_idresponse: integer
    ca_stage: string
    ca_detail: string
    ca_estimated: date
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
    ca_idtarea: integer
  relations:    
    HdeskResponse:
      local: ca_idresponse
      foreign: ca_idresponse
      type: one
    HdeskTicket:
      local: ca_idticket
      foreign: ca_idticket
      type: one