Idg:
  options:
    symfony:
      form: false
      filter: false
  generatePath: idg
  tableName: idg.tb_idg
  columns:
    ca_idg:
      type: integer
      primary: true
      autoincrement: true    
    ca_nombre: string(255)
    ca_iddepartamento: integer
    ca_tipo: string(12)
    ca_usucreado: string(20)
    ca_fchcreado: timestamp
    ca_usuactualizado: string(20)
    ca_fchactualizado: timestamp
    ca_impoexpo: string(15)
    ca_transporte: string(15)
    ca_sigla: string(3)
    ca_idproceso: integer
    ca_datos: string
    ca_activo: boolean
    ca_modalidad: string(15)
    ca_idempresa: integer
  relations:
    IdgConfig:
      local: ca_idg
      foreign: ca_idg
      type: many
    Departamento:
      local: ca_iddepartamento
      foreign: ca_iddepartamento
      type: one
    UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario
    UsuActualizado:
      local: ca_usuactualizado
      foreign: ca_login
      type: one
      class: Usuario
    IdgProcesos:
       local: ca_idproceso
       foreign: ca_idproceso
       type: one
    
IdgConfig:
  options:
    symfony:
      form: false
      filter: false
  generatePath: idg
  tableName: idg.tb_config
  columns:
    ca_idgconfig:
      type: integer
      primary: true
      autoincrement: true
    ca_idg: integer
    ca_idsucursal: string(3)
    ca_lim1: numeric
    ca_color1: string(10)
    ca_lim2: numeric
    ca_color2: string(10)
    ca_lim3: numeric
    ca_color3: string(10)
    ca_fchini: date
    ca_fchfin: date
    ca_tiempo: string(10)
    ca_usucreado: string(20)
    ca_fchcreado: timestamp
    ca_usuactualizado: string(20)
    ca_fchactualizado: timestamp
    ca_usueliminado: string(20)
    ca_fcheliminado: timestamp
  relations:
    Idg:
      local: ca_idg
      foreign: ca_idg
      type: one
    UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario
    UsuActualizado:
      local: ca_usuactualizado
      foreign: ca_login
      type: one
      class: Usuario
    Sucursal:
      local: ca_idsucursal
      foreign: ca_idsucursal
      type: one

IdgProcesos:
  options:
    symfony:
      form: false
      filter: false
  generatePath: idg
  tableName: idg.tb_procesos
  columns:
    ca_idproceso:
      type: integer
      primary: true
      autoincrement: true    
    ca_nombre: string(30)
    ca_iddepartamento: integer    
    ca_usuproceso: string(20)    
  relations:
    IdgRiesgos:
      local: ca_idproceso
      foreign: ca_idproceso
      type: many
    Departamento:
      local: ca_iddepartamento
      foreign: ca_iddepartamento
      type: one

IdgRiesgos:
  options:
    symfony:
      form: false
      filter: false
  generatePath: idg
  tableName: idg.tb_riesgos
  columns:
    ca_idriesgo:
      type: integer
      primary: true
      autoincrement: true
    ca_idproceso: 
      type: integer
      notnull: true
    ca_codigo: 
      type: string(10)
      notnull: true
    ca_riesgo: string
    ca_etapa: string
    ca_potenciador: string
    ca_controles: string    
    ca_ap: string
    ca_contingencia: string
    ca_usucreado: string(15)
    ca_fchcreado: timestamp
    ca_usuactualizado: string(15)
    ca_fchactualizado: timestamp
    ca_impresion: integer
    ca_laft: boolean
    ca_activo: boolean
  relations:
    IdgProcesos:
      local: ca_idproceso
      foreign: ca_idproceso
      type: one
    IdgFactor:
      local: ca_idriesgo
      foreign: ca_idriesgo
      type: many
    UsuCreado:
      class: Usuario
      local: ca_usucreado
      foreign: ca_login
      type: one
    UsuActualizado:
      class: Usuario
      local: ca_usuactualizado
      foreign: ca_login
      type: one

IdgValoracion:
  options:
    symfony:
      form: false
      filter: false
  generatePath: idg
  tableName: idg.tb_valoracion
  columns:
    ca_idvaloracion:
      type: integer
      primary: true
      autoincrement: true
    ca_idriesgo: integer
    ca_ano: integer    
    ca_operativo: integer
    ca_legal: integer
    ca_economico: integer
    ca_comercial: integer
    ca_peso: integer
    ca_usucreado: string(15)
    ca_fchcreado: timestamp
    ca_usuactualizado: string(15)
    ca_fchactualizado: timestamp
    ca_datos: jsonb
  relations:
    IdgRiesgos:
      local: ca_idriesgo
      foreign: ca_idriesgo
      type: one
    UsuCreado:
      class: Usuario
      local: ca_usucreado
      foreign: ca_login
      type: one
    UsuActualizado:
      class: Usuario
      local: ca_usuactualizado
      foreign: ca_login
      type: one
 
IdgEventos:
  options:
    symfony:
      form: false
      filter: false
  generatePath: idg
  tableName: idg.tb_eventos
  columns:
    ca_idevento:
      type: integer
      primary: true
      autoincrement: true
    ca_idriesgo: integer
    ca_idcausa: integer
    ca_fchevento: date
    ca_descripcion: string
    ca_tipo_doc: string
    ca_documento:  string
    ca_idcliente: integer
    ca_idsucursal: string
    ca_perdida_tot: decimal
    ca_perdida_ope: decimal
    ca_perdida_leg: decimal
    ca_perdida_eco: decimal
    ca_perdida_com: decimal
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
    ca_pa: string
  relations:
    IdgRiesgos:
      local: ca_idriesgo
      foreign: ca_idriesgo
      type: one
    IdgCausas:
      local: ca_idcausa
      foreign: ca_idcausa
      type: one    
    Cliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: one
    Sucursal:
      local: ca_idsucursal
      foreign: ca_idsucursal
      type: one
    UsuCreado:
      class: Usuario
      local: ca_usucreado
      foreign: ca_login
      type: one
    UsuActualizado:
      class: Usuario
      local: ca_usuactualizado
      foreign: ca_login
      type: one
    IdgEventoCausa:
      local: ca_idevento
      foreign: ca_idevento
      type: many
      
IdgCausas:
  options:
    symfony:
      form: false
      filter: false
  generatePath: idg
  tableName: idg.tb_causas
  columns:
    ca_idcausa:
      type: integer
      primary: true
      autoincrement: true
    ca_idriesgo: integer
    ca_causa: string
    ca_fchcreado: timestamp
    ca_usucreado: string(15)
    ca_fchactualizado: timestamp
    ca_usuactualizado: string(15)
    ca_nueva: boolean
    ca_orden: integer
  relations:
    IdgRiesgos:
      local: ca_idriesgo
      foreign: ca_idriesgo
      type: one
    UsuCreado:
      class: Usuario
      local: ca_usucreado
      foreign: ca_login
      type: one
    UsuActualizado:
      class: Usuario
      local: ca_usuactualizado
      foreign: ca_login
      type: one
      
IdgUsuProcesos:
  options:
    symfony:
      form: false
      filter: false
  generatePath: idg
  tableName: idg.tb_usuprocesos
  columns:
    ca_idproceso:
      type: integer
      primary: true
    ca_login:
      type: string
      primary: true  
  relations:
    IdgProcesos:
      local: ca_idproceso
      foreign: ca_idproceso
      type: one
    Usuario:
      local: ca_login
      foreign: ca_login
      type: one
      
IdgFactor:
  options:
    symfony:
      form: false
      filter: false
  generatePath: idg
  tableName: idg.tb_factores
  columns:    
    ca_idriesgo:
      type: integer
      primary: true
    ca_factor:
      type: string
      primary: true
  relations:
    IdgRiesgos:
      local: ca_idriesgo
      foreign: ca_idriesgo
      type: one    
      
IdgEventoCausa:
  options:
    symfony:
      form: false
      filter: false
  generatePath: idg
  tableName: idg.tb_eventos_causas
  columns:    
    ca_idevento:
      type: integer
      primary: true
    ca_idcausa:
      type: integer
      primary: true
  relations:
      IdgEventos:
        local: ca_idevento
        foreign: ca_idevento
        type: one
      IdgCausas:
        local: ca_idcausa
        foreign: ca_idcausa
        type: many  

IdgVersion:
  options:
    symfony:
      form: false
      filter: false
  generatePath: idg
  tableName: idg.tb_versiones
  columns:    
    ca_id:
      type: integer
      primary: true
    ca_version: integer
    ca_idproceso: integer
    ca_nombre: string
    ca_observaciones: text
    ca_fchcreado: timestamp
    ca_usucreado: string(15)
    ca_fcheliminado: timestamp
    ca_usueliminado: string(15)      
  relations:
      IdgProcesos:
        local: ca_idproceso
        foreign: ca_idproceso
        type: one
      UsuCreado:
        class: Usuario
        local: ca_usucreado
        foreign: ca_login
        type: one
      UsuEliminado:
        class: Usuario
        local: ca_usueliminado
        foreign: ca_login
        type: one

IdgArchivo:
  options:
    symfony:
      form: false
      filter: false
  generatePath: idg
  tableName: idg.tb_archivos
  columns:    
    ca_idarchivo:
      type: integer
      primary: true
    ca_idg: integer
    ca_ano: string
    ca_periodo: string
    ca_nombre: string
    ca_path: string
    ca_observaciones: text
    ca_fchcreado: timestamp
    ca_usucreado: string(15)
    ca_fchactualizado: timestamp
    ca_usuactualizado: string(15)
    ca_fcheliminado: timestamp
    ca_usueliminado: string(15)      
    ca_idsucursal: string(3)
  relations:
      Idg:
        local: ca_idg
        foreign: ca_idg
        type: one
      UsuCreado:
        class: Usuario
        local: ca_usucreado
        foreign: ca_login
        type: one
      UsuActualizado:
        class: Usuario
        local: ca_usuactualizado
        foreign: ca_login
        type: one
      UsuEliminado:
        class: Usuario
        local: ca_usueliminado
        foreign: ca_login
        type: one
      Sucursal:
        local: ca_idsucursal
        foreign: ca_idsucursal
        type: one        