Idg:
  options:
    symfony:
      form: false
      filter: false
  generatePath: idg
  tableName: idg.tb_idg
  columns:
    ca_idg:
      type: integer
      primary: true
      autoincrement: true    
    ca_nombre: string(255)
    ca_iddepartamento: integer
    ca_tipo: string(12)
    ca_usucreado: string(20)
    ca_fchcreado: timestamp
    ca_usuactualizado: string(20)
    ca_fchactualizado: timestamp
  relations:
    IdgConfig:
      local: ca_idg
      foreign: ca_idg
      type: many
    Departamento:
      local: ca_iddepartamento
      foreign: ca_iddepartamento
      type: one
    UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario
    UsuActualizado:
      local: ca_usuactualizado
      foreign: ca_login
      type: one
      class: Usuario
    
IdgConfig:
  options:
    symfony:
      form: false
      filter: false
  generatePath: idg
  tableName: idg.tb_config
  columns:
    ca_idgconfig:
      type: integer
      primary: true
      autoincrement: true
    ca_idg: integer
    ca_idsucursal: string(3)
    ca_lim1: numeric
    ca_color1: string(10)
    ca_lim2: numeric
    ca_color2: string(10)
    ca_lim3: numeric
    ca_color3: string(10)
    ca_fchini: date
    ca_fchfin: date
    ca_tiempo: string(10)
    ca_usucreado: string(20)
    ca_fchcreado: timestamp
    ca_usuactualizado: string(20)
    ca_fchactualizado: timestamp
  relations:
    Idg:
      local: ca_idg
      foreign: ca_idg
      type: one
    UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario
    UsuActualizado:
      local: ca_usuactualizado
      foreign: ca_login
      type: one
      class: Usuario
    Sucursal:
      local: ca_idsucursal
      foreign: ca_idsucursal
      type: one

IdgProcesos:
  options:
    symfony:
      form: false
      filter: false
  generatePath: idg
  tableName: idg.tb_procesos
  columns:
    ca_idproceso:
      type: integer
      primary: true
      autoincrement: true    
    ca_nombre: string(30)
    ca_iddepartamento: integer    
    ca_usuproceso: string(20)    
  relations:
    IdgRiesgos:
      local: ca_idproceso
      foreign: ca_idproceso
      type: many


IdgRiesgos:
  options:
    symfony:
      form: false
      filter: false
  generatePath: idg
  tableName: idg.tb_riesgos
  columns:
    ca_idriesgo:
      type: integer
      primary: true
      autoincrement: true
    ca_idproceso: integer
    ca_codigo: string(10)    
    ca_descripcion: string
    ca_causas: string
    ca_controles: string
    ca_operativo: integer
    ca_legal: integer
    ca_economico: integer
    ca_comercial: integer
    ca_peso: integer
    ca_ap: string
    ca_contingencia: string
  relations:
    IdgProcesos:
      local: ca_idproceso
      foreign: ca_idproceso
      type: one
