Ids:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ids
  tableName: ids.tb_ids
  columns:
    ca_id:
      type: integer
      primary: true
      autoincrement: true
    ca_dv: integer
    ca_idalterno: string(20)
    ca_tipoidentificacion: integer
    ca_idgrupo: integer
    ca_nombre: string(255)
    ca_website: string(60)
    ca_actividad: string
    ca_sectoreco: string(30)
    ca_usucreado: string(20)
    ca_fchcreado: timestamp
    ca_usuactualizado: string(20)
    ca_fchactualizado: timestamp    
  relations:
    IdsSucursal:
      local: ca_id
      foreign: ca_id
      type: many
    IdsAgente:
      local: ca_id
      foreign: ca_idagente
      type: one
    IdsProveedor:
      local: ca_id
      foreign: ca_idproveedor
      type: one
    IdsCliente:
      local: ca_id
      foreign: ca_idcliente
      type: one
    IdsEmpresa:
      local: ca_id
      foreign: ca_idempresa
      type: one
    IdsDocumento:
       local: ca_id
       foreign: ca_id
       type: many
    IdsEvento:
      local: ca_id
      foreign: ca_id
      type: many
    IdsSeguimiento:
      local: ca_id
      foreign: ca_id
      type: many
    IdsTipoIdentificacion:
      local: ca_tipoidentificacion
      foreign: ca_tipoidentificacion
      type: one
    
IdsTipoIdentificacion:  
  options:
    symfony:
      form: false
      filter: false
  generatePath: ids
  tableName: ids.tb_tiposidentificacion
  columns:
    ca_tipoidentificacion:
      type: integer
      primary: true
      autoincrement: true
    ca_nombre: string
    ca_idtrafico: string
  relations:
    Trafico:
      local: ca_idtrafico
      foreign: ca_idtrafico
      type: one
      
IdsSucursal:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ids
  tableName: ids.tb_sucursales
  columns:
    ca_idsucursal:
      type: integer
      primary: true
      autoincrement: true
    ca_id: integer
    ca_principal: boolean
    ca_direccion: string(100)
    ca_oficina: string(15)
    ca_torre: string(15)
    ca_bloque: string(15)
    ca_interior: string(15)
    ca_localidad: string(20)
    ca_complemento: string(50)
    ca_telefonos: string(30)
    ca_fax: string(30)
    ca_idciudad: string(8)
    ca_zipcode: string(20)
    ca_usucreado: string(20)
    ca_fchcreado: timestamp
    ca_usuactualizado: string(20)
    ca_fchactualizado: timestamp
  relations:
    Ids:
      local: ca_id
      foreign: ca_id
      type: one
    Ciudad:
      local: ca_idciudad
      foreign: ca_idciudad
      type: one

IdsContacto:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ids
  tableName: ids.tb_contactos
  columns:
    ca_idcontacto:
      type: integer
      primary: true
      autoincrement: true
    ca_idsucursal: integer
    ca_nombres: string(60)
    ca_papellido: string(60)
    ca_sapellido: string(60)
    ca_saludo: string(15)
    ca_direccion: string(100)
    ca_telefonos: string(30)
    ca_fax: string(30)
    ca_email: string(50)
    ca_impoexpo: string
    ca_transporte: string
    ca_cargo: string(20)
    ca_departamento: string(30)
    ca_observaciones: string(100)
    ca_sugerido: boolean
    ca_visibilidad: integer
    ca_activo: boolean
    ca_notificar_vencimientos: boolean
    ca_codigoarea: string
    ca_skype: string
    ca_celular: string
    ca_usucreado: string(20)
    ca_fchcreado: timestamp
    ca_usuactualizado: string(20)
    ca_fchactualizado: timestamp
    ca_fcheliminado: timestamp
    ca_usueliminado: string(20)
  relations:
    IdsSucursal:
      local: ca_idsucursal
      foreign: ca_idsucursal
      type: one
      
IdsAgente:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ids
  tableName: ids.tb_agentes
  columns:
    ca_idagente:
      type: integer
      primary: true
    ca_tipo: string
    ca_activo: boolean
    ca_tplogistics: boolean
    ca_infosec: string
  relations:
    Ids:
      local: ca_idagente
      foreign: ca_id
      type: one
    IdsTipo:
      local: ca_tipo
      foreign: ca_tipo
      type: one

IdsProveedor:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ids
  tableName: ids.tb_proveedores
  columns:
    ca_idproveedor:
      type: integer
      primary: true
    ca_tipo: string(5)    
    ca_critico: boolean
    ca_controladoporsig: boolean
    ca_fchaprobado: timestamp
    ca_usuaprobado: string(20)
    ca_sigla: string(20)
    ca_transporte: string(10)
    ca_empresa: string    
    ca_activo_impo: boolean
    ca_activo_expo: boolean
    ca_contrato_comodato: boolean
  relations:
    Ids:
      local: ca_idproveedor
      foreign: ca_id
      type: one
    IdsTipo:
      local: ca_tipo
      foreign: ca_tipo
      type: one

IdsEmpresa:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ids
  tableName: ids.tb_empresas
  columns:
    ca_idempresa:
      type: integer
      primary: true
    ca_sigla: string(20)
  relations:
    Ids:
      local: ca_idempresa
      foreign: ca_id
      type: one


IdsTipo:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ids
  tableName: ids.tb_tipos
  columns:
    ca_tipo:
      type: string(3)
      primary: true
    ca_nombre: string(50)
    ca_aplicacion: string(50)
  relations:
    IdsAgente:
      local: ca_tipo
      foreign: ca_tipo
      type: one
    IdsProveedor:
      local: ca_tipo
      foreign: ca_tipo
      type: one

IdsDocumento:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ids
  tableName: ids.tb_documentos
  columns:
    ca_iddocumento:
      type: integer
      primary: true
      autoincrement: true
    ca_id: integer
    ca_idtipo: integer
    ca_ubicacion: string(255)
    ca_observaciones: string(255)
    ca_fchinicio: date
    ca_fchvencimiento: date
    ca_usucreado: string(20)
    ca_fchcreado: timestamp
  relations:
    Ids:
      local: ca_id
      foreign: ca_id
      type: one
    IdsTipodocumento:
      local: ca_idtipo
      foreign: ca_idtipo
      type: one

IdsTipoDocumento:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ids
  tableName: ids.tb_tipodocumentos
  columns:
    ca_idtipo:
      type: integer
      primary: true
      autoincrement: true
    ca_tipo: string(60)
    ca_equivalentea: integer
    ca_vigencia: string(15)
    ca_observaciones: string(15)    
    ca_usucreado: string(20)
    ca_fchcreado: timestamp
    ca_usuactualizado: string(20)
    ca_fchactualizado: timestamp
  relations:
    IdsDocumento:
      local: ca_idtipo
      foreign: ca_idtipo
      type: many

IdsDocumentoPorTipo:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ids
  tableName: ids.tb_documentosxtipo
  columns:
    ca_iddocumentosxtipo:
      type: integer
      primary: true
    ca_idtipo: integer
    ca_tipo: string
    ca_controladoxsig: boolean
    ca_impoexpo: string
    ca_transporte: string
    ca_solo_si_aplica: boolean
  relations:
    IdsTipoDocumento:
      local: ca_idtipo
      foreign: ca_idtipo
      type: one
    IdsTipo:
      local: ca_tipo
      foreign: ca_tipo
      type: one



IdsEvaluacion:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ids
  tableName: ids.tb_evaluacion
  columns:
    ca_idevaluacion:
      type: integer
      primary: true
      autoincrement: true
    ca_id: integer
    ca_tipo: string(15)
    ca_concepto: string(15)
    ca_ano: integer
    ca_periodo: integer
    ca_fchevaluacion: date
    ca_usucreado: string(20)
    ca_fchcreado: timestamp
    ca_usuactualizado: string(20)
    ca_fchactualizado: timestamp
  relations:
    Ids:
      local: ca_id
      foreign: ca_id
      type: one
    IdsEvaluacionxCriterio:
      local: ca_idevaluacion
      foreign: ca_idevaluacion
      type: many
      


IdsEvaluacionxCriterio:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ids
  tableName: ids.tb_evaluacionxcriterio
  columns:
    ca_idevaluacion:
      type: integer
      primary: true
    ca_idcriterio:
      type: integer
      primary: true
    ca_valor: decimal
    ca_ponderacion: decimal
    ca_observaciones: string(255)
    ca_usucreado: string(20)
    ca_fchcreado: timestamp
    ca_usuactualizado: string(20)
    ca_fchactualizado: timestamp
  relations:
    IdsEvaluacion:
      local: ca_idevaluacion
      foreign: ca_idevaluacion
      type: one
    IdsCriterio:
      local: ca_idcriterio
      foreign: ca_idcriterio
      type: one
    

IdsCriterio:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ids
  tableName: ids.tb_criterios
  columns:
    ca_idcriterio:
      type: integer
      primary: true
      autoincrement: true
    ca_tipo: string(3)
    ca_criterio: string(60)
    ca_ponderacion: integer(4)
    ca_tipocriterio: string(30)
    ca_activo: boolean
    ca_impoexpo: string
    ca_transporte: string
    ca_usucreado: string(20)
    ca_fchcreado: timestamp
    ca_usuactualizado: string(20)
    ca_fchactualizado: timestamp
  relations:
    IdsEvaluacionxCriterio:
      local: ca_idcriterio
      foreign: ca_idcriterio
      type: many
    IdsEvento:
      local: ca_idcriterio
      foreign: ca_idcriterio
      type: many
    IdsTipo:
      local: ca_tipo
      foreign: ca_tipo
      type: one

IdsEvento:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ids
  tableName: ids.tb_eventos
  columns:
    ca_idevento:
      type: integer
      primary: true
      autoincrement: true
    ca_id: integer
    ca_evento: string
    ca_referencia: string(16)
    ca_idcriterio: integer
    ca_usucreado: string(20)
    ca_fchcreado: timestamp
  relations:
    IdsCriterio:
      local: ca_idcriterio
      foreign: ca_idcriterio
      type: one
    Ids:
      local: ca_id
      foreign: ca_id
      type: one

#Hace referencia a una vista  
#Se cambió por motivos de compatibilidad 
Cliente:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ids
  tableName: vi_clientes_reduc
  columns:
    ca_idcliente:
        type: integer
        primary: true
    ca_compania: string
    ca_idalterno: string(20)
    ca_tipoidentificacion: integer
    ca_digito: integer
    ca_papellido: string
    ca_sapellido: string
    ca_nombres: string
    ca_saludo: string
    ca_sexo: string
    ca_cumpleanos: string
    ca_direccion: string
    ca_oficina: string
    ca_torre: string
    ca_bloque: string
    ca_interior: string
    ca_localidad: string
    ca_nombres: string
    ca_complemento: string
    ca_telefonos: string
    ca_fax: string
    ca_idciudad: string
    ca_website: string
    ca_email: string
    ca_actividad: string
    ca_sectoreco: string
    ca_vendedor: string
    ca_status: string
    ca_calificacion: string
    ca_preferencias: string
    ca_confirmar: string
    ca_coordinador: string
    ca_fchcircular: date
    ca_nvlriesgo: string
    ca_fchcotratoag: date
    ca_listaclinton: string
    ca_leyinsolvencia: string
    ca_comentario: string
    ca_idgrupo: string
    ca_tipo: string
    ca_propiedades: string
    ca_entidad: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
    ca_fchfinanciero: timestamp
    ca_usufinanciero: string
  relations:
    Ids:
      local: ca_idcliente
      foreign: ca_id
      type: one
    Contacto:
      local: ca_idcliente
      foreign: ca_idcliente
      type: many
    Usuario:
      local: ca_vendedor
      foreign: ca_login
      type: one
    Ciudad:
      local: ca_idciudad
      foreign: ca_idciudad
      type: one
    StdCliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: many
    LibCliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: one
  

#Hace referencia a la tabla
#No contiene el nombre de la compañia ya que esta en Ids
IdsCliente:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ids
  tableName: tb_clientes
  columns:
    ca_idcliente:
        type: integer
        primary: true    
    ca_papellido: string
    ca_sapellido: string
    ca_nombres: string
    ca_saludo: string
    ca_sexo: string
    ca_cumpleanos: string
    ca_direccion: string
    ca_oficina: string
    ca_torre: string
    ca_bloque: string
    ca_interior: string
    ca_localidad: string
    ca_nombres: string
    ca_complemento: string
    ca_telefonos: string
    ca_fax: string
    ca_idciudad: string
    ca_website: string
    ca_email: string
    ca_actividad: string
    ca_sectoreco: string
    ca_vendedor: string
    ca_status: string
    ca_calificacion: string
    ca_preferencias: string
    ca_confirmar: string
    ca_coordinador: string
    ca_fchcircular: date
    ca_nvlriesgo: string
    ca_fchcotratoag: date
    ca_listaclinton: string
    ca_leyinsolvencia: string
    ca_comentario: string
    ca_idgrupo: string
    ca_tipo: string
    ca_propiedades: string
    ca_entidad: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
    ca_fchfinanciero: timestamp
    ca_usufinanciero: string
  relations:
    Ids:
      local: ca_idcliente
      foreign: ca_id
      type: one
    Contacto:
      local: ca_idcliente
      foreign: ca_idcliente
      type: many
    Usuario:
      local: ca_vendedor
      foreign: ca_login
      type: one
    Ciudad:
      local: ca_idciudad
      foreign: ca_idciudad
      type: one
    StdCliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: many
    LibCliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: one


IdsSeguimiento:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ids
  tableName: ids.tb_seguimientos
  columns:
    ca_idseguimiento:
      type: integer
      primary: true
      autoincrement: true
    ca_id: integer
    ca_fchseguimiento: timestamp
    ca_tipo: string
    ca_asunto: string
    ca_detalle: string
    ca_compromisos: string
    ca_fchcompromiso: timestamp
    ca_idantecedente: integer
    ca_usuario: string
    ca_fchpublicado: timestamp
    ca_usucreado: string
    ca_fchcreado: timestamp
    ca_usuactualizado: string(20)
    ca_fchactualizado: timestamp
  relations:
    Ids:
      local: ca_id
      foreign: ca_id
      type: one
    Usuario:
      local: ca_usuario
      foreign: ca_login
      type: one

