
InoMaestra:
  generatePath: ino
  tableName: ino.tb_maestra
  columns:
    ca_idmaestra:
      type: integer
      autoincrement: true
      primary: true
    ca_fchreferencia:
      type: date      
    ca_referencia: string
    ca_idtrayecto: 
      type: integer
      notnull: true
    ca_referencia: string
    ca_master:
        type: string
        notnull: true
    ca_fchmaster:
        type: date
        notnull: true
    ca_piezas: decimal
    ca_peso: decimal
    ca_volumen: decimal
    ca_observaciones: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
    ca_fchliquidado: timestamp
    ca_usuliquidado: string
    ca_fchcerrado: timestamp
    ca_usucerrado: string
    ca_fchanulado: timestamp
    ca_usuanulado: string
  relations:
    InoCliente:
      local: ca_idmaestra
      foreign: ca_idmaestra
      type: many
    Trayecto:
      local: ca_idtrayecto
      foreign: ca_idtrayecto
      type: one
    UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario
    UsuActualizado:
      local: ca_usuactualizado
      foreign: ca_login
      type: one
      class: Usuario
    UsuLiquidado:
      local: ca_usuliquidado
      foreign: ca_login
      type: one
      class: Usuario
    UsuCerrado:
      local: ca_usucerrado
      foreign: ca_login
      type: one
      class: Usuario
    UsuAnulado:
      local: ca_usuanulado
      foreign: ca_login
      type: one
      class: Usuario



InoCliente:
  generatePath: ino
  tableName: ino.tb_clientes
  columns:
    ca_idinocliente:
      type: integer
      autoincrement: true
      primary: true
    ca_idmaestra:
      type: integer
      notnull: true
    ca_idcliente:
      type: integer
      notnull: true
    ca_hbls:
      type: string
      notnull: true
    ca_fchhbls:
      type: date
      notnull: true
    ca_idreporte:
      type: integer
      notnull: true
    ca_idproveedor:
      type: integer
      notnull: true
    ca_proveedor:
      type: string
    ca_numpiezas:
      type: decimal
      notnull: true
    ca_peso:
      type: decimal
      notnull: true
    ca_volumen:
      type: decimal
      notnull: true
    ca_numorden:
      type: string
      notnull: true
    ca_vendedor:
      type: string
      notnull: true
    ca_idsubtrayecto:
      type: integer      
    ca_idbodega:
      type: integer
    ca_observaciones:
      type: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
  relations:
    Cliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: one
    InoMaestra:
      local: ca_idmaestra
      foreign: ca_idmaestra
      type: many
    Proveedor:
      local: ca_idproveedor
      foreign: ca_idtercero
      type: one
      class: Tercero
    Vendedor:
      local: ca_vendedor
      foreign: ca_login
      type: one
      class: Usuario
    UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario
    UsuActualizado:
      local: ca_usuactualizado
      foreign: ca_login
      type: one
      class: Usuario

InoComprobante:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ino
  tableName: ino.tb_comprobantes
  columns:
    ca_idcomprobante:
      type: integer
      autoincrement: true
      primary: true
    ca_id: integer
    ca_idtipo: integer
    ca_consecutivo: integer
    ca_fchcomprobante: date
    ca_idmaestra: integer
    ca_observaciones: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
  relations:    
    UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario
    UsuActualizado:
      local: ca_usuactualizado
      foreign: ca_login
      type: one
      class: Usuario
    InoTransaccion:
      local: ca_idcomprobante
      foreign: ca_idcomprobante
      type: many
    Ids:
      local: ca_id
      foreign: ca_id
      type: one

InoTransaccion:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ino
  tableName: ino.tb_transacciones
  columns:
    ca_idtransaccion:
      type: integer
      autoincrement: true
      primary: true
    ca_idcomprobante: integer
    ca_idcuenta: integer
    ca_idconcepto: integer
    ca_id: integer
    ca_db: decimal
    ca_cr: decimal
    ca_idmoneda: string
    ca_observaciones: timestamp
    ca_fchcreado: timestamp
    ca_usucreado: string
  relations:
    InoCliente:
      local: ca_idinocliente
      foreign: ca_idinocliente
      type: one
    UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario
    InoComprobante:
      local: ca_idcomprobante
      foreign: ca_idcomprobante
      type: one
    InoCuenta:
      local: ca_idcuenta
      foreign: ca_idcuenta
      type: one
    InoConcepto:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: one


InoConcepto:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ino
  tableName: ino.tb_conceptos
  columns:
    ca_idconcepto:
      type: integer
#      autoincrement: true
      primary: true
    ca_concepto:
      type: string
      notnull: true
    ca_tipo: string   
    ca_liminferior: integer
    ca_incoterms: string
    ca_comisionable: booolean
    ca_idcuenta: integer
    ca_ingreso_propio: booolean
    ca_iva: decimal
    ca_baseretencion: decimal
    ca_idcuentaretencion: integer
    ca_valor: decimal
    ca_convenios: boolean
    ca_autoretencion: decimal
    ca_tipoautoretencion: smallint
  relations:
    InoCuenta:
      local: ca_idcuenta
      foreign: ca_idcuenta
      type: one
    InoCuentaRetencion:
      local: ca_idcuentaretencion
      foreign: ca_idcuenta
      type: one
      class: InoCuenta
    
InoConceptoModalidad:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ino
  tableName: ino.tb_conceptos_modalidades  
  columns:
    ca_idconcepto:
      type: integer
      primary: true
    ca_idmodalidad:
      type: integer
      primary: true
  relations:
    InoConcepto:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: one
    Modalidad:
      local: ca_idmodalidad
      foreign: ca_idmodalidad
      type: one

InoCuenta:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ino
  tableName: ino.tb_cuentas
  columns:
    ca_idcuenta:
      type: integer
      autoincrement: true
      primary: true
    ca_cuenta: string
    ca_descripcion: string
    ca_naturaleza: string
    ca_moneda: string


InoTipoComprobante:
  generatePath: ino
  tableName: ino.tb_tipos_comprobante
  columns:
    ca_idtipo:
      type: integer
      autoincrement: true
      primary: true
    ca_tipo:
      type: string
      notnull: true
    ca_comprobante:
      type: integer
      notnull: true
    ca_descripcion: string
    ca_titulo: string
    ca_numeracion_inicial:
      type: integer
      notnull: true
    ca_mensaje: string
    ca_noautorizacion: string
    ca_prefijo_aut: string
    ca_inicial_aut: integer
    ca_final_aut: integer
    ca_activo: boolean
    