InoMaestra:
  generatePath: ino
  tableName: ino.tb_maestra
  columns:
    ca_idmaestra:
      type: integer
      primary: true
      autoincrement: true
    ca_fchreferencia: date
    ca_referencia: string
    ca_idtrayecto: integer
    ca_referencia: string
    ca_master: string
    ca_fchmaster: date
    ca_piezas: decimal
    ca_peso: decimal
    ca_volumen: decimal
    ca_observaciones: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
    ca_fchliquidado: timestamp
    ca_usuliquidado: string
    ca_fchcerrado: timestamp
    ca_usucerrado: string
    ca_fchanulado: timestamp
    ca_usuanulado: string




