
InoMaster:
  generatePath: ino
  tableName: ino.tb_master
  columns:
    ca_idmaster:
      type: integer
      autoincrement: true
      primary: true
    ca_fchreferencia:
      type: date      
    ca_referencia: string
    ca_impoexpo:
      type: string
      notnull: true
    ca_transporte:
      type: string
      notnull: true
    ca_modalidad:
      type: string
      notnull: true
    ca_origen:
      type: string
      notnull: true
    ca_destino:
      type: string
      notnull: true
    ca_idlinea:
      type: integer
      notnull: true
    ca_idagente: integer
    ca_referencia: string(15)
    ca_master:
        type: string
        notnull: true
    ca_fchmaster:
        type: date
        notnull: true
    ca_piezas: decimal
    ca_peso: decimal
    ca_volumen: decimal
    ca_observaciones: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
    ca_fchliquidado: timestamp
    ca_usuliquidado: string
    ca_fchcerrado: timestamp
    ca_usucerrado: string
    ca_fchanulado: timestamp
    ca_usuanulado: string
  relations:
    InoHouse:
      local: ca_idmaster
      foreign: ca_idmaster
      type: many    
    Origen:
      local: ca_origen
      foreign: ca_idciudad
      type: one
      class: Ciudad
    Destino:
      local: ca_destino
      foreign: ca_idciudad
      type: one
      class: Ciudad
    IdsProveedor:
      local: ca_idlinea
      foreign: ca_idproveedor
      type: one
    UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario
    UsuActualizado:
      local: ca_usuactualizado
      foreign: ca_login
      type: one
      class: Usuario
    UsuLiquidado:
      local: ca_usuliquidado
      foreign: ca_login
      type: one
      class: Usuario
    UsuCerrado:
      local: ca_usucerrado
      foreign: ca_login
      type: one
      class: Usuario
    UsuAnulado:
      local: ca_usuanulado
      foreign: ca_login
      type: one
      class: Usuario



InoHouse:
  generatePath: ino
  tableName: ino.tb_house
  columns:
    ca_idhouse:
      type: integer
      autoincrement: true
      primary: true
    ca_idmaster:
      type: integer
      notnull: true
    ca_idcliente:
      type: integer
      notnull: true
    ca_doctransporte:
      type: string
      notnull: true
    ca_fchdoctransporte:
      type: date
      notnull: true
    ca_idreporte:
      type: integer
      notnull: true
    ca_idproveedor:
      type: integer
      notnull: true
    ca_proveedor:
      type: string
    ca_numpiezas:
      type: decimal
      notnull: true
    ca_peso:
      type: decimal
      notnull: true
    ca_volumen:
      type: decimal
      notnull: true
    ca_numorden:
      type: string
      notnull: true
    ca_vendedor:
      type: string
      notnull: true
    ca_idsubtrayecto:
      type: integer      
    ca_idbodega:
      type: integer
    ca_observaciones:
      type: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
  relations:
    Cliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: one
    InoMaster:
      local: ca_idmaster
      foreign: ca_idmaster
      type: one
    InoComprobante:
      local: ca_idhouse
      foreign: ca_idhouse
      type: many
    Proveedor:
      local: ca_idproveedor
      foreign: ca_idtercero
      type: one
      class: Tercero
    Reporte:
      local: ca_idreporte
      foreign: ca_idreporte
      type: one
    Vendedor:
      local: ca_vendedor
      foreign: ca_login
      type: one
      class: Usuario
    UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario
    UsuActualizado:
      local: ca_usuactualizado
      foreign: ca_login
      type: one
      class: Usuario


InoComprobante:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ino
  tableName: ino.tb_comprobantes
  columns:
    ca_idcomprobante:
      type: integer
      autoincrement: true
      primary: true
    ca_id: integer
    ca_idtipo: integer    
    ca_consecutivo: integer
    ca_fchcomprobante: date
#    ca_idmaster: integer
    ca_idhouse: integer
    ca_plazo: integer
    ca_tasacambio: decimal
    ca_observaciones: string
    ca_estado: integer
    ca_valor: float
    ca_idmoneda: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
  relations:
    Ids:
      local: ca_id
      foreign: ca_id
      type: one      
    UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario
    UsuActualizado:
      local: ca_usuactualizado
      foreign: ca_login
      type: one
      class: Usuario
    InoHouse:
      local: ca_idhouse
      foreign: ca_idhouse
      type: one
    InoTransaccion:
      local: ca_idcomprobante
      foreign: ca_idcomprobante
      type: many
    InoTipoComprobante:
      local: ca_idtipo
      foreign: ca_idtipo
      type: one
    

InoTransaccion:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ino
  tableName: ino.tb_transacciones
  columns:
    ca_idtransaccion:
      type: integer
      autoincrement: true
      primary: true
    ca_idcomprobante: integer
    ca_idcuenta: integer
    ca_idconcepto: integer
    ca_idccosto: integer
    ca_idmaster: integer
    ca_id: integer
    ca_db: boolean
    ca_valor: decimal
    ca_idmoneda: string
    ca_observaciones: timestamp
    ca_fchcreado: timestamp
    ca_usucreado: string
  relations:
    InoHouse:
      local: ca_idhouse
      foreign: ca_idhouse
      type: one
    InoCentroCosto:
      local: ca_idccosto
      foreign: ca_idccosto
      type: one
    UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario
    InoComprobante:
      local: ca_idcomprobante
      foreign: ca_idcomprobante
      type: one
    InoCuenta:
      local: ca_idcuenta
      foreign: ca_idcuenta
      type: one
    InoConcepto:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: one
    InoMaster:
      local: ca_idmaster
      foreign: ca_idmaster
      type: one

InoConcepto:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ino
  tableName: ino.tb_conceptos
  columns:
    ca_idconcepto:
      type: integer
      autoincrement: true
      primary: true
    ca_concepto:
      type: string
      notnull: true
    ca_tipo: string   
    ca_liminferior: integer
    ca_flete: boolean
    ca_recargolocal: boolean
    ca_recargoorigen: boolean
    ca_recargootmdta: boolean
    ca_costo: boolean
    ca_aplicaciones: string
    ca_aka: string
    ca_fcheliminado: timestamp
    ca_usueliminado: string
  relations:
    InoConceptoModalidad:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: many
    InoParametroFacturacion:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: many
    InoParametroCosto:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: many

InoParametroFacturacion:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ino
  tableName: ino.tb_parametros_facturacion
  columns:
    ca_idparametro:
      type: integer
      autoincrement: true
      primary: true
    ca_idconcepto:
      type: integer
    ca_idccosto:
      type: integer
    ca_idcuenta: integer
    ca_ingreso_propio: booolean
    ca_iva: decimal
    ca_baseretencion: decimal
    ca_idcuentaretencion: integer
    ca_valor: decimal
    ca_convenios: boolean
    ca_autoretencion: decimal
    ca_tipoautoretencion: smallint
  relations:
    InoConcepto:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: one
    InoCentroCosto:
      local: ca_idccosto
      foreign: ca_idccosto
      type: one
    InoCuenta:
      local: ca_idcuenta
      foreign: ca_idcuenta
      type: one
    InoCuentaRetencion:
      local: ca_idcuentaretencion
      foreign: ca_idcuenta
      type: one
      class: InoCuenta

InoParametroCosto:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ino
  tableName: ino.tb_parametros_costos
  columns:
    ca_idparametro:
      type: integer
      autoincrement: true
      primary: true
    ca_idconcepto:
      type: integer
    ca_idccosto:
      type: integer
    ca_idcuenta: integer
  relations:
    InoConcepto:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: one
    InoCentroCosto:
      local: ca_idccosto
      foreign: ca_idccosto
      type: one
    InoCuenta:
      local: ca_idcuenta
      foreign: ca_idcuenta
      type: one

InoConceptoModalidad:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ino
  tableName: ino.tb_conceptos_modalidades  
  columns:
    ca_idconcepto:
      type: integer
      primary: true
    ca_idmodalidad:
      type: integer
      primary: true
    ca_comisionable: boolean
  relations:
    InoConcepto:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: one
    Modalidad:
      local: ca_idmodalidad
      foreign: ca_idmodalidad
      type: one

InoCuenta:
  options:
    symfony:
      form: false
      filter: false
  generatePath: ino
  tableName: ino.tb_cuentas
  columns:
    ca_idcuenta:
      type: integer
      autoincrement: true
      primary: true
    ca_cuenta: string
    ca_descripcion: string
    ca_naturaleza: string
    ca_moneda: string


InoTipoComprobante:
  generatePath: ino
  tableName: ino.tb_tipos_comprobante
  columns:
    ca_idtipo:
      type: integer
      autoincrement: true
      primary: true
    ca_tipo:
      type: string
      notnull: true
    ca_comprobante:
      type: integer
      notnull: true
    ca_descripcion: string
    ca_titulo: string
    ca_numeracion_inicial:
      type: integer
      notnull: true
    ca_mensaje: string
    ca_noautorizacion: string
    ca_fchautorizacion: date
    ca_prefijo_aut: string
    ca_inicial_aut: integer
    ca_final_aut: integer
    ca_activo: boolean
    ca_idsucursal: integer
    ca_idcta_cierre: integer
    ca_idcta_iva: integer
  relations:
    IdsSucursal:
      local: ca_idsucursal
      foreign: ca_idsucursal
      type: one
    
InoCentroCosto:
  generatePath: ino
  tableName: ino.tb_ccostos
  columns:
    ca_idccosto:
      type: integer
      autoincrement: true
      primary: true
    ca_centro: 
      type: integer
      notnull: true
    ca_subcentro:
      type: integer      
    ca_nombre: 
      type: string
      notnull: true


InoAuditor:
  generatePath: ino
  tableName: ino.tb_auditor
  columns:
    ca_idevento:
      type: integer
      autoincrement: true
      primary: true
    ca_idmaster: integer
    ca_tipo : string
    ca_asunto: string
    ca_detalle : string
    ca_compromisos: string
    ca_respuesta: string
    ca_fchcompromiso : date
    ca_idantecedente: integer           
    ca_estado: char
    ca_fchcreado: timestamp
    ca_usucreado: string
  relations:
    InoMaster:
      local: ca_idmaster
      foreign: ca_idmaster
      type: many
    UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario
    InoAuditor:
      local: ca_idevento
      foreign: ca_idantecedente
      type: many
