
InoMaestra:
  generatePath: ino
  tableName: ino.tb_maestra
  attributes:
    export: tables
  columns:
    ca_idmaestra:
      type: integer
      autoincrement: true
      primary: true
    ca_fchreferencia:
      type: date      
    ca_referencia: string
    ca_idtrayecto: 
      type: integer
      notnull: true
    ca_referencia: string
    ca_master:
        type: string
        notnull: true
    ca_fchmaster:
        type: date
        notnull: true
    ca_piezas: decimal
    ca_peso: decimal
    ca_volumen: decimal
    ca_observaciones: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
    ca_fchliquidado: timestamp
    ca_usuliquidado: string
    ca_fchcerrado: timestamp
    ca_usucerrado: string
    ca_fchanulado: timestamp
    ca_usuanulado: string
  relations:
    Trayecto:
      local: ca_idtrayecto
      foreign: ca_idtrayecto
      type: one
    UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario
    UsuActualizado:
      local: ca_usuactualizado
      foreign: ca_login
      type: one
      class: Usuario
    UsuLiquidado:
      local: ca_usuliquidado
      foreign: ca_login
      type: one
      class: Usuario
    UsuCerrado:
      local: ca_usucerrado
      foreign: ca_login
      type: one
      class: Usuario
    UsuAnulado:
      local: ca_usuanulado
      foreign: ca_login
      type: one
      class: Usuario




