InoMaestraAir:
  generatePath: inoAnterior
  tableName: tb_inomaestra_air
  columns:
    ca_referencia:
      type: string(16)
      primary: true
      autoincrement: true
    ca_idlinea: integer

InoMaestraSea:
  generatePath: inoAnterior
  tableName: tb_inomaestra_sea
  columns:
    ca_referencia:
      type: string(16)
      primary: true
      autoincrement: true
    ca_idlinea: integer