
InoMaestraSea:
  options:
    symfony:
      form: false
      filter: false
  generatePath: sea
  tableName: tb_inomaestra_sea
  columns:
    ca_referencia:
      type: string
      primary: true
    ca_fchreferencia: date
    ca_impoexpo: string
    ca_origen: string
    ca_destino: string
    ca_fchembarque: date
    ca_fcharribo: date
    ca_modalidad: string
    ca_idlinea: integer
    ca_motonave: string
    ca_ciclo: string
    ca_mbls: string
    ca_observaciones: string
    ca_fchconfirmacion: date
    ca_horaconfirmacion: time
    ca_registroadu: string
    ca_registrocap: string
    ca_bandera: string
    ca_fchliberacion: date
    ca_nroliberacion: string
    ca_anulado: string
    ca_mensaje: string
    ca_fchdesconsolidacion: date
    ca_mnllegada: string
    ca_fchregistroadu: date    
    ca_provisional: boolean    
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
    ca_fchliquidado: timestamp
    ca_usuliquidado: string
    ca_fchcerrado: timestamp
    ca_usucerrado: string
    ca_fchconfirmado: timestamp
    ca_usuconfirmado: string
    ca_fchvaciado: date
    ca_horavaciado: time
    ca_fchmuisca: timestamp
    ca_usumuisca: string
    ca_fchmbls: date
    ca_carpeta: boolean
    ca_muelle: integer
    ca_fchfinmuisca: date
    ca_estado: string
    ca_fchenvio: timestamp
    ca_fchrecibido: timestamp
  relations:
    InoClientesSea:
      local: ca_referencia
      foreign: ca_referencia
      type: many
    InoEquiposSea:
      local: ca_referencia
      foreign: ca_referencia
      type: many
    IdsProveedor:
      local: ca_idlinea
      foreign: ca_idproveedor
      type: one    
    Origen:
      local: ca_origen
      foreign: ca_idciudad
      type: one
      class: Ciudad
    Destino:
      local: ca_destino
      foreign: ca_idciudad
      type: one
      class: Ciudad
    UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario
    InoDianDepositos:
      local: ca_muelle
      foreign: ca_codigo

InoClientesSea:
  options:
    symfony:
      form: false
      filter: false
  generatePath: sea
  tableName: tb_inoclientes_sea
  columns:
    ca_idinocliente:
      type: integer      
    ca_referencia:
      type: string   
      primary: true
    ca_idcliente:
      type: integer  
      primary: true
    ca_hbls:
      type: string  
      primary: true
    ca_idreporte: integer
    ca_idproveedor: integer
    ca_proveedor: string
    ca_numpiezas: decimal
    ca_peso: decimal
    ca_volumen: decimal
    ca_numorden: decimal
    ca_confirmar: string
    ca_login: string
    ca_observaciones: string
    ca_fchliberacion: date
    ca_notaliberacion: string
    ca_mensaje: string
    ca_continuacion: string
    ca_continuacion_dest: string
    ca_idbodega: integer
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
    ca_fchliberado: timestamp
    ca_usuliberado: string
    ca_fchhbls : date
    ca_fchantecedentes: date
    ca_imprimirorigen : boolean
    ca_idaduana: integer
  relations:
     Reporte:
       local: ca_idreporte
       foreign: ca_idreporte
       type: one
     InoMaestraSea:
       local: ca_referencia
       foreign: ca_referencia
       type: one
     Cliente:
       local: ca_idcliente
       foreign: ca_idcliente
       type: one
     Tercero:
       local: ca_idproveedor
       foreign: ca_idtercero
       type: one
     Proveedor:
       local: ca_idproveedor
       foreign: ca_idtercero
       type: one
       class: Tercero
     DestinoCont:
      local: ca_continuacion_dest
      foreign: ca_idciudad
      type: one
      class: Ciudad
     Vendedor:
      local: ca_login
      foreign: ca_login
      type: one
      class: Usuario
     Ids:
      local: ca_idagente
      foreign: ca_id
      type: one
      class: Ids
     Aduana:
      local: ca_idaduana
      foreign: ca_id
      type: one
      class: Ids

InoEquiposSea:
  options:
    symfony:
      form: false
      filter: false
  generatePath: sea
  tableName: tb_inoequipos_sea
  columns:
    ca_referencia:
      type: string
      primary: true
    ca_idequipo:
      type: integer
      primary: true
    ca_idconcepto: integer
    ca_cantidad: float
    ca_observaciones: string
    ca_numprecinto: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
  relations:
     InoMaestraSea:
       local: ca_referencia
       foreign: ca_referencia
       type: one
     InoContratosSea:
       local: ca_referencia
       local: ca_idequipo
       foreign: ca_referencia
       foreign: ca_idequipo
       type: one
     Concepto:
       local: ca_idconcepto
       foreign: ca_idconcepto
       type: one


InoContratosSea:
  options:
    symfony:
      form: false
      filter: false
  generatePath: sea
  tableName: tb_inocontratos_sea
  columns:
    ca_referencia:
      type: string
      primary: true
    ca_idequipo:
      type: integer
      primary: true
    ca_entrega_comodato: date
    ca_idpatio: integer
    ca_inspeccion_nta: string
    ca_inspeccion_fch: date
    ca_observaciones: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
  relations:
     InoMaestraSea:
       local: ca_referencia
       foreign: ca_referencia
       type: one
     PricPatio:
       local: ca_idpatio
       foreign: ca_idpatio
       type: one
       

    
InoIngresosSea:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inoAnterior
  tableName: tb_inoingresos_sea
  columns:
    ca_referencia:
      type: string
      primary: true
    ca_idcliente:
      type: integer
      primary: true
    ca_hbls:
      type: string
      primary: true
    ca_factura:
      type: string
      primary: true
    ca_fchfactura: date
    ca_idmoneda: string
    ca_neto: decimal
    ca_valor: decimal
    ca_reccaja: string    
    ca_fchpago: date
    ca_tcambio: decimal
    ca_observaciones: string    
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string    
  relations:    
     InoMaestraSea:
       local: ca_referencia
       foreign: ca_referencia
       type: one        

InoCostosSea:
  options:
    symfony:
      form: false
      filter: false
  generatePath: sea
  tableName: tb_inocostos_sea
  columns:
    oid:
      type: integer
      primary: true
    ca_referencia:
      type: string      
    ca_idcosto:
      type: integer      
    ca_factura:
      type: string          
    ca_fchfactura: date
    #ca_idproveedor: integer
    ca_proveedor: string
    ca_idmoneda: string
    ca_tcambio: decimal
    ca_tcambio_usd: decimal
    ca_neto: decimal
    ca_venta: decimal    
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string 
    ca_idproveedor: integer
  relations:
     Costo:
       local: ca_idcosto
       foreign: ca_idcosto
       type: one
     InoMaestraSea:
       local: ca_referencia
       foreign: ca_referencia
       type: one     
     UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario
     UsuActualizado:
      local: ca_usuactualizado
      foreign: ca_login
      type: one
      class: Usuario


InoutilidadSea:
  options:
    symfony:
      form: false
      filter: false
  generatePath: sea
  tableName: tb_inoutilidad_sea
  columns:    
    ca_referencia:
      type: string 
      primary: true
    ca_idcliente:
      type: integer      
      primary: true
    ca_hbls:
      type: string   
      primary: true
    ca_idcosto:
      type: integer      
      primary: true
    ca_factura:
      type: string      
      primary: true
    ca_valor: decimal    
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string    
  relations:
     Costo:
       local: ca_idcosto
       foreign: ca_idcosto
       type: one
     InoMaestraSea:
       local: ca_referencia
       foreign: ca_referencia
       type: one     
     UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario
     UsuActualizado:
      local: ca_usuactualizado
      foreign: ca_login
      type: one
      class: Usuario

InoMaestraAir:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inoAnterior
  tableName: tb_inomaestra_air
  columns:
    ca_referencia:
      type: string(16)
      primary: true      
    ca_fchreferencia: date
    ca_impoexpo: string(16)  
    ca_modalidad: string
    ca_idlinea: integer
    ca_origen: string
    ca_destino: string
    ca_mawb: string
    ca_piezas: string
    ca_peso: string
    ca_pesovolumen: string
    ca_fchpreaviso: date
    ca_fchllegada: date
    ca_observaciones: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
    ca_fchliquidado: timestamp
    ca_usuliquidado: string
    ca_fchcerrado: timestamp
    ca_usucerrado: string
    ca_idagente: integer    
  relations:
    InoClientesAir:
      local: ca_referencia
      foreign: ca_referencia
      type: many    
    IdsProveedor:
      local: ca_idlinea
      foreign: ca_idproveedor
      type: one   
    IdsAgente:
      local: ca_idagente
      foreign: ca_idagente
      type: one   
    Origen:
      local: ca_origen
      foreign: ca_idciudad
      type: one
      class: Ciudad
    Destino:
      local: ca_destino
      foreign: ca_idciudad
      type: one
      class: Ciudad
    UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario
   
 

InoClientesAir:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inoAnterior
  tableName: tb_inoclientes_air
  columns:
    ca_referencia:
      type: string
      primary: true
    ca_idcliente:
      type: integer
      primary: true
    ca_hawb:
      type: string
      primary: true
    oid: integer
    ca_idreporte: string
    ca_idproveedor: integer
    ca_proveedor: string
    ca_numpiezas: decimal
    ca_peso: decimal
    ca_volumen: decimal
    ca_numorden: decimal    
    ca_loginvendedor: string  
    ca_idbodega: integer
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string    
  relations:    
     InoMaestraAir:
       local: ca_referencia
       foreign: ca_referencia
       type: one
     Cliente:
       local: ca_idcliente
       foreign: ca_idcliente
       type: one
     Tercero:
       local: ca_idproveedor
       foreign: ca_idtercero
       type: one
     Proveedor:
       local: ca_idproveedor
       foreign: ca_idtercero
       type: one
       class: Tercero     
     Vendedor:
      local: ca_loginvendedor
      foreign: ca_login
      type: one
      class: Usuario

InoIngresosAir:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inoAnterior
  tableName: tb_inoingresos_air
  columns:
    ca_referencia:
      type: string
      primary: true
    ca_idcliente:
      type: integer
      primary: true
    ca_hawb:
      type: string
      primary: true
    ca_factura:
      type: string
      primary: true
    ca_fchfactura: date
    ca_valor: decimal
    ca_reccaja: string
    ca_reccaja: string
    ca_fchpago: date
    ca_tcalaico: decimal
    ca_observaciones: string    
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string    
  relations:    
     InoMaestraAir:
       local: ca_referencia
       foreign: ca_referencia
       type: one          
      
InoCostosAir:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inoAnterior
  tableName: tb_inocostos_air
  columns:
    ca_referencia:
      type: string
      primary: true
    ca_idcosto:
      type: integer
      primary: true    
    ca_factura:
      type: string
      primary: true
    ca_fchfactura: date    
    ca_factura: string
    ca_idmoneda: string
    ca_trm: decimal
    ca_trm_usd: decimal
    ca_neto: decimal
    ca_venta: decimal    
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string   
    ca_idproveedor: integer
  relations:    
     InoMaestraAir:
       local: ca_referencia
       foreign: ca_referencia
       type: one          
 
InoUtilidadAir:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inoAnterior
  tableName: tb_inoutilidad_air
  columns:
    ca_referencia:
      type: string
      primary: true
    ca_idcliente:
      type: integer
      primary: true    
    ca_hawb:
      type: string
      primary: true
    ca_idcosto:
      type: integer
      primary: true
    ca_factura:
      type: string
      primary: true 
    ca_valor: decimal    
    ca_fchcreado: timestamp
    ca_usucreado: string    
  relations:    
     InoMaestraAir:
       local: ca_referencia
       foreign: ca_referencia
       type: one      
      
      
InoMaestraExpo:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inoAnterior
  tableName: tb_expo_maestra
  columns:
    ca_referencia:
      type: string
      primary: true
    ca_fchreferencia: date
    ca_idcliente: integer
    ca_producto: string
    ca_via: string
    ca_modalidad: string
    ca_origen: string
    ca_destino: string
    ca_peso: float
    ca_pesovolumen: float
    ca_valorcarga: float
    ca_idsia: integer
    ca_contacto: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
    ca_fchliquidado: timestamp
    ca_usuliquidado: string
    ca_fchcerrado: timestamp
    ca_usucerrado: string
    ca_idagente: integer
    ca_tipoexpo: integer
    ca_incoterm: string
    ca_nombrecons: string
    ca_direccioncons: string
    ca_consecutivo: string
    ca_aplicaidg: boolean
  relations:         
     Cliente:
       local: ca_idcliente
       foreign: ca_idcliente
       type: one

      
InoMaestraExpoAir:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inoAnterior
  tableName: tb_expo_aerea
  columns:
    ca_referencia:
      type: string
      primary: true    
    ca_idexpo: integer
    ca_idaerolinea: string
    ca_hawb: string
    
InoMaestraExpoSea:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inoAnterior
  tableName: tb_expo_maritimo
  columns:
    ca_referencia:
      type: string
      primary: true    
    ca_idexpo: integer
    ca_idnaviera: integer
    ca_modalidad: string
    ca_hija: string

    
InoMaestraExpoTer:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inoAnterior
  tableName: tb_expo_terrestre
  columns:
    ca_referencia:
      type: string
      primary: true    
    ca_idexpo: integer
    ca_idtransportador: integer
    ca_cartaporte: string    
    
    
InoCostoExpo:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inoAnterior
  tableName: tb_expo_costos
  columns:
    ca_referencia:
      type: string
      primary: true    
    ca_idcosto: 
      type: integer
      primary: true    
    ca_neta: float
    ca_venta: float 
    ca_factura: 
      type: string
      primary: true    
    ca_fchfactura: date
    ca_facturaing: string
    ca_proveedor: string
    ca_idproveedor: integer
    ca_utilidad: float
    ca_moneda: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
  
 
InoIngresosExpo:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inoAnterior
  tableName: tb_expo_ingresos
  columns:
    ca_referencia:
      type: string
      primary: true    
    ca_idcliente: 
      type: integer
      primary: true    
    ca_documento: 
      type: string
      primary: true  
    ca_shipper: string 
    ca_loginvendedor: string 
    ca_factura: 
      type: string
      primary: true    
    ca_fchfactura: date
    ca_valor: float
    ca_reccaja: string
    ca_tasacambio: float
    ca_fchpago: string
    ca_observaciones: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
    ca_fchinformado: timestamp
    ca_usuinformado: string
  relations:
    InoMaestraExpo:
      local: ca_referencia
      foreign: ca_referencia
      type: one
    

    
    
ExpoAlerta:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inoAnterior
  tableName: tb_expo_alertas
  columns:
    ca_idalerta:
      type: integer
      primary: true
      autoincrement: true
    ca_cuerpoalerta: string
    ca_fchrecordatorio: date
    ca_referencia: string
    ca_fchvencimiento: date
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_notificar: string 
    ca_notificar_jefe: boolean
  relations:
    Usuario:
      local: ca_usucreado
      foreign: ca_login
      type: one
    InoMaestraExpo:
      local: ca_referencia
      foreign: ca_referencia
      type: one

InoDianDepositos:
  options:
    symfony:
      form: false
      filter: false
  generatePath: sea
  tableName: tb_diandepositos
  columns:
    ca_codigo:
      type: integer
      primary: true
    ca_nombre : string
    ca_administracion: string
    ca_tipo_deposito: string
    ca_direccion: string
    ca_fchdesde: string
    ca_fchhasta: string


InoDeduccionesSea:
  options:
    symfony:
      form: false
      filter: false
  generatePath: sea
  tableName: tb_inodeduccion_sea
  columns:
    ca_referencia: 
      type: string  
      primary: true
    ca_idcliente:
      type: integer
      primary: true
    ca_hbls:
      type: string
      primary: true
    ca_factura:
      type: string
      primary: true
    ca_iddeduccion:
      type: integer
      primary: true
    ca_neto: numeric
    ca_valor: numeric
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
  relations:
     InoMaestraSea:
       local: ca_referencia
       foreign: ca_referencia
       type: one
     Cliente:
       local: ca_idcliente
       foreign: ca_idcliente
       type: one