InoMaestraAir:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inoAnterior
  tableName: tb_inomaestra_air
  columns:
    ca_referencia:
      type: string(16)
      primary: true
      autoincrement: true
    ca_idlinea: integer

