Noticia:
  options:
    symfony:
      form: true
      filter: true
  generatePath: intranet
  tableName: intranet.tb_noticias
  columns:
    ca_idnoticia:
      type: integer
      primary: true
      autoincrement: true
    ca_categoria: string(12)
    ca_fchpublicacion: date
    ca_asunto: string
    ca_detalle: string
    ca_fcharchivar: date
    ca_extension: string
    ca_header_file: string
    ca_content: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_icon: string