   

InvCategory:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inv
  tableName: inv.tb_categories
  columns:
    ca_idcategory:
      type: integer
      primary: true
      autoincrement: true
    ca_parent: integer
    ca_name: string
    ca_order: integer
    ca_main: boolean 
    ca_parameter: string    
  relations:
    SubCategory:
      local: ca_idcategory
      foreign: ca_parent
      type: many
      class: InvCategory
      orderBy: ca_order ASC
    Parent:
      local: ca_parent
      foreign: ca_idcategory
      type: one
      class: InvCategory      
    InvActivo:
      local: ca_idcategory
      foreign: ca_idcategory
      type: many
    
    

InvActivo:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inv
  tableName: inv.tb_activos
  columns:
    ca_idactivo:
      type: integer
      primary: true
      autoincrement: true
    ca_idcategory: integer
    ca_identificador: string
    ca_fchcompra: date
    ca_proveedor: string
    ca_marca: string
    ca_modelo: string
    ca_ubicacion: string
    ca_ipaddress: string
    ca_procesador: string
    ca_memoria: string
    ca_disco: string
    ca_optica: string
    ca_serial: string
    ca_noinventario: string
    ca_version: string
    ca_factura: string
    ca_reposicion: float
    ca_observaciones: string
    ca_contrato: string
    ca_so: string
    ca_so_serial: string
    ca_office: string
    ca_office_serial: string
    ca_empresa: string
    ca_asignadoa: string
    ca_software: string
    ca_mantenimiento: string
    ca_idsucursal: string
    ca_cantidad: integer
    ca_detalle: string
    ca_fchbaja: date
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string       
  relations:
    InvCategory:
      local: ca_idcategory
      foreign: ca_idcategory
      type: one
    InvSeguimiento:
      local: ca_idactivo
      foreign: ca_idactivo
      type: many
    InvAsignacion:
      local: ca_idactivo
      foreign: ca_idactivo
      type: many
    InvAsignacionSoftware:
      local: ca_idactivo
      foreign: ca_idequipo
      type: many
    InvAsignacionSoftwareActivo:
      local: ca_idactivo
      foreign: ca_idactivo
      type: one
      class: InvAsignacionSoftware
    Usuario:
      local: ca_asignadoa
      foreign: ca_login
      type: one
    Sucursal:
      local: ca_idsucursal
      foreign: ca_idsucursal
      type: one



InvSeguimiento:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inv
  tableName: inv.tb_seguimientos
  columns:
    ca_idseguimiento:
      type: integer
      primary: true
      autoincrement: true
    ca_idactivo: integer
    ca_text: string
    ca_fchcreado: timestamp
    ca_usucreado: string
  relations:
    InvActivo:
      local: ca_idactivo
      foreign: ca_idactivo
      type: one
    Usuario:
      local: ca_usucreado
      foreign: ca_login
      type: one

InvAsignacion:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inv
  tableName: inv.tb_asignaciones
  columns:
    ca_idasignacion:
      type: integer
      primary: true
      autoincrement: true
    ca_idactivo: integer
    ca_login: string
    ca_fchasignacion: timestamp
  relations:
    InvActivo:
      local: ca_idactivo
      foreign: ca_idactivo
      type: one
    Usuario:
      local: ca_login
      foreign: ca_login
      type: one




InvAsignacionSoftware:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inv
  tableName: inv.tb_asignaciones_software
  columns:
    ca_idasignacion_software:
      type: integer
      primary: true
      autoincrement: true
    ca_idactivo: integer
    ca_idequipo: integer
    ca_usucreado: string
    ca_fchcreado: timestamp
  relations:
    InvActivo:
      local: ca_idactivo
      foreign: ca_idactivo
      type: one
    Equipo:
      local: ca_idequipo
      foreign: ca_idactivo
      type: one
      class: InvActivo
    UsuCreado:
      local: ca_fchcreado
      foreign: ca_login
      type: one
      class: Usuario


InvProducto:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inv
  tableName: inv.tb_productos
  columns:
    ca_idproducto:
      type: integer
      primary: true
      autoincrement: true
    ca_idcategoria: integer
    ca_nombre: string    
  relations:
    InvCategory:
      local: ca_idcategoria
      foreign: ca_idcategory
      type: one


InvPrefijo:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inv
  tableName: inv.tb_prefijos
  columns:
    ca_idcategory:
      type: integer
      primary: true
    ca_idsucursal:
      type: string
      primary: true             
    ca_prefix: string
    ca_autonumeric: boolean 
    ca_padlength: integer    
  relations:
    InvCategory:
      local: ca_idcategory
      foreign: ca_idcategory
      type: one
    Sucursal:
      local: ca_idsucursal
      foreign: ca_idsucursal
      type: one