Trayecto:
  options:
    symfony:
      form: true
      filter: false
  generatePath: pricing
  tableName: pric.tb_trayectos
  attributes:
    export: tables
  columns:
    ca_idtrayecto:
      type: integer
      primary: true
      autoincrement: true
    ca_origen:
      type: string(8)
      notnull: true
    ca_destino:
      type: string(8)
      notnull: true
    ca_idlinea:
      type: integer
      notnull: true
    ca_transporte:
      type: string
      notnull: true
    ca_impoexpo:
      type: string
      notnull: true
    ca_modalidad:
      type: string
      notnull: true
    ca_frecuencia: string
    ca_tiempotransito: string
    ca_observaciones: string
    ca_idagente: integer
    ca_activo: boolean
    ca_fchcreado: timestamp
    ca_usucreado: string
  relations:
    Origen:
      local: ca_origen
      foreign: ca_idciudad
      type: one
      class: Ciudad
    Destino:
      local: ca_destino
      foreign: ca_idciudad
      type: one
      class: Ciudad
    IdsProveedor:
      local: ca_idlinea
      foreign: ca_idproveedor
      type: one
    IdsAgente:
      local: ca_idagente
      foreign: ca_idagente
      type: one

ConceptoAduana:
  options:
    symfony:
      form: true
      filter: false
  generatePath: pricing
  tableName: pric.tb_conceptoaduana
  attributes:
    export: tables
  columns:
    ca_consecutivo:
      type: integer
      primary: true
      autoincrement: true
    ca_idconcepto:
      type: integer
      notnull: true
    ca_valor:
      type: numeric
      notnull: true
    ca_aplicacion:
      type: string
      notnull: true
    ca_valorminimo:
      type: numeric
      notnull: true
    ca_parametro:
      type: string
      notnull: true
    ca_aplicacionminimo:
      type: string
      notnull: true
    ca_parametro:
      type: string
      notnull: true
    ca_fchini:
      type: date
    ca_fchfin:
      type: date
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_observaciones:
      type: string
      notnull: true
  relations:
    Costo:
      local: ca_idconcepto
      foreign: ca_idcosto
      type: one


ConceptoDeposito:
  options:
    symfony:
      form: true
      filter: false
  generatePath: pricing
  tableName: pric.tb_conceptodeposito
  attributes:
    export: tables
  columns:
    ca_consecutivo:
      type: integer
      primary: true
      autoincrement: true
    ca_idconcepto:
      type: integer
      notnull: true
    ca_valor:
      type: numeric
      notnull: true
    ca_aplicacion:
      type: string
      notnull: true
    ca_valorminimo:
      type: numeric
      notnull: true
    ca_parametro:
      type: string
      notnull: true
    ca_aplicacionminimo:
      type: string
      notnull: true
    ca_parametro:
      type: string
      notnull: true
    ca_fchini:
      type: date
    ca_fchfin:
      type: date
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_observaciones:
      type: string
      notnull: true
  relations:
    Costo:
      local: ca_idconcepto
      foreign: ca_idcosto
      type: one


ConceptoAduanaCliente:
  options:
    symfony:
      form: true
      filter: false
  generatePath: pricing
  tableName: pric.tb_conceptoaduanaxcliente
  attributes:
    export: tables
  columns:
    ca_consecutivo:
      type: integer
      primary: true
      autoincrement: true
    ca_idconcepto:
      type: integer
      notnull: true
    ca_idcliente:
      type: numeric
      notnull: true
    ca_valor:
      type: numeric
      notnull: true
    ca_aplicacion:
      type: string
      notnull: true
    ca_valorminimo:
      type: numeric
      notnull: true
    ca_parametro:
      type: string
      notnull: true
    ca_aplicacionminimo:
      type: string
      notnull: true
    ca_parametro:
      type: string
      notnull: true
    ca_fchini:
      type: date
    ca_fchfin:
      type: date
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_observaciones:
      type: string
      notnull: true
  relations:    
    Costo:
      local: ca_idconcepto
      foreign: ca_idcosto
      type: one
    Cliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: one

PricFlete:
  options:
    symfony:
      form: false
      filter: false
  generatePath: pricing
  tableName: pric.tb_fletes
  attributes:
    export: tables
  columns:
    ca_consecutivo:
      type: integer
      primary: true
    ca_idtrayecto: integer
    ca_idconcepto: integer
    ca_idequipo: integer
    ca_vlrneto: decimal
    ca_vlrsugerido: decimal
    ca_fchinicio: date
    ca_fchvencimiento: date
    ca_idmoneda: string
    ca_estado: string
    ca_aplicacion: string    
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fcheliminado: timestamp
  relations:
    Concepto:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: one
    Equipo:
      local: ca_idequipo
      foreign: ca_idconcepto
      type: one
      class: Concepto

PricFleteBs:
  options:
    symfony:
      form: false
      filter: false
  generatePath: pricing
  tableName: pric.bs_fletes
  attributes:
    export: tables
  columns:
    ca_consecutivo:
      type: integer
      primary: true
    ca_idtrayecto: integer
    ca_idconcepto: integer
    ca_idequipo: integer
    ca_vlrneto: decimal
    ca_vlrsugerido: decimal
    ca_fchinicio: date
    ca_fchvencimiento: date
    ca_idmoneda: string
    ca_estado: string
    ca_aplicacion: string    
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fcheliminado: timestamp
  relations:
    Concepto:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: one
    Equipo:
      local: ca_idequipo
      foreign: ca_idconcepto
      type: one
      class: Concepto

PricRecargoxConcepto:
  options:
    symfony:
      form: false
      filter: false
  generatePath: pricing
  tableName: pric.tb_recargosxconcepto
  attributes:
    export: tables
  columns:
    ca_consecutivo:
      type: integer
      primary: true
    ca_idtrayecto: integer
    ca_idconcepto: integer
    ca_idrecargo: integer
    ca_idequipo: integer
    ca_vlrrecargo: decimal
    ca_aplicacion: string
    ca_vlrminimo: decimal
    ca_aplicacion_min: string
    ca_observaciones: string
    ca_fchinicio: date
    ca_fchvencimiento: date
    ca_idmoneda: string
    ca_aplicacion: string    
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fcheliminado: timestamp
  relations:
    Concepto:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: one
    TipoRecargo:
      local: ca_idrecargo
      foreign: ca_idrecargo
      type: one
    Equipo:
      local: ca_idequipo
      foreign: ca_idconcepto
      type: one
      class: Concepto

PricRecargoxConceptoBs:
  options:
    symfony:
      form: false
      filter: false
  generatePath: pricing
  tableName: pric.bs_recargosxconcepto
  attributes:
    export: tables
  columns:
    ca_consecutivo:
      type: integer
      primary: true
    ca_idtrayecto: integer
    ca_idconcepto: integer
    ca_idrecargo: integer
    ca_idequipo: integer
    ca_vlrrecargo: decimal
    ca_aplicacion: string
    ca_vlrminimo: decimal
    ca_aplicacion_min: string
    ca_observaciones: string
    ca_fchinicio: date
    ca_fchvencimiento: date
    ca_idmoneda: string
    ca_aplicacion: string    
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fcheliminado: timestamp
  relations:
    Concepto:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: one
    TipoRecargo:
      local: ca_idrecargo
      foreign: ca_idrecargo
      type: one
    Equipo:
      local: ca_idequipo
      foreign: ca_idconcepto
      type: one
      class: Concepto


PricRecargoxCiudad:
  options:
    symfony:
      form: false
      filter: false
  generatePath: pricing
  tableName: pric.tb_recargosxciudad
  attributes:
    export: tables
  columns:
    ca_idtrafico:
      type: string
      primary: true
    ca_idciudad:
      type: string
      primary: true
    ca_idrecargo:
      type: integer
      primary: true
    ca_modalidad:
      type: string
      primary: true
    ca_impoexpo:
      type: string
      primary: true
    ca_transporte:
      type: string
      primary: true
    ca_vlrrecargo: decimal
    ca_aplicacion: string
    ca_vlrminimo: decimal
    ca_aplicacion_min: string
    ca_observaciones: string
    ca_fchinicio: date
    ca_fchvencimiento: date
    ca_idmoneda: string
    ca_aplicacion: string
    ca_consecutivo: integer
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fcheliminado: timestamp
  relations:
    TipoRecargo:
      local: ca_idrecargo
      foreign: ca_idrecargo
      type: one
    Trafico:
      local: ca_idtrafico
      foreign: ca_idtrafico
      type: one
    Ciudad:
      local: ca_idciudad
      foreign: ca_idciudad
      type: one

PricRecargoxCiudadBs:
  options:
    symfony:
      form: false
      filter: false
  generatePath: pricing
  tableName: pric.bs_recargosxciudad
  attributes:
    export: tables
  columns:
    ca_idtrafico:
      type: string
      primary: true
    ca_idciudad:
      type: string
      primary: true
    ca_idrecargo:
      type: integer
      primary: true
    ca_modalidad:
      type: string
      primary: true
    ca_impoexpo:
      type: string
      primary: true
    ca_transporte:
      type: string
      primary: true
    ca_vlrrecargo: decimal
    ca_aplicacion: string
    ca_vlrminimo: decimal
    ca_aplicacion_min: string
    ca_observaciones: string
    ca_fchinicio: date
    ca_fchvencimiento: date
    ca_idmoneda: string
    ca_aplicacion: string
    ca_consecutivo: integer
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fcheliminado: timestamp
  relations:
    TipoRecargo:
      local: ca_idrecargo
      foreign: ca_idrecargo
      type: one
    Trafico:
      local: ca_idtrafico
      foreign: ca_idtrafico
      type: one
    Ciudad:
      local: ca_idciudad
      foreign: ca_idciudad
      type: one


PricRecargoxLinea:
  options:
    symfony:
      form: false
      filter: false
  generatePath: pricing
  tableName: pric.tb_recargosxlinea
  attributes:
    export: tables
  columns:
    ca_idtrafico:
      type: string
      primary: true
    ca_idlinea:
      type: integer
      primary: true
    ca_idrecargo:
      type: integer
      primary: true
    ca_idconcepto:
      type: integer
      primary: true
    ca_modalidad:
      type: string
      primary: true
    ca_impoexpo:
      type: string
      primary: true
    ca_transporte:
      type: string
      primary: true
    ca_vlrrecargo: decimal
    ca_aplicacion: string
    ca_vlrminimo: decimal
    ca_aplicacion_min: string
    ca_observaciones: string
    ca_fchinicio: date
    ca_fchvencimiento: date
    ca_idmoneda: string
    ca_aplicacion: string
    ca_consecutivo: integer
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fcheliminado: timestamp
  relations:
    Concepto:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: one
    TipoRecargo:
      local: ca_idrecargo
      foreign: ca_idrecargo
      type: one
    Trafico:
      local: ca_idtrafico
      foreign: ca_idtrafico
      type: one
    IdsProveedor:
      local: ca_idlinea
      foreign: ca_idproveedor
      type: one

PricRecargoxLineaBs:
  options:
    symfony:
      form: false
      filter: false
  generatePath: pricing
  tableName: pric.bs_recargosxlinea
  attributes:
    export: tables
  columns:
    ca_idtrafico:
      type: string
      primary: true
    ca_idlinea:
      type: integer
      primary: true
    ca_idrecargo:
      type: integer
      primary: true
    ca_idconcepto:
      type: integer
      primary: true
    ca_modalidad:
      type: string
      primary: true
    ca_impoexpo:
      type: string
      primary: true
    ca_transporte:
      type: string
      primary: true
    ca_vlrrecargo: decimal
    ca_aplicacion: string
    ca_vlrminimo: decimal
    ca_aplicacion_min: string
    ca_observaciones: string
    ca_fchinicio: date
    ca_fchvencimiento: date
    ca_idmoneda: string
    ca_aplicacion: string
    ca_consecutivo: integer
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fcheliminado: timestamp
  relations:
    Concepto:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: one
    TipoRecargo:
      local: ca_idrecargo
      foreign: ca_idrecargo
      type: one
    Trafico:
      local: ca_idtrafico
      foreign: ca_idtrafico
      type: one
    IdsProveedor:
      local: ca_idlinea
      foreign: ca_idproveedor
      type: one


PricPatio:
  options:
    symfony:
      form: false
      filter: false
  generatePath: pricing
  tableName: pric.tb_patios
  attributes:
    export: tables
  columns:
    ca_idpatio:
      type: integer
      primary: true
      autoincrement: true
    ca_nombre: string
    ca_idciudad: string
    ca_direccion: string
  relations:
     Ciudad:
      local: ca_idciudad
      foreign: ca_idciudad
      type: one

PricPatioLinea:
  options:
    symfony:
      form: false
      filter: false
  generatePath: pricing
  tableName: pric.tb_patioslinea
  attributes:
    export: tables
  columns:
    ca_idpatio:
      type: integer
      primary: true
    ca_idlinea:
      type: integer
      primary: true
    ca_transporte:
      type: string
      primary: true
    ca_modalidad:
      type: string
      primary: true
    ca_impoexpo:
      type: string
      primary: true
    ca_observaciones:
      type: string
  relations:
    PricPatio:
      local: ca_idpatio
      foreign: ca_idpatio
      type: one
    IdsProveedor:
      local: ca_idlinea
      foreign: ca_idproveedor
      type: one

PricRecargoParametro:
  options:
    symfony:
      form: false
      filter: false
  generatePath: pricing
  tableName: pric.tb_recargosparametros
  attributes:
    export: tables
  columns:
    ca_idlinea:
      type: integer
      primary: true
    ca_transporte:
      type: string
      primary: true
    ca_modalidad:
      type: string
      primary: true
    ca_impoexpo:
      type: string
      primary: true
    ca_concepto:
      type: string
      primary: true
    ca_valor: string
    ca_observaciones: string
    ca_fchcreado: timestamp
    ca_usucreado: string
  relations:
    IdsProveedor:
      local: ca_idlinea
      foreign: ca_idproveedor
      type: one

PricSeguro:
  options:
    symfony:
      form: false
      filter: false
  generatePath: pricing
  tableName: pric.tb_seguros
  attributes:
    export: tables
  columns:
    ca_idgrupo:
      type: integer
      primary: true
    ca_transporte:
      type: string
      primary: true
    ca_vlrprima: decimal
    ca_vlrminima: decimal
    ca_vlrobtencionpoliza: decimal
    ca_idmoneda: string
    ca_idmonedaobtencion: string
    ca_observaciones: string
    ca_fchcreado: timestamp
    ca_usucreado: string
  
PricNotificacion:
  options:
    symfony:
      form: false
      filter: false
  generatePath: pricing
  tableName: pric.tb_notificaciones
  attributes:
    export: tables
  columns:
    ca_idnotificacion:
      type: integer
      primary: true
      autoincrement: true
    ca_titulo: string
    ca_mensaje: string
    ca_caducidad: string
    ca_fchcreado: timestamp
    ca_usucreado: string



PricRecargoCliente:
  options:
    symfony:
      form: false
      filter: false
  generatePath: pricing
  tableName: pric.tb_recargos_cliente
  attributes:
    export: tables
  columns:
    ca_consecutivo:
      type: integer
      primary: true
    ca_idconcepto: integer
    ca_idcliente: integer
    ca_vlr1: decimal
    ca_vlr2: decimal
    ca_aplicacion: string
    ca_idmoneda: string
    ca_fchinicio: date
    ca_fchvencimiento: date
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fcheliminado: timestamp
  relations:
    InoConcepto:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: one
    Cliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: one


PricRecargoClienteBs:
  options:
    symfony:
      form: false
      filter: false
  generatePath: pricing
  tableName: pric.bs_recargos_cliente
  attributes:
    export: tables
  columns:
    ca_consecutivo:
      type: integer
      primary: true
    ca_idconcepto: integer
    ca_idcliente: integer
    ca_vlr1: decimal
    ca_vlr2: decimal
    ca_aplicacion: string
    ca_idmoneda: string
    ca_fchinicio: date
    ca_fchvencimiento: date
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fcheliminado: timestamp
  relations:
    InoConcepto:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: one
    Cliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: one


