Ciudad:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_ciudades
  columns:
    ca_idciudad:
      type: string(8)
      fixed: false
      primary: true
    ca_ciudad:
      type: string(50)
      fixed: false
      notnull: true
      primary: false
    ca_idtrafico:
      type: string(6)
      fixed: false
      notnull: true
      primary: false
    ca_puerto:
      type: string(10)
      fixed: false
      notnull: true
      primary: false
  relations:
    Trafico:
      local: ca_idtrafico
      foreign: ca_idtrafico
      type: one

Trafico:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_traficos
  columns:
    ca_idtrafico:
      type: string(6)
      fixed: false
      primary: true
    ca_nombre:
      type: string(40)
      fixed: false
      notnull: true
      primary: false
    ca_bandera:
      type: string(30)
      fixed: false
      notnull: true
      primary: false
    ca_idmoneda:
      type: string(3)
      fixed: false
      notnull: true
      primary: false
    ca_idgrupo:
      type: integer(2)
      unsigned: false
      notnull: true
      primary: false
    ca_link:
      type: string(256)
      fixed: false
      notnull: false
      primary: false
    ca_cod_dian:
      type: string(3)
      fixed: false
      notnull: false
      primary: false
  relations:
    TraficoGrupo:
      local: ca_idgrupo
      foreign: ca_idgrupo
      type: one
    Moneda:
      local: ca_idmoneda
      foreign: ca_idmoneda
      type: one    
    Ciudad:
      local: ca_idtrafico
      foreign: ca_idtrafico
      type: many

TraficoUsers:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_traficos_users
  columns:
    ca_idtrafico:
      type: string(6)
      primary: true
      notnull: true
    ca_impo: boolean
    ca_login:
      type: string(15)
      notnull: true
      primary: false
    ca_ciudad:
      type: string(15)
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
    ca_expo: boolean
  relations:
    Trafico:
      local: ca_idtrafico
      foreign: ca_idtrafico
      type: one
    Usuario:
      local: ca_login
      foreign: ca_login
      type: one
    Ciudad:
      local: ca_ciudad
      foreign: ca_idciudad
      type: one


TraficoGrupo:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_grupos
  columns:
    ca_idgrupo:
      type: integer(2)
      unsigned: false
      primary: true
    ca_descripcion:
      type: string(40)
      fixed: false
      notnull: true
      primary: false
  relations:
    Trafico:
      local: ca_idgrupo
      foreign: ca_idgrupo
      type: many


Moneda:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_monedas
  columns:
    ca_idmoneda:
      type: string(3)
      fixed: false
      primary: true
    ca_nombre:
      type: string(30)
      fixed: false
      notnull: true
      primary: false
    ca_referencia:
      type: string(3)
      fixed: false
      notnull: true
      primary: false
    ca_sugerido: boolean
  relations:
    Moneda:
      local: ca_referencia
      foreign: ca_idmoneda
      type: one
    Trafico:
      local: ca_idmoneda
      foreign: ca_idmoneda
      type: many


Email:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_emails
  columns:
    ca_idemail:
      type: integer
      primary: true
      autoincrement: true
    ca_fchenvio: timestamp
    ca_usuenvio: string
    ca_tipo: string
    ca_idcaso: string    
    ca_from: string
    ca_fromname: string
    ca_cc: string
    ca_replyto: string
    ca_address: string
    ca_attachment: string
    ca_subject: string
    ca_body: string
    ca_bodyhtml: string
    ca_readreceipt: boolean
    ca_fchcreado: timestamp
    ca_priority: integer
  relations:
     Reporte:
       local: ca_idcaso
       foreign: ca_idreporte
       type: one
     EmailAttachment:
      local: ca_idemail
      foreign: ca_idemail
      type: many
      
      
EmailAttachment:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_attachments
  columns:
    ca_idattachment:
      type: integer
      primary: true
      autoincrement: true
    ca_idemail: integer
    ca_extension: string
    ca_header_file: string
    ca_filesize: string
    ca_content: blob
  relations:
    Email:
      local: ca_idemail
      foreign: ca_idemail
      type: one


Festivo:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_festivos
  columns:
    ca_fchfestivo:
      type: date
      primary: true


Parametro:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_parametros
  columns:
    ca_casouso:
      type: string
      primary: true      
    ca_identificacion:
      type: integer
      primary: true
    ca_valor:
      type: string
      primary: true
    ca_valor2:
      type: string

Contacto:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_concliente
  columns:
    ca_idcontacto:
      type: integer
      primary: true
      autoincrement: true
    ca_idcliente: integer
    ca_papellido: string
    ca_sapellido: string
    ca_nombres: string
    ca_saludo: string
    ca_cargo: string
    ca_departamento: string
    ca_telefonos: string
    ca_fax: string
    ca_email: string
    ca_observaciones: string
    ca_fijo: boolean
    ca_fchcreado: string
    ca_fchcreado: string
  relations:
    Cliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: one


Concepto:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_conceptos
  columns:
    ca_idconcepto:
      type: integer
      primary: true
      autoincrement: true
    ca_concepto: string
    ca_unidad: string
    ca_transporte: string
    ca_modalidad: string
    ca_liminferior: integer
    ca_fcheliminado: timestamp
    ca_usueliminado: string


TipoRecargo:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_tiporecargo
  columns:
    ca_idrecargo:
      type: integer
      primary: true
      autoincrement: true
    ca_recargo: string
    ca_tipo: string
    ca_transporte: string
    ca_incoterms: string
    ca_fcheliminado: timestamp
    ca_usueliminado: string
#    ca_impoexpo: string
#    ca_impoexpo: string
  relations:
    InoConceptoModalidad:
      local: ca_idrecargo
      foreign: ca_idconcepto
      type: one
   

Costo:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_costos
  columns:
    ca_idcosto:
      type: integer
      primary: true
      autoincrement: true
    ca_costo: string
    ca_transporte: string
    ca_impoexpo: string
    ca_modalidad: string
    ca_comisionable: string
    ca_parametros: string
    ca_activo: boolean
    ca_conceptoopen: string
    
Deduccion:
  options:
    symfony:
      form: false
      filter: false
  generatePath: inoAnterior
  tableName: tb_deducciones
  columns:
    ca_iddeduccion:
      type: integer
      primary: true
    ca_deduccion : string
    ca_transporte : string
    ca_impoexpo : string
    ca_modalidad : string
    ca_habilitado : boolean
  relations:
    InoDeduccionesSea:
      local: ca_iddeduccion
      foreign: ca_iddeduccion
      type: many

ColNovedad:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_colnovedades
  columns:
    ca_idnovedad:
      type: integer
      primary: true
      autoincrement: true
    ca_fchpublicacion: date
    ca_asunto: string
    ca_detalle: string
    ca_fcharchivar: date
    ca_extension: string
    ca_header_file: string
    ca_content: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_icon: string
  relations:
    UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario


Sia:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_sia
  columns:
    ca_idsia:
      type: integer
      primary: true
      autoincrement: true
    ca_nombre: string
    ca_tel: string
    ca_contacto: string


Modalidad:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_modalidades
  columns:
    ca_idmodalidad:
      type: integer
      primary: true
      autoincrement: true
    ca_impoexpo: string
    ca_transporte: string
    ca_modalidad: string
    ca_fcheliminado: timestamp
    ca_usueliminado: string

StdCliente:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_stdcliente
  columns:
    ca_idcliente:
      type: integer
      primary: true
    ca_fchestado:
      type: timestamp
      primary: true
    ca_estado: string
    ca_empresa:
      type: string
      primary: true
  relations:
    Cliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: one


LibCliente:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_libcliente
  columns:
    ca_idcliente:
      type: integer
      primary: true
    ca_diascredito: integer
    ca_cupo: integer
    ca_observaciones: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
  relations:
    Cliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: one

Trms:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_trms
  columns:
    ca_fecha:
      type: date
      primary: true
    ca_pesos: numeric
    ca_euro: numeric

MandatosTipo:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_mandatos_tipo
  columns:
    ca_idtipo:
      type: integer
      primary: true
    ca_tipo:
      type: string(255)
      notnull: true
    ca_clase: string(32)
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
  relations:
    ManCliente:
      local: ca_idtipo
      foreign: ca_idtipo
      type: many

ManCliente:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_mancliente
  columns:
    ca_idcliente:
      type: integer
      primary: true
    ca_idciudad:
      type: string(8)
      primary: true
    ca_idtipo:
      type: integer
      primary: true
    ca_idarchivo: integer
    ca_observaciones: string(255)
    ca_fchradicado: date
    ca_fchvencimiento: date
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
  relations:
    Cliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: one
    Ciudad:
      local: ca_idciudad
      foreign: ca_idciudad
      type: one
    MandatosTipo:
      local: ca_idtipo
      foreign: ca_idtipo
      type: one
    Archivos:
      local: ca_idarchivo
      foreign: ca_idarchivo
      type: one
    UsuCreado:
      local: ca_usucreado
      foreign: ca_login
      type: one
      class: Usuario

DocCliente:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_doccliente
  columns:
    ca_iddocumento:
      type: integer
      notnull: true
      primary: true
    ca_fchdocumento:
      type: date   
      notnull: true
    ca_idcliente:
      type: integer
      notnull: true
      primary: true
    ca_idtipo:
      type: integer
    ca_observaciones:
      type: text      
    ca_usucreado: string(20)
    ca_fchcreado: timestamp
    ca_usuactualizado: string(20)
    ca_fchactualizado: timestamp  
  relations:
    Cliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: one
    ColsysConfigValue:
      local: ca_iddocumento
      foreign: ca_idvalue
      type: one
    Documentosxconc:
      local: ca_idtipo
      foreign: ca_id
      type: one
     
BlcCliente:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_blccliente
  columns:
    ca_idcliente: 
      type: integer 
      notnull: true
      primary: true
    ca_anno:
      type: integer
      notnull: true
      primary: true
    ca_activostotales: integer
    ca_activoscorrientes: integer
    ca_pasivostotales: integer
    ca_pasivoscorrientes: integer
    ca_inventarios: integer
    ca_patrimonios: integer
    ca_utilidades: integer
    ca_ventas: integer
    ca_fchcreado:
      type: date
      notnull: true
    ca_usucreado:
      type: string(20) 
      notnull: true
    ca_fchanulado: date
    ca_usuanulado: string(20)
  relations:
    Cliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: one
      
Smlv:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_smlv
  columns:
    ca_anno:
      type: integer
      primary: true
      notnull: true
    ca_smlv:
      type: integer   
      
AduCliente:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_aducliente
  columns:
    ca_idcliente: 
      type: integer      
      primary: true
    ca_idagaduana:
      type: integer      
      primary: true
    ca_fchautorizacion: date
    ca_fchvigencia: date
    ca_iddocumento: integer
    ca_fchanulado: timestamp
    ca_usuanulado: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
  relations:
    Cliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: one
    Ids:
      local: ca_idagaduana
      foreign: ca_id
      type: one
    Archivos:
      local: ca_iddocumento
      foreign: ca_idarchivo
      type: one

FichaTecnica:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_ficha_tecnica
  columns:
    ca_documentacion:
      type: json
    ca_transporteinternacional:
      type: json
    ca_idcliente:
      type: integer
      notnull: true
      primary: true
    ca_contactos:
      type: json
    ca_usucreado: string(20)
    ca_fchcreado: timestamp
    ca_usuactualizado: string(20)
    ca_fchactualizado: timestamp
  relations:
    Cliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: one

PorcentajesComisiones:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_porcentajescomisiones
  columns:
    ca_idcliente: 
      type: integer   
      primary: true
      notnull: true
    ca_inicio:
      primary: true
      type: date
      notnull: true
    ca_fin:
      primary: true
      type: date
      notnull: true
    ca_porcentaje: numeric
    ca_fchcreado: timestamp 
    ca_usucreado: string(15)
    ca_empresa: 
      type: string(20)
      primary: true
      notnull: true
    ca_fchactualizado: timestamp
    ca_usuactualizado: string(20)
  relations:
    Cliente:
      local: ca_idcliente
      foreign: ca_idcliente
      type: one
    Usuario:
      local: ca_usucreado
      foreign: ca_login
      type: one

DianReservado:
  options:
    symfony:
      form: false
      filter: false
  generatePath: public
  tableName: tb_dianreservados
  columns:
    ca_numero_resv: 
      type: integer   
      primary: true
      notnull: true
    ca_anno: numeric
    ca_numenvio: numeric
    ca_fchreservado: timestamp
    ca_usureservado: string(20)
  
MaestraClasificacion:
  options:
    symfony:
      form: false
      filter: flase
  generatePath: public
  tableName: tb_maestra_clasificacion
  columns:
    ca_idclasificacion:
      type: integer
      notnull: true
      primary: true
      autoincrement: true
    ca_idpadre: integer
    ca_nombre: string
    ca_tipo: string
    ca_datos: string
    ca_estado: string
  relations:
    ClasificacionPadre:
      local: ca_idclasificacion
      foreign: ca_idpadre
      type: one
      class: MaestraClasificacion
    ClasificacionHijos:
      local: ca_idpadre
      foreign: ca_idclasificacion
      type: one
      class: MaestraClasificacion