
RepGerInforme:
  options:
    symfony:
      form: false
      filter: false
  generatePath: repger
  tableName: repger.tb_informes
  attributes:
    export: tables
  columns:
    ca_idinforme:
      type: integer
      primary: true
      autoincrement: true
    ca_titulo: string
    ca_categoria: string
  relations:
    RepGerCampo:
      local: ca_idinforme
      foreign: ca_idinforme
      type: many
  

RepGerCampo:
  options:
    symfony:
      form: false
      filter: false
  generatePath: repger
  tableName: repger.tb_campos
  attributes:
    export: tables
  columns:
    ca_idcampo:
      type: integer
      primary: true
      autoincrement: true
    ca_idinforme: integer
    ca_campo: string
    ca_nombre: string
    ca_tipo: string    
    ca_agrupar: boolean
    ca_filtrar: boolean
    ca_agregacion: string
  relations:
    RepGerInforme:
      local: ca_idinforme
      foreign: ca_idinforme
      type: one




RepCargaTraficos:
  options:
    symfony:
      form: false
      filter: false
  generatePath: repger
  tableName: vi_repcargatraficos
  columns:
    ca_fchreferencia: date
    ca_referencia:
      type: string
      primary: true
    ca_origen: string
    ori_ca_ciudad : string
    ca_destino: string
    des_ca_ciudad : string
    ori_ca_idtrafico: string(6)
    ori_ca_nombre: string(40)
    des_ca_idtrafico: string(6)
    des_ca_nombre: string(40)
    ca_modalidad : string
    ca_idlinea: integer
    ca_concepto :
      type: string
      primary: true
    ca_nombre: string
    teus : integer
    ncontenedores : integer
    piezas: integer
    peso: numeric
    volumen : numeric  