Reporte:
  options:
    symfony:
      form: true
      filter: false
  generatePath: reportes
  tableName: tb_reportes
  columns:
    ca_idreporte:
      type: integer
      autoincrement: true
      primary: true
    ca_fchreporte: date
    ca_consecutivo: string
    ca_version: integer
    ca_idcotizacion: string
    ca_idproducto: integer
    ca_origen:
      type: string
    ca_destino:
      type: string
    ca_impoexpo:
      type: string
      notnull: true
    ca_fchdespacho:
      type: date
      notnull: true
    ca_idagente: integer
    ca_idsucursalagente: integer
    ca_incoterms: string
    ca_mercancia_desc:
      type: string
      notnull: true
    ca_idproveedor: string
    ca_orden_prov: string
    ca_idconcliente:
      type: integer
      notnull: true
    ca_orden_clie:
      type: string
      notnull: true
    ca_confirmar_clie: string
    ca_idrepresentante: integer
    ca_informar_repr: string
    ca_idconsignatario: integer
    ca_informar_cons: string
    ca_idnotify: integer
    ca_informar_noti: string
    ca_idmaster: integer
    ca_informar_mast: string
    ca_notify: integer
    ca_transporte: string
    ca_modalidad: string
    ca_seguro: string
    ca_liberacion: string
    ca_tiempocredito: string
    ca_comodato: string
    ca_preferencias_clie: string
    ca_instrucciones: string
    ca_idlinea: integer
    ca_idconsignar: integer
    ca_idconsignarmaster: integer
    ca_idbodega: integer
    ca_mastersame: string
    ca_continuacion: string
    ca_continuacion_dest: string
    ca_continuacion_conf: string
    ca_etapa_actual: string
    ca_login: string
    ca_colmas: string
    ca_propiedades: string
    ca_idetapa: string
    ca_fchultstatus: timestamp
    ca_idtarea_rext: integer
    ca_idtarea_antecedente: integer
    ca_detanulado: string
    ca_mcia_peligrosa: boolean
    ca_idgrupo: integer
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
    ca_fchanulado: timestamp
    ca_usuanulado: string
    ca_fchcerrado: timestamp
    ca_usucerrado: string
    ca_idclientefac: numeric
    ca_idclienteag: numeric
    ca_idclienteotro: numeric
    ca_cont_origen: integer
    ca_cont_destino: integer
    ca_idcotizacionotm: string
    ca_idproductootm: integer
    ca_tiporep: integer
    ca_declaracionant: boolean
  relations:
    RepStatus:
      local: ca_idreporte
      foreign: ca_idreporte
      type: many
    RepTarifa:
      local: ca_idreporte
      foreign: ca_idreporte
      type: many
    RepGasto:
      local: ca_idreporte
      foreign: ca_idreporte
      type: many
    RepAsignacion:
      local: ca_idreporte
      foreign: ca_idreporte
      type: many
    Usuario:
      local: ca_login
      foreign: ca_login
      type: one
    Contacto:
      local: ca_idconcliente
      foreign: ca_idcontacto
      type: one
    TrackingEtapa:
      local: ca_idetapa
      foreign: ca_idetapa
      type: one
    Origen:
      local: ca_origen
      foreign: ca_idciudad
      type: one
      class: Ciudad
    Destino:
      local: ca_destino
      foreign: ca_idciudad
      type: one
      class: Ciudad
    DestinoCont:
      local: ca_continuacion_dest
      foreign: ca_idciudad
      type: one
      class: Ciudad
    NotTareaAntecedente:
      local: ca_idtarea_antecedente
      foreign: ca_idtarea
      type: one
      class: NotTarea
    RepEquipo:
      local: ca_idreporte
      foreign: ca_idreporte
      type: many
    InoClientesSea:
      local: ca_idreporte
      foreign: ca_idreporte
      type: one
    Bodega:
      local: ca_idbodega
      foreign: ca_idbodega
      type: one
    IdsAgente:
      local: ca_idagente
      foreign: ca_idagente
      type: one
    IdsSucursal:
      local: ca_idsucursalagente
      foreign: ca_idsucursal
      type: one
    IdsProveedor:
      local: ca_idlinea
      foreign: ca_idproveedor
      type: one
    Proveedor:
      local: ca_idproveedor
      foreign: ca_idtercero
      type: one
      class: Tercero
    GrupoReporte:
      local: ca_idgrupo
      foreign: ca_idreporte
      type: one
      class: Reporte
    ClienteFac:
      local: ca_idclientefac
      foreign: ca_idcliente
      type: one
      class: Cliente
    ClienteAg:
      local: ca_idclienteag
      foreign: ca_idcliente
      type: one
      class: Cliente
    ClienteOtro:
      local: ca_idclienteotro
      foreign: ca_idcliente
      type: one
      class: Cliente
    ContOrigen:
      local: ca_cont_origen
      foreign: ca_idbodega
      type: one
      class: Bodega
    ContDestino:
      local: ca_cont_destino
      foreign: ca_idbodega
      type: one
      class: Bodega
    RepExpo:
      local: ca_idreporte
      foreign: ca_idreporte
      type: one
    RepCosto:
      local: ca_idreporte
      foreign: ca_idreporte
      type: many
    RepOtm:
      local: ca_idreporte
      foreign: ca_idreporte
      type: one

RepStatus:
  options:
    symfony:
      form: false
      filter: false
  generatePath: reportes
  tableName: tb_repstatus
  columns:
    ca_idstatus:
      type: integer
      autoincrement: true
      primary: true
    ca_idreporte: integer
    ca_idemail: integer
    ca_fchstatus: date
    ca_status: string
    ca_comentarios: string
    ca_fchrecibo: timestamp
    ca_fchenvio: timestamp
    ca_usuenvio: string
    ca_introduccion: string
    ca_fchsalida: date
    ca_fchllegada: date
    ca_fchcontinuacion: date
    ca_piezas: string
    ca_peso: string
    ca_volumen: string
    ca_doctransporte: string
    ca_idnave: string
    ca_docmaster: string
    ca_equipos: string
    ca_horasalida: string
    ca_horallegada: string
    ca_idetapa: string
    ca_propiedades: string
    ca_observaciones_idg: string
  relations:
    Reporte:
      local: ca_idreporte
      foreign: ca_idreporte
      type: one
    Email:
      local: ca_idemail
      foreign: ca_idemail
      type: one
    TrackingEtapa:
      local: ca_idetapa
      foreign: ca_idetapa
      type: one
    RepStatusRespuesta:
      local: ca_idstatus
      foreign: ca_idstatus
      type: many


RepStatusRespuesta:
  options:
    symfony:
      form: false
      filter: false
  generatePath: reportes
  tableName: tb_repstatusrespuestas
  columns:
    ca_idrepstatusrespuestas:
      type: integer
      autoincrement: true
      primary: true
    ca_idstatus: integer
    ca_respuesta: string
    ca_email: string
    ca_login: string
    ca_fchcreado: string
  relations:
    RepStatus:
      local: ca_idstatus
      foreign: ca_idstatus
      type: one
    Usuario:
      local: ca_login
      foreign: ca_login
      type: one



TrackingEtapa:
  options:
    symfony:
      form: false
      filter: false
  generatePath: reportes
  tableName: tb_tracking_etapas
  columns:
    ca_idetapa:
      type: string
      primary: true
    ca_impoexpo: string
    ca_transporte: string
    ca_departamento: string
    ca_etapa: string
    ca_orden: integer
    ca_ttl: integer
    ca_class: string
    ca_template: string
    ca_message: string
    ca_message_default: string
    ca_intro: string
    ca_title: string
    ca_preasunto: string

Tercero:
  options:
    symfony:
      form: false
      filter: false
  generatePath: reportes
  tableName: tb_terceros
  columns:
    ca_idtercero:
      type: string
      primary: true
      autoincrement: true
    ca_nombre: string
    ca_contacto: string
    ca_direccion: string
    ca_telefonos: string
    ca_fax: string
    ca_idciudad: string
    ca_email: string
    ca_vendedor: string
    ca_tipo: string
    ca_identificacion: string
    ca_idciudad: string
    ca_usucreado: string
    ca_fchcreado: timestamp
    ca_usuactualizado: string
    ca_fchactualizado: timestamp
  relations:
    Ciudad:
      local: ca_idciudad
      foreign: ca_idciudad
      type: one

RepEquipo:
  options:
    symfony:
      form: false
      filter: false
  generatePath: reportes
  tableName: tb_repequipos
  columns:
    ca_idreporte:
      type: integer
      primary: true
    ca_idconcepto:
      type: integer
      primary: true
    ca_cantidad: decimal
    ca_idequipo: string
    ca_observaciones: string
  relations:
    Reporte:
      local: ca_idreporte
      foreign: ca_idreporte
      type: one
    Concepto:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: one

Bodega:
  generatePath: reportes
  tableName: tb_bodegas
  columns:
    ca_idbodega:
      type: integer
      primary: true
      autoincrement: true
    ca_nombre: string(80)
    ca_tipo: string
    ca_transporte: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string

RepTarifa:
  options:
    symfony:
      form: false
      filter: false
  generatePath: reportes
  tableName: tb_reptarifas
  columns:
    ca_idreporte: integer
    ca_idconcepto: integer      
    ca_cantidad: decimal
    ca_neta_tar: decimal
    ca_neta_min: decimal
    ca_neta_idm: string
    ca_reportar_tar: decimal
    ca_reportar_min: decimal
    ca_reportar_idm: string
    ca_cobrar_tar: decimal
    ca_cobrar_min: decimal
    ca_cobrar_idm: string
    ca_observaciones: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
    ca_idreptarifa:
      type: integer
      autoincrement: true
      primary : true
    ca_tipo:
      type: integer
      notnull: true
  relations:
    Reporte:
      local: ca_idreporte
      foreign: ca_idreporte
      type: one
    Concepto:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: one

RepGasto:
  options:
    symfony:
      form: false
      filter: false
  generatePath: reportes
  tableName: tb_repgastos
  columns:
    ca_idrepgasto :
      type: integer
      autoincrement: true      
      primary : true
    ca_idreporte: integer      
    ca_idconcepto: integer      
    ca_idrecargo: integer      
    ca_idequipo: integer      
    ca_aplicacion: string
    ca_tipo: string
    ca_neta_tar: decimal
    ca_neta_min: decimal
    ca_reportar_tar: decimal
    ca_reportar_min: decimal
    ca_cobrar_tar: decimal
    ca_cobrar_min: decimal
    ca_idmoneda: string
    ca_detalles: string
    ca_recargoorigen: bool
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
  relations:
    Reporte:
      local: ca_idreporte
      foreign: ca_idreporte
      type: one
    TipoRecargo:
      local: ca_idrecargo
      foreign: ca_idrecargo
      type: one
    Concepto:
      local: ca_idconcepto
      foreign: ca_idconcepto
      type: one
    Equipo:
      local: ca_idequipo
      foreign: ca_idconcepto
      type: one
      class: Concepto


RepSeguro:
  options:
    symfony:
      form: true
      filter: false
  generatePath: reportes
  tableName: tb_repseguro
  attributes:
    export: tables
  columns:
    ca_idreporte:
      type: integer
      primary: true
    ca_vlrasegurado:
      type: decimal
      notnull: true
    ca_idmoneda_vlr: string
    ca_primaventa:
      type: decimal
      notnull: true
    ca_minimaventa:
      type: decimal
      notnull: true
    ca_idmoneda_vta: string
    ca_obtencionpoliza:
      type: decimal
      notnull: true
    ca_idmoneda_pol: string
    ca_seguro_conf:
      type: string
      notnull: true
  relations:
    Reporte:
      local: ca_idreporte
      foreign: ca_idreporte
      type: one

RepAduana:
  options:
    symfony:
      form: true
      filter: false
  generatePath: reportes
  tableName: tb_repaduana
  attributes:
    export: tables
  columns:
    ca_idreporte:
      type: integer
      primary: true
    ca_instrucciones: string
    ca_coordinador: string
    ca_transnacarga: string
    ca_transnatipo: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
  relations:
    Reporte:
      local: ca_idreporte
      foreign: ca_idreporte
      type: one
    Usuario:
      local: ca_coordinador
      foreign: ca_login
      type: one


RepExpo:
  options:
    symfony:
      form: true
      filter: false
  generatePath: reportes
  tableName: tb_repexpo
  attributes:
    export: tables
  columns:
    ca_idreporte:
      type: integer
      primary: true
    ca_peso: string
    ca_volumen: string
    ca_piezas: string
    ca_dimensiones: string
    ca_valorcarga: numeric
    ca_anticipo: string
    ca_idsia:
      type: integer
      notnull: true
    ca_tipoexpo: integer
    ca_idlineaterrestre: integer
    ca_motonave: string(50)
    ca_emisionbl: string(10)
    ca_datosbl: string
    ca_numbl: integer
    ca_inspeccion_fisica: boolean
  relations:
    Reporte:
      local: ca_idreporte
      foreign: ca_idreporte
      type: one
    Sia:
      local: ca_idsia
      foreign: ca_idsia
      type: one


RepAsignacion:
  options:
    symfony:
      form: false
      filter: false
  generatePath: reportes
  tableName: tb_repasignaciones
  attributes:
    export: tables
  columns:
    ca_idreporte:
      type: integer
      primary: true
    ca_idtarea:
      type: integer
      primary: true
  relations:
    Reporte:
      local: ca_idreporte
      foreign: ca_idreporte
      type: one
    NotTarea:
      local: ca_idtarea
      foreign: ca_idtarea
      type: one

RepCosto:
  options:
    symfony:
      form: false
      filter: false
  generatePath: reportes
  tableName: tb_repaduanadet
  attributes:
    export: tables
  columns:
    ca_idreporte:
      type: integer
      primary: true
    ca_idcosto:
      type: integer
      primary: true
    ca_tipo: string
    ca_vlrcosto: decimal
    ca_mincosto: decimal
    ca_netcosto: decimal
    ca_idmoneda: string
    ca_detalles: string
    ca_aplicacion: string
    ca_aplicacionminimo: string
    ca_parametro: string
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string
  relations:
    Reporte:
      local: ca_idreporte
      foreign: ca_idreporte
      type: one
    Costo:
      local: ca_idcosto
      foreign: ca_idcosto
      type: one
      
      
      
RepOtm:
  options:
    symfony:
      form: false
      filter: false
  generatePath: reportes
  tableName: tb_repotm
  attributes:
    export: tables
  columns:
    ca_idreporte:
      type: integer
      primary: true    
    ca_referencia: string,
    ca_idcliente: integer,  
    ca_hbls: string,
    ca_origenimpo: string,
    ca_idproveedor: integer,
    ca_numpiezas: numeric,
    ca_peso: numeric,
    ca_volumen: numeric,
    ca_valorfob: numeric,
    ca_fcharribo: date,
    ca_manifiesto: string,
    ca_idtransportador: integer,
    ca_doctransporte: string,
    ca_fchdoctransporte: date,
    ca_codadupartida: integer,
    ca_codadudestino: integer,
    ca_fchcreado: timestamp
    ca_usucreado: string
    ca_fchactualizado: timestamp
    ca_usuactualizado: string,
    ca_numpiezasun: string,
    ca_pesoun: string,
    ca_volumenun: string
    ca_idimportador: string
    ca_motonave: string
    ca_muelle : integer
  relations:
    Reporte:
      local: ca_idreporte
      foreign: ca_idreporte
      type: one
    Referencia:
      local: ca_referencia
      foreign: ca_referencia
      type: one
    Origenimp:
      local: ca_origenimpo
      foreign: ca_idciudad
      type: one
      class: Ciudad
    Cliente:
      local: ca_idcliente
      foreign: ca_idtercero
      type: one
      class: Tercero
    Tercero:
       local: ca_idproveedor
       foreign: ca_idtercero
       type: one
    Importador:
      local: ca_idimportador
      foreign: ca_idtercero
      type: one
      class: Tercero
    InoDianDepositos:
      local: ca_muelle
      foreign: ca_codigo