Sdn:
  options:
    symfony:
      form: false
      filter: false
  generatePath: sdn
  tableName: tb_sdn
  columns:
    ca_uid:
      type: integer
      primary: true
    ca_firstname: string
    ca_lastname: string
    ca_title: string
    ca_sdntype: string
    ca_remarks: string
  relations:
    SdnId:
      local: ca_uid
      foreign: ca_uid
      type: many
    SdnAka:
      local: ca_uid
      foreign: ca_uid
      type: many
    SdnAddress:
      local: ca_uid
      foreign: ca_uid
      type: many

SdnId:
  options:
    symfony:
      form: false
      filter: false
  generatePath: sdn
  tableName: tb_sdnid
  columns:
    ca_uid:
      type: integer
      primary: true
    ca_uid_id:
      type: integer
      primary: true
    ca_idtype: string
    ca_idnumber: string
    ca_idcountry: string
    ca_issuedate: string
    ca_expirationdate: string
  relations:
    Sdn:
      local: ca_uid
      foreign: ca_uid
      type: one

SdnAka:
  options:
    symfony:
      form: false
      filter: false
  generatePath: sdn
  tableName: tb_sdnaka
  columns:
    ca_uid:
      type: integer
      primary: true
    ca_uid_aka:
      type: integer
      primary: true
    ca_type: string
    ca_category: string
    ca_firstname: string
    ca_lastname: string
  relations:
    Sdn:
      local: ca_uid
      foreign: ca_uid
      type: one

SdnAddress:
  options:
    symfony:
      form: false
      filter: false
  generatePath: sdn
  tableName: tb_sdnaddress
  columns:
    ca_uid:
      type: integer
      primary: true
    ca_uid_address:
      type: integer
      primary: true
    ca_address1: string
    ca_address2: string
    ca_address3: string
    ca_city: string
    ca_state: string
    ca_postal: string
    ca_country: string
  relations:
    Sdn:
      local: ca_uid
      foreign: ca_uid
      type: one
